Repository frankframework/frankframework, pull requests merged in 2022-07, with the labels that each got.

#3507 Reduce the use of org.json and use javax.json instead
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/pipes/JsonWellFormedChecker.java
  core/src/test/java/nl/nn/adapterframework/pipes/JsonWellFormedCheckerTest.java
Labels: Performance, Technical Debt

#3504 Migrate Javax Mail to Jakarta
  aspose/pom.xml
  core/pom.xml
  ifsa/pom.xml
  pom.xml
Labels: dependencies

#3531 Skip PdfPipe tests with wrong timezone
  aspose/pom.xml
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/AsposeFontManager.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/CisConversionService.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/CisConversionServiceImpl.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/ConvertorFactory.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/MailConvertor.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PdfAttachmentUtil.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/WordConvertor.java
  aspose/src/test/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipeTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/TestAssertions.java
  pom.xml
Labels: CI
