Repository frankframework/frankframework, pull requests merged in 2023-03, with the labels that each got.

#4579 Fixing build with maven 3.9.0
  .github/workflows/maven-build.yml
  .mvn/wrapper/maven-wrapper.properties
  copyrightExcludeFile.txt
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  mvnw
  mvnw.cmd
Labels: Bug

#4592 (7.8) Fix GitHub Actions Maven build (#4579)
  .github/workflows/maven-build.yml
  .mvn/wrapper/maven-wrapper.properties
  copyrightExcludeFile.txt
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  mvnw
  mvnw.cmd
Labels: Bug, Backport

#4591 (7.7) Fix GitHub Actions Maven build (#4579)
  .github/workflows/maven-build.yml
  .mvn/wrapper/maven-wrapper.properties
  copyrightExcludeFile.txt
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  mvnw
  mvnw.cmd
Labels: Bug, Backport

#4582 Bump Ladybug from 2.3-20230217.183249 to 2.3-20230302.190234
  ladybug/pom.xml
Labels: Backport

#4596 Refactor code that uses Commons Upload dependency
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/extensions/api/ApiStreamPipe.java
  core/src/main/java/nl/nn/adapterframework/http/RestListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/http/RestServiceDispatcher.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcIteratingPipeBase.java
  core/src/main/java/nl/nn/adapterframework/pipes/StreamPipe.java
Labels: Performance, Technical Debt

#4625 Bump Ladybug from 2.3-20230302.190234 to 2.3-20230310.190611
  ladybug/pom.xml
  ladybug/src/main/resources/springIbisTestTool.xml
Labels: Backport

#4641 Add Narayana logger configurable through Log Settings page
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/UpdateLoggingConfig.java
  core/src/main/resources/log4j4ibis.xml
Labels: Backport

#4660 Add blob attributes to ResultSetIteratingPipe
  core/src/main/java/nl/nn/adapterframework/jdbc/BlobLineIteratingPipe.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcIteratingPipeBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/LobLineIteratingPipeBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipe.java
  core/src/main/java/nl/nn/adapterframework/jdbc/ResultSetIterator.java
  core/src/main/java/nl/nn/adapterframework/util/ReaderLineIterator.java
  core/src/test/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipeTest.java
  core/src/test/resources/Pipes/ResultSetIteratingPipe/testCompressedAndUncompressedBlob.xml
Labels: Backport

#4649 Remove message reference from TestFileUtils
  aspose/src/test/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipeTest.java
  aws/pom.xml
  core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java
  core/src/test/java/nl/nn/adapterframework/filesystem/IFileHandler.java
  core/src/test/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/CompressPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/IteratingPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/MessageSendingPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/StreamLineIteratorPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java
  core/src/test/java/nl/nn/adapterframework/senders/XsltSenderTest.java
  core/src/test/java/nl/nn/adapterframework/soap/SoapValidatorTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/MessageTestUtils.java
  core/src/test/java/nl/nn/adapterframework/testutil/TestFileUtils.java
  core/src/test/java/nl/nn/adapterframework/util/FileHandlerTestBase.java
  credentialProvider/.project
  pom.xml
Labels: Technical Debt

#4673 Create bean to validate database connectivity
  .github/workflows/maven-build.yml
  cmis/pom.xml
  core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java
  core/src/main/java/nl/nn/adapterframework/lifecycle/VerifyDatabaseConnectionBean.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java
  core/src/main/resources/SpringApplicationContext.xml
  core/src/test/java/nl/nn/adapterframework/jdbc/ResultSetIteratingPipeTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/MockIbisManager.java
  pom.xml
  test/pom.xml
Labels: Backport

#4680 Improve display of ConnectionFactory info
  core/src/main/java/nl/nn/adapterframework/jms/MessagingSource.java
  webapp/src/main/webapp/iaf/gui/js/controllers.js
  webapp/src/main/webapp/iaf/gui/js/services.js
Labels: Backport

#4691 Fix expectations in tests after an error message had been changed
  test/src/test/testtool/FxF3/12/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario03/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario07/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario09/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario11/md-select-result.xml
Labels: Bug, Frank Framework

#4693 Remove double slash in monitoring url
  webapp/src/main/webapp/iaf/gui/js/controllers.js
Labels: Bug, Backport

#4696 Bump Ladybug from 2.3-20230310.190611 to 2.3-20230327.174500 (7.8)
  ladybug/pom.xml
Labels: Backport

#4709 Lock transient dependencies and LCM icu4j
  core/pom.xml
Labels: Backport
