Repository frankframework/frankframework, pull requests merged in 2023-09, with the labels that each got.

#5316 ASPOSE: Strip MimeType params for converters (7.8)
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/CisConversionServiceImpl.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/AbstractConvertor.java
  aspose/src/test/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipeTest.java
  aspose/src/test/resources/Util/MessageUtils/utf8-with-bom.txt
Labels: Backport

#5311 Fix detection of named params
  core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java
  core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
Labels: Backport

#5312 Add ContentDisposition header to WSS responses
  core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java
Labels: Backport

#5318 Allow global setting for the use of eTags and disable by default (7.8)
  RELEASES.md
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
Labels: Backport

#5336 Create 1 Tika config and catch InvalidMimeTypeExceptions (7.8)
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/util/MessageUtils.java
Labels: Backport

#5346 Fix Job response not read and closed (#5340) - backport
  akamai/pom.xml
  aspose/pom.xml
  cmis/pom.xml
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/scheduler/job/SendMessageJob.java
  core/src/test/java/nl/nn/adapterframework/scheduler/job/SendMessageJobTest.java
  credentialProvider/pom.xml
  ibm/pom.xml
  idin/pom.xml
  ladybug/pom.xml
  larva/pom.xml
  pom.xml
  test-integration/pom.xml
Labels: Backport

#5300 Fix session key resources closed unexpectedly
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapter.java
  core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisJavaSender.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/util/Misc.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionBaseTest.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionTest.java
  core/src/test/java/nl/nn/adapterframework/http/cxf/SoapProviderStub.java
  core/src/test/java/nl/nn/adapterframework/http/cxf/SoapProviderTest.java
  core/src/test/java/nl/nn/adapterframework/monitoring/MessageCapturingEchoSender.java
  core/src/test/java/nl/nn/adapterframework/monitoring/MonitorTest.java
  core/src/test/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapterTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/PipeTestBase.java
  core/src/test/java/nl/nn/adapterframework/senders/IbisLocalSenderTest.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
  core/src/test/java/nl/nn/adapterframework/util/MiscTest.java
  iaf-commons/src/main/java/nl/nn/adapterframework/util/StreamUtil.java
Labels: Bug

#5348 Close Message of sendMessageOrThrow to avoid leaks / open resources
  .gitignore
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisHttpSender.java
  core/src/main/java/nl/nn/adapterframework/batch/RecordXml2Sender.java
  core/src/main/java/nl/nn/adapterframework/batch/ResultBlock2Sender.java
  core/src/main/java/nl/nn/adapterframework/extensions/javascript/J2V8.java
  core/src/main/java/nl/nn/adapterframework/extensions/javascript/Nashorn.java
  core/src/main/java/nl/nn/adapterframework/extensions/svn/ScanTibcoSolutionPipe.java
  core/src/main/java/nl/nn/adapterframework/extensions/svn/SvnUtils.java
  core/src/main/java/nl/nn/adapterframework/jdbc/Result2LobWriterBase.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsListenerBase.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/BrowseJdbcTable.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/ExecuteJdbcQuery.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/IbisstoreSummary.java
  core/src/main/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapter.java
  core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/scheduler/ServiceJob.java
  core/src/main/java/nl/nn/adapterframework/scheduler/job/CleanupDatabaseJob.java
  core/src/main/java/nl/nn/adapterframework/scheduler/job/ExecuteQueryJob.java
  core/src/main/java/nl/nn/adapterframework/scheduler/job/SendMessageJob.java
  core/src/main/java/nl/nn/adapterframework/senders/ShadowSender.java
  core/src/test/java/nl/nn/adapterframework/management/bus/endpoints/TestExecuteJdbcQuery.java
  core/src/test/java/nl/nn/adapterframework/receivers/JavaListenerTest.java
  core/src/test/java/nl/nn/adapterframework/senders/ShadowSenderTest.java
  larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
  larva/src/main/java/nl/nn/adapterframework/testtool/queues/QueueCreator.java
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
Labels: Feature

#5354 Code clean up; JUnit 5 conversions; keep naming conventions
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  core/src/main/java/nl/nn/adapterframework/ftp/FtpSession.java
  core/src/main/java/nl/nn/adapterframework/lifecycle/servlets/ServletAuthenticatorBase.java
  core/src/main/java/nl/nn/adapterframework/management/bus/MessageDispatcher.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/Monitoring.java
  core/src/main/java/nl/nn/adapterframework/pipes/CleanupOldFilesPipe.java
  core/src/main/java/nl/nn/adapterframework/soap/SoapValidator.java
  core/src/main/java/nl/nn/adapterframework/util/CalendarParser.java
  core/src/main/java/nl/nn/adapterframework/util/CompactSaxHandler.java
  core/src/test/java/nl/nn/adapterframework/collection/CollectionSenderTest.java
  core/src/test/java/nl/nn/adapterframework/compression/TestZipWriterSender.java
  core/src/test/java/nl/nn/adapterframework/filesystem/BasicFileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemTestBase.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FtpFileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/SftpFileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/dbms/MariaDbDbmsSupportTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/dbms/SqlTranslatorOracleToH2Test.java
  core/src/test/java/nl/nn/adapterframework/jdbc/transformer/ToCsvTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/transformer/ToJsonTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/transformer/ToListOfMapsTest.java
  core/src/test/java/nl/nn/adapterframework/jta/StatusRecordingTransactionManagerImplementationTest.java
  core/src/test/java/nl/nn/adapterframework/jta/btm/BtmConnectionFactoryFactoryTest.java
  core/src/test/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactoryTest.java
  core/src/test/java/nl/nn/adapterframework/ldap/LdapSenderTest.java
  core/src/test/java/nl/nn/adapterframework/lifecycle/ServletManagerTest.java
  core/src/test/java/nl/nn/adapterframework/management/bus/BusTestBase.java
  core/src/test/java/nl/nn/adapterframework/senders/MailSender2Test.java
  core/src/test/java/nl/nn/adapterframework/util/FilenameUtilsTest.java
  core/src/test/java/nl/nn/adapterframework/util/flow/graphviz/FormatTest.java
  test-integration/src/test/java/nl/nn/adapterframework/filesystem/BasicFileSystemTestBase.java
  test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeMailListenerTestBase.java
Labels: Technical Debt

#5362 Do not close any session keys in sub-adapter that are also in calling adapter
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisJavaSender.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionTest.java
  core/src/test/java/nl/nn/adapterframework/senders/IbisLocalSenderTest.java
Labels: Bug

#5357 Fix for Session Key close unexpectedly (7.8) (#5287)
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapter.java
  core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisJavaSender.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/util/Misc.java
  core/src/main/java/nl/nn/adapterframework/util/StreamUtil.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionBaseTest.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionTest.java
  core/src/test/java/nl/nn/adapterframework/http/cxf/SoapProviderStub.java
  core/src/test/java/nl/nn/adapterframework/http/cxf/SoapProviderTest.java
  core/src/test/java/nl/nn/adapterframework/monitoring/MessageCapturingEchoSender.java
  core/src/test/java/nl/nn/adapterframework/monitoring/MonitorTest.java
  core/src/test/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapterTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/PipeTestBase.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
  core/src/test/java/nl/nn/adapterframework/util/MiscTest.java
Labels: Bug, Backport

#5374 Bump Ladybug from 2.3-20230608.115735 to 2.3-20230911.183804
  ladybug/pom.xml
  ladybug/src/main/java/nl/nn/ibistesttool/transform/HideRegexMessageTransformer.java
Labels: Backport

#5363 Add more and consistent debug logging on JMS Received/sent messages
  core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsListenerBase.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsSender.java
  ibm/src/main/java/nl/nn/adapterframework/extensions/ibm/IMSSender.java
  ibm/src/main/java/nl/nn/adapterframework/extensions/ibm/MQSender.java
  ibm/src/test/java/nl/nn/adapterframework/extensions/ibm/IMSSenderTest.java
  ibm/src/test/java/nl/nn/adapterframework/extensions/ibm/TestJMSMessage.java
Labels: Feature

#5386 Move and upgrade hamcrest-all (from 2012) to hamcrest (2019) library
  aws/pom.xml
  cmis/pom.xml
  console/backend/pom.xml
  core/pom.xml
  ibm/pom.xml
  management-gateway/pom.xml
  pom.xml
  test-integration/pom.xml
Labels: Dependencies

#5389 Fix Locker numRetries not working
  core/src/main/java/nl/nn/adapterframework/util/Locker.java
Labels: Backport

#5431 Reduce CI JavaDoc logging
  pom.xml
Labels: Backport

#5435 Remove Memory footprint log warnings
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
Labels: Backport

#5458 Fix exception caused by unset log config property
  core/src/main/resources/log4j4ibis.properties
  core/src/main/resources/log4j4ibis.xml
Labels: Bug, Backport

#5457 Fix exception caused by unset log config property
  core/src/main/resources/log4j4ibis.properties
  core/src/main/resources/log4j4ibis.xml
Labels: Bug

#5445 Components to typescript 2
  console/frontend/src/main/frontend/.vscode/settings.json
  console/frontend/src/main/frontend/src/angularjs/app/app.service.ts
  console/frontend/src/main/frontend/src/angularjs/app/views/environment-variables/environment-variables.component.js
  console/frontend/src/main/frontend/src/angularjs/app/views/environment-variables/environment-variables.component.ts
  console/frontend/src/main/frontend/src/angularjs/app/views/ibisstore-summary/ibisstore-summary.component.js
  console/frontend/src/main/frontend/src/angularjs/app/views/ibisstore-summary/ibisstore-summary.component.ts
  console/frontend/src/main/frontend/src/angularjs/app/views/inlinestore/inlinestore.component.ts
  console/frontend/src/main/frontend/src/angularjs/app/views/jms/jms-browse-queue/jms-browse-queue.component.js
  console/frontend/src/main/frontend/src/angularjs/app/views/jms/jms-browse-queue/jms-browse-queue.component.ts
  console/frontend/src/main/frontend/src/angularjs/app/views/jms/jms-send-message/jms-send-message.component.js
  console/frontend/src/main/frontend/src/angularjs/app/views/jms/jms-send-message/jms-send-message.component.ts
  console/frontend/src/main/frontend/src/angularjs/app/views/liquibase/liquibase.component.js
  console/frontend/src/main/frontend/src/angularjs/app/views/liquibase/liquibase.component.ts
  console/frontend/src/main/frontend/src/angularjs/app/views/security-items/security-items.component.js
  console/frontend/src/main/frontend/src/angularjs/app/views/security-items/security-items.component.ts
  console/frontend/src/main/frontend/src/angularjs/components.ts
  console/frontend/src/main/frontend/src/app/app.module.ts
  console/frontend/src/main/frontend/src/app/pipes/orderby.pipe.ts
  console/frontend/src/main/frontend/src/app/pipes/variablesFilter.pipe.ts
  console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.html
  console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.scss
  console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.spec.ts
  console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.ts
  console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.html
  console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-custom-view/iframe-custom-view.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug-beta/iframe-ladybug-beta.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug/iframe-ladybug.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-larva/iframe-larva.component.ts
  console/frontend/src/main/frontend/src/app/views/inlinestore/inlinestore.component.html
  console/frontend/src/main/frontend/src/app/views/inlinestore/inlinestore.component.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/quick-submit-form.directive.spec.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/quick-submit-form.directive.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-browse-queue/jms-browse-queue.component.html
  console/frontend/src/main/frontend/src/app/views/jms/jms-browse-queue/jms-browse-queue.component.scss
  console/frontend/src/main/frontend/src/app/views/jms/jms-browse-queue/jms-browse-queue.component.spec.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-browse-queue/jms-browse-queue.component.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.scss
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.spec.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts
  console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.html
  console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.scss
  console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.spec.ts
  console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.ts
Labels: Frank Console
