Repository frankframework/frankframework, pull requests merged in 2023-05, with the labels that each got.

#4835 Bump Ladybug from 2.3-20230330.120035 to 2.3-20230428.135435
  ladybug/pom.xml
Labels: Backport

#4840 Fix Samba2 authentication to use CredentialProvider (#4831)
  core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java
Labels: Bug, Backport

#4857 Fix for Ladybug Report not being closed with IbisLocalSender "Isolated" option
  core/src/main/java/nl/nn/adapterframework/core/RequestReplyExecutor.java
  core/src/main/java/nl/nn/adapterframework/pipes/IsolatedServiceExecutor.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
  core/src/main/java/nl/nn/adapterframework/stream/StreamingPipe.java
  core/src/main/java/nl/nn/adapterframework/stream/ThreadConnector.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemPipeTest.java
  ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
  test/src/main/configurations/MainConfig/ConfigurationCompareStringPipe.xml
Labels: Bug

#4882 Backport of improvements to temporary file handling
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/AsposeFontManager.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipe.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/RepositoryConnectorFactory.java
  core/src/main/java/nl/nn/adapterframework/extensions/esb/WsdlGeneratorPipe.java
  core/src/main/java/nl/nn/adapterframework/extensions/javascript/J2V8.java
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java
  core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
  core/src/main/java/nl/nn/adapterframework/util/FileHandler.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  core/src/test/java/nl/nn/adapterframework/pipes/CompressPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/UnzipPipeTest.java
  core/src/test/java/nl/nn/adapterframework/util/FileUtilsTest.java
  larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
Labels: Technical Debt, Backport

#4859 JavaListener memory usage reduction
  core/src/main/java/nl/nn/adapterframework/http/cxf/NamespaceUriProvider.java
  core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/receivers/ServiceClient.java
  core/src/main/java/nl/nn/adapterframework/receivers/ServiceDispatcher.java
  core/src/main/java/nl/nn/adapterframework/receivers/ServiceDispatcherBean.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisJavaSender.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
  core/src/main/java/nl/nn/adapterframework/senders/IsolatedServiceCaller.java
  core/src/main/java/nl/nn/adapterframework/senders/IsolatedServiceExecutor.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/TestServiceListener.java
  core/src/main/resources/SpringApplicationContext.xml
  core/src/test/java/nl/nn/adapterframework/receivers/JavaListenerTest.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
  core/src/test/java/nl/nn/adapterframework/receivers/ServiceDispatcherTest.java
  core/src/test/java/nl/nn/adapterframework/senders/IbisJavaSenderTest.java
  core/src/test/java/nl/nn/adapterframework/senders/IbisLocalSenderTest.java
Labels: Bug

#4886 Preserve large messages to disk
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/AsposeFontManager.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java
  core/src/main/java/nl/nn/adapterframework/stream/FileMessage.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java
  core/src/main/java/nl/nn/adapterframework/stream/PathMessage.java
  core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java
  core/src/main/java/nl/nn/adapterframework/util/AppConstants.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  core/src/main/java/nl/nn/adapterframework/util/Misc.java
  core/src/main/java/nl/nn/adapterframework/util/StreamUtil.java
  core/src/main/resources/AppConstants.properties
  core/src/test/java/nl/nn/adapterframework/stream/FileMessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/SerializableFileReferenceTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/SerializationTester.java
Labels: Performance, Frank Framework, Technical Debt

#4897 Preserve large messages to disk (#4759)
  core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java
  core/src/main/java/nl/nn/adapterframework/stream/FileMessage.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java
  core/src/main/java/nl/nn/adapterframework/stream/PathMessage.java
  core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java
  core/src/main/java/nl/nn/adapterframework/util/AppConstants.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  core/src/main/java/nl/nn/adapterframework/util/StreamUtil.java
  core/src/main/resources/AppConstants.properties
  core/src/test/java/nl/nn/adapterframework/stream/FileMessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/SerializableFileReferenceTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/SerializationTester.java
  iaf-commons/src/main/java/nl/nn/adapterframework/util/StreamUtil.java
Labels: Feature

#4896 Fix possible stream leak detected by tests in master
  core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java
  core/src/test/java/nl/nn/adapterframework/stream/SerializableFileReferenceTest.java
Labels: Bug, Backport
