Repository frankframework/frankframework, pull requests merged in 2023-10, with the labels that each got.

#5475 Fix JMS Session Closed issue
  core/src/main/java/nl/nn/adapterframework/core/IListenerConnector.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionTest.java
Labels: Bug, Backport

#5486 Use Maven Central repository first
  pom.xml
Labels: CI

#5498 Fix JMS Session Closed issue (#5481)
  core/src/main/java/nl/nn/adapterframework/core/IListenerConnector.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionTest.java
Labels: Bug

#5471 Lcm/minor cleanups
  core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsListener.java
  core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java
  core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
  core/src/main/java/nl/nn/adapterframework/processors/CorePipeLineProcessor.java
  core/src/main/java/nl/nn/adapterframework/processors/InputOutputPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/processors/MonitoringPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/soap/SoapValidator.java
  core/src/main/java/nl/nn/adapterframework/soap/SoapWrapper.java
  core/src/main/java/nl/nn/adapterframework/util/TransformerPool.java
Labels: Technical Debt

#5514 Backport Maven improvements
  aspose/pom.xml
  idin/pom.xml
  pom.xml
Labels: Backport

#5508 Fix default-values in log configuration properties
  core/src/main/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactory.java
  core/src/test/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactoryTest.java
Labels: Bug

#5518 Ensure the original message wont be closed when using an IbisLocalSender
  core/src/main/java/nl/nn/adapterframework/receivers/JavaListener.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
  test/src/main/configurations/MainConfig/ConfigurationReturnedSessionKeys.xml
  test/src/test/testtool/ReturnedSessionKeys/scenario05.properties
  test/src/test/testtool/ReturnedSessionKeys/scenario05/out.xml
Labels: Bug, Backport

#5509 Fix default values in log configuration
  core/src/main/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactory.java
  core/src/test/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipeTest.java
  core/src/test/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactoryTest.java
  core/src/test/resources/DeploymentSpecifics.properties
Labels: Bug, Backport

#5580 Fix CXF duplicate endpoints errors
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/CompatibilityShowScheduler.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/DeprecationFilter.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowScheduler.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSchedulerBase.java
  core/src/test/java/nl/nn/adapterframework/webcontrol/api/TestDeprecationFilter.java
Labels: Backport

#5533 Add warning when XSDs will be merged to facilitate debugging
  core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java
  core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
  core/src/main/java/nl/nn/adapterframework/soap/WsdlGenerator.java
  core/src/main/java/nl/nn/adapterframework/validation/IXSD.java
  core/src/main/java/nl/nn/adapterframework/validation/JavaxXmlValidator.java
  core/src/main/java/nl/nn/adapterframework/validation/SchemaUtils.java
  core/src/main/java/nl/nn/adapterframework/validation/XSD.java
  core/src/main/java/nl/nn/adapterframework/validation/XercesValidationErrorHandler.java
  core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java
  core/src/test/java/nl/nn/adapterframework/pipes/WsdlXmlValidatorTest.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
  core/src/test/resources/Validation/WsdlValidatorMultipleImportFromDifferentRoots/A.xsd
  core/src/test/resources/Validation/WsdlValidatorMultipleImportFromDifferentRoots/B.xsd
  core/src/test/resources/Validation/WsdlValidatorMultipleImportFromDifferentRoots/root-import-not-ok.wsdl
  core/src/test/resources/Validation/WsdlValidatorMultipleImportFromDifferentRoots/root-import-ok.wsdl
  core/src/test/resources/Validation/WsdlValidatorMultipleImportFromDifferentRoots/soapInput.xml
  core/src/test/resources/Validation/WsdlValidatorMultipleImportFromDifferentRoots/xml.xsd
Labels: Bug

#5551 #5444 support for JMS BytesMessage
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsListener.java
  core/src/main/java/nl/nn/adapterframework/jms/BytesMessageInputStream.java
  core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsListener.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsListenerBase.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsMessagingSource.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsMessagingSourceFactory.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsSender.java
  core/src/main/java/nl/nn/adapterframework/jms/MessagingSource.java
  core/src/main/java/nl/nn/adapterframework/jms/MessagingSourceFactory.java
  core/src/main/java/nl/nn/adapterframework/jms/PullingJmsListener.java
  core/src/main/java/nl/nn/adapterframework/jms/PushingJmsListener.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/SendJmsMessage.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/stream/SerializableFileReference.java
  core/src/main/resources/AppConstants.properties
  core/src/test/java/nl/nn/adapterframework/jms/JMSFacadeTest.java
  core/src/test/java/nl/nn/adapterframework/jms/JmsSenderTest.java
  core/src/test/java/nl/nn/adapterframework/management/bus/BusTestBase.java
  core/src/test/java/nl/nn/adapterframework/management/bus/endpoints/TestBrowseQueue.java
  core/src/test/java/nl/nn/adapterframework/management/bus/endpoints/TestSendJmsMessage.java
  core/src/test/java/nl/nn/adapterframework/testutil/mock/MockRunnerConnectionFactoryFactory.java
  core/src/test/resources/AppConstants.properties
  core/src/test/resources/testBusApplicationContext.xml
  iaf-commons/src/main/java/nl/nn/adapterframework/functional/FunctionalUtil.java
  iaf-commons/src/main/java/nl/nn/adapterframework/util/PropertyLoader.java
  ibm/src/main/java/nl/nn/adapterframework/extensions/ibm/IMSSender.java
  ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/IfsaMessagingSourceFactory.java
  test/src/main/configurations/JMS/BinaryData/test-data.zip
  test/src/main/configurations/JMS/Configuration.xml
  test/src/main/configurations/JMS/ConfigurationJmsBytesMessage.xml
  test/src/test/testtool/JmsBytesMessage/common.properties
  test/src/test/testtool/JmsBytesMessage/scenario01.properties
  test/src/test/testtool/JmsBytesMessage/scenario01/test-output.txt
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/TibcoMessagingSourceFactory.java
Labels: Feature

#5618 Fix "replyTo" and "bounceAddress" options not working in MailSender
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/senders/MailSender.java
  core/src/main/java/nl/nn/adapterframework/senders/MailSenderBase.java
  core/src/main/java/nl/nn/adapterframework/senders/SendGridSender.java
  core/src/main/java/nl/nn/adapterframework/util/Misc.java
  core/src/test/java/nl/nn/adapterframework/senders/MailSender2Test.java
  core/src/test/java/nl/nn/adapterframework/senders/mail/MailSenderTestBase.java
  core/src/test/resources/Senders/MailSender/mailWithAttachment.txt
  core/src/test/resources/Senders/MailSender/mailWithBase64Attachment.txt
  core/src/test/resources/Senders/MailSender/mailWithBase64Message.txt
  core/src/test/resources/Senders/MailSender/mailWithBase64MessageAndAttachment.txt
  core/src/test/resources/Senders/MailSender/mailWithBase64MessageAndAttachmentWithContentType.txt
  core/src/test/resources/Senders/MailSender/mailWithMultipleRecipients.txt
  core/src/test/resources/Senders/MailSender/mailWithNDR.txt
  core/src/test/resources/Senders/MailSender/mailWithPRC.txt
  core/src/test/resources/Senders/MailSender/mailWithPRCAttachmentsFromSession.txt
  core/src/test/resources/Senders/MailSender/mailWithRPCAttachments.txt
Labels: Backport
