Repository frankframework/frankframework, pull requests merged in 2023-12, with the labels that each got.

#5904 Move remainder of extensions-esb to NN Specials
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/core/DestinationValidator.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
  core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
  core/src/main/java/nl/nn/adapterframework/soap/WsdlGenerator.java
  core/src/main/java/nl/nn/adapterframework/soap/WsdlGeneratorExtension.java
  core/src/main/java/nl/nn/adapterframework/soap/WsdlGeneratorExtensionContext.java
  nn-specials/pom.xml
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsListener.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsSender.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapValidator.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWrapperPipe.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWsdlGeneratorContext.java
  pom.xml
  test/pom.xml
Labels: Technical Debt

#5926 Updated date-parser
  commons/src/main/java/nl/nn/adapterframework/util/CalendarParser.java
  commons/src/main/java/nl/nn/adapterframework/util/CalendarParserException.java
  commons/src/main/java/nl/nn/adapterframework/util/DateFormatUtils.java
  commons/src/test/java/nl/nn/adapterframework/util/DateFormatUtilsTest.java
  core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
  core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java
Labels: Technical Debt

#5747 Add Experimental Kafka Support
  messaging/pom.xml
  messaging/src/main/java/nl/nn/adapterframework/extensions/kafka/KafkaFacade.java
  messaging/src/main/java/nl/nn/adapterframework/extensions/kafka/KafkaListener.java
  messaging/src/main/java/nl/nn/adapterframework/extensions/kafka/KafkaSender.java
  messaging/src/main/java/nl/nn/adapterframework/extensions/mqtt/MqttFacade.java
  messaging/src/main/java/nl/nn/adapterframework/extensions/mqtt/MqttListener.java
  messaging/src/main/java/nl/nn/adapterframework/extensions/mqtt/MqttSender.java
  messaging/src/test/java/nl/nn/adapterframework/extensions/kafka/KafkaFacadeTest.java
  messaging/src/test/java/nl/nn/adapterframework/extensions/kafka/KafkaPatternValidatorTest.java
  messaging/src/test/java/nl/nn/adapterframework/extensions/kafka/KafkaReceiverTest.java
  messaging/src/test/java/nl/nn/adapterframework/extensions/kafka/KafkaSenderTest.java
Labels: Feature

#5945 Remove log warnings when unable to parse mimetype parameters
  core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java
  core/src/test/java/nl/nn/adapterframework/http/PartMessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageContextTest.java
Labels: Bug, Backport, 7.8

#5944 Remove log warnings when unable to parse mimetype parameters
  core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java
  core/src/test/java/nl/nn/adapterframework/http/PartMessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageContextTest.java
Labels: Bug, Backport, 7.9

#5956 Actually implement type=file attribute when using multipartXml
  core/src/main/java/nl/nn/adapterframework/http/HttpSender.java
  core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXml.txt
  core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXmlNoPartName.txt
  core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXml.txt
  core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXmlNoPartName.txt
Labels: Bug, Backport, 7.8

#5955 Actually implement type=file attribute when using multipartXml
  core/src/main/java/nl/nn/adapterframework/http/HttpSender.java
  core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXml.txt
  core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXmlNoPartName.txt
  core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXml.txt
  core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXmlNoPartName.txt
Labels: Bug, Backport, 7.9

#5927 Cleanup deprecated methods (part 1)
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipe.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java
  cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/TestGetAction.java
  core/src/main/java/nl/nn/adapterframework/http/HttpSender.java
  core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/nl/nn/adapterframework/ldap/LdapQueryPipeBase.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/BrowseQueue.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/SendJmsMessage.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/ServerStatistics.java
  core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
  core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/GenericMessageSendingPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/XmlSwitch.java
  core/src/main/java/nl/nn/adapterframework/pipes/XsltPipe.java
  core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java
  core/src/main/java/nl/nn/adapterframework/senders/JsonXsltSender.java
  core/src/main/java/nl/nn/adapterframework/senders/SambaSenderOld.java
  core/src/main/java/nl/nn/adapterframework/senders/SendGridSender.java
  core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java
  core/src/main/java/nl/nn/adapterframework/soap/SoapWrapperPipe.java
  core/src/main/java/nl/nn/adapterframework/util/DB2DocumentWriter.java
  core/src/main/java/nl/nn/adapterframework/util/DB2XMLWriter.java
  core/src/main/java/nl/nn/adapterframework/util/FileHandler.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  core/src/main/java/nl/nn/adapterframework/util/TransformerPool.java
  core/src/main/resources/META-INF/resources/iaf/jsp/debuginfo.jsp
  core/src/main/resources/xml/xsl/adapter2dot.xsl
  core/src/main/resources/xml/xsl/pipeTypes.xml
  core/src/main/resources/xml/xsl/stub4testtool.xsl
  core/src/main/resources/xml/xsl/uglify_lookup.xml
  core/src/test/java/nl/nn/adapterframework/configuration/Stub4TesttoolTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/nl/nn/adapterframework/util/FileUtilsTest.java
  core/src/test/java/nl/nn/adapterframework/xslt/ParallelXsltTest.java
  core/src/test/java/nl/nn/adapterframework/xslt/Xslt3Test.java
  core/src/test/java/nl/nn/adapterframework/xslt/XsltErrorTestBase.java
  core/src/test/java/nl/nn/adapterframework/xslt/XsltPipeTest.java
  core/src/test/java/nl/nn/adapterframework/xslt/XsltSenderTest.java
  core/src/test/java/nl/nn/adapterframework/xslt/XsltTestBase.java
  core/src/test/resources/ConfigurationUtils/stub4testtool/GenericMessageSendingPipe/expected.xml
  core/src/test/resources/ConfigurationUtils/stub4testtool/GenericMessageSendingPipe/original.xml
  core/src/test/resources/Digester/Original/SimpleConfiguration.xml
  core/src/test/resources/test1.xml
  ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/IfsaRequesterSender.java
  larva/src/main/java/nl/nn/adapterframework/testtool/XsltProviderListener.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/bis/BisWrapperPipe.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsSender.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/svn/ScanTibcoSolutionPipe.java
  test/src/main/configurations/HTTP/ConfigurationRestListener.xml
Labels: Technical Debt

#5958 Remove default values from Larva test configurations
  core/src/main/java/nl/nn/adapterframework/compression/ZipWriterPipe.java
  core/src/main/java/nl/nn/adapterframework/compression/ZipWriterSender.java
  test/src/main/configurations/HTTP/ConfigurationApiListener.xml
  test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAddress.xml
  test/src/main/configurations/JDBC/ConfigurationJdbcListener.xml
  test/src/main/configurations/JDBC/ConfigurationManageDatabaseWrapper.xml
  test/src/main/configurations/MainConfig/ConfigurationCompactMessage.xml
  test/src/main/configurations/MainConfig/ConfigurationXsltPipe.xml
  test/src/main/configurations/MainConfig/ConfigurationZip.xml
Labels: Technical Debt, Backport, 7.9

#5960 JmsSender should use property jms.messageClass.default if messageClass not set
  core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsSender.java
  core/src/test/java/nl/nn/adapterframework/jms/JmsSenderTest.java
  core/src/test/resources/AppConstants.properties
Labels: 7.9

#5959 Fix rollBackOnly on pipes and delegate exceptions to ExceptionHandlingProcessor
  console/war/src/main/resources/application.properties
  core/src/main/java/nl/nn/adapterframework/core/IbisTransaction.java
  core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
  core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/processors/TransactionAttributePipeProcessor.java
  test/src/main/configurations/TX/Configuration.xml
  test/src/main/configurations/TX/TransactionFailureInDbPipe.xml
  test/src/main/configurations/TX/TransactionFailureInNonDbPipe.xml
  test/src/main/configurations/TX/TransactionFailureInNotSupportedDbPipe.xml
  test/src/test/testtool/ClobAndBlob/common.properties
  test/src/test/testtool/ClobAndBlob/scenario07/out.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario09/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario11/md-select-result.xml
  test/src/test/testtool/Senders/scenario01.properties
  test/src/test/testtool/Senders/scenario01/out.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01.properties
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01/in.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01/jdbc-delete.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01/md-result.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01/md-select.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01/out.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02.properties
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02/in.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02/jdbc-delete.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02/md-result.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02/md-select.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02/out.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario03.properties
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario03/in.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario03/jdbc-delete.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario03/md-result.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario03/md-select.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario03/out.xml
  test/src/test/testtool/TransactionHandling/scenario08.properties
  test/src/test/testtool/TransactionHandling/scenario08/out.txt
  test/src/test/testtool/TransactionHandling/scenario08/out.xml
Labels: Backport, 7.9

#5980 Run unreliable test only locally
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
Labels: 7.9

#5968 Clean some code
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  core/src/main/java/nl/nn/adapterframework/core/BytesResource.java
  core/src/main/java/nl/nn/adapterframework/core/HasPhysicalDestination.java
  core/src/main/java/nl/nn/adapterframework/core/HasSender.java
  core/src/main/java/nl/nn/adapterframework/core/HasTransactionAttribute.java
  core/src/main/java/nl/nn/adapterframework/core/IAdapter.java
  core/src/main/java/nl/nn/adapterframework/core/IBlockEnabledSender.java
  core/src/main/java/nl/nn/adapterframework/core/IConfigurable.java
  core/src/main/java/nl/nn/adapterframework/core/IConfigurationAware.java
  core/src/main/java/nl/nn/adapterframework/core/IDataIterator.java
  core/src/main/java/nl/nn/adapterframework/core/IDualModeValidator.java
  core/src/main/java/nl/nn/adapterframework/core/IErrorMessageFormatter.java
  core/src/main/java/nl/nn/adapterframework/core/IExtendedPipe.java
  core/src/main/java/nl/nn/adapterframework/core/IForwardTarget.java
  core/src/main/java/nl/nn/adapterframework/core/IListenerConnector.java
  core/src/main/java/nl/nn/adapterframework/core/IMessageBrowser.java
  core/src/main/java/nl/nn/adapterframework/core/IMessageHandler.java
  core/src/main/java/nl/nn/adapterframework/core/IPeekableListener.java
  core/src/main/java/nl/nn/adapterframework/core/IPipeLineExitHandler.java
  core/src/main/java/nl/nn/adapterframework/core/IPortConnectedListener.java
  core/src/main/java/nl/nn/adapterframework/core/IProvidesMessageBrowsers.java
  core/src/main/java/nl/nn/adapterframework/core/IScopeProvider.java
  core/src/main/java/nl/nn/adapterframework/core/ISecurityHandler.java
  core/src/main/java/nl/nn/adapterframework/core/ISender.java
  core/src/main/java/nl/nn/adapterframework/core/IThreadCountControllable.java
  core/src/main/java/nl/nn/adapterframework/core/ITransactionalStorage.java
  core/src/main/java/nl/nn/adapterframework/core/IValidator.java
  core/src/main/java/nl/nn/adapterframework/core/IWithParameters.java
  core/src/main/java/nl/nn/adapterframework/core/IWrapperPipe.java
  core/src/main/java/nl/nn/adapterframework/core/IXAEnabled.java
  core/src/main/java/nl/nn/adapterframework/core/IXmlValidator.java
  core/src/main/java/nl/nn/adapterframework/core/PipeForwards.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLine.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLineExits.java
  core/src/main/java/nl/nn/adapterframework/core/ProcessState.java
  core/src/main/java/nl/nn/adapterframework/core/SharedResource.java
  core/src/main/java/nl/nn/adapterframework/core/TransactionAttribute.java
  docker/Tomcat/webapp/Dockerfile
Labels: Technical Debt

#5983 Update smb documentation and setters
  core/src/main/java/nl/nn/adapterframework/filesystem/Samba1FileSystem.java
  core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java
  core/src/main/java/nl/nn/adapterframework/pipes/Samba1Pipe.java
  core/src/main/java/nl/nn/adapterframework/senders/Samba1Sender.java
  core/src/test/java/nl/nn/adapterframework/filesystem/smb/Samba1FileSystemTest.java
Labels: 7.9, Documentation

#5988 Issue 7.8 - Do NOT close session twice
  core/src/main/java/nl/nn/adapterframework/compression/ZipWriter.java
  core/src/main/java/nl/nn/adapterframework/compression/ZipWriterPipe.java
  core/src/main/java/nl/nn/adapterframework/util/FileHandler.java
  core/src/main/java/nl/nn/adapterframework/util/Misc.java
  test/src/main/configurations/HTTP/ConfigurationWebServiceListenerSenderAddress.xml
  test/src/main/configurations/MainConfig/ConfigurationZip.xml
  test/src/test/testtool/Zip/ZipWriter/output-3.xml
  test/src/test/testtool/Zip/ZipWriter/scenario03.properties
Labels: 7.8

#5978 Error setting CLOB parameter for stored procedure
  core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySender.java
  core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
  core/src/test/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySenderTest.java
Labels: Bug, 7.9

#5995 Fix error setting CLOB parameter for stored procedure (#5978)
  core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySender.java
  core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
  core/src/test/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySenderTest.java
Labels: Bug

#6001 Remove old deprecation warning on Javascript Engines. Use StringBuilder where possible.
  core/src/main/java/nl/nn/adapterframework/senders/JavascriptSender.java
  core/src/main/java/nl/nn/adapterframework/util/flow/graphviz/Format.java
  core/src/test/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySenderTest.java
  larva/src/main/java/nl/nn/adapterframework/testtool/FileListener.java
  larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
Labels: Technical Debt

#6035 fix configuration file upload
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-upload/configurations-upload.component.html
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-upload/configurations-upload.component.ts
Labels: Frank Console

#6036 fix configuration file upload
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-upload/configurations-upload.component.html
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-upload/configurations-upload.component.ts
Labels: Frank Console

#6031 7.9 backport console adapter record keys are now changed for namespace instead of adaptername
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add/scheduler-add.component.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-edit/scheduler-edit.component.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.service.ts
  console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
Labels: Frank Console

#6026 Console adapter record keys are now changed for namespace instead of adaptername
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add/scheduler-add.component.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-edit/scheduler-edit.component.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.service.ts
  console/frontend/src/main/frontend/src/app/views/security-items/security-items.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
Labels: Frank Console

#6051 fix sidebar so the routes in a category stays open correctly
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts
Labels: Frank Console

#6038 fix error status checks in error page
  console/frontend/src/main/frontend/src/app/views/error/error.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
Labels: Frank Console

#6052 Backport 7.9 fix error page
  console/frontend/src/main/frontend/src/app/views/error/error.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
Labels: Frank Console

#6053 Backport 7.9 fix sidebar categories expand collapse
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts
Labels: Frank Console
