Repository frankframework/frankframework, pull requests merged in 2023-08, with the labels that each got.

#5177 Add more JDBC and JMS pooling
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/jms/JmsMessagingSource.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsMessagingSourceFactory.java
  core/src/main/java/nl/nn/adapterframework/jms/MessagingSource.java
  core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactory.java
  core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaConnectionFactoryFactory.java
  core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSource.java
  core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactory.java
  core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java
  core/src/main/resources/AppConstants.properties
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
  core/src/test/java/nl/nn/adapterframework/testutil/NarayanaXADataSourceFactory.java
Labels: Bug, Backport

#5176 MariaDB support using MariaDB native driver instead of MySQL
  docker/appserver/JBoss/src/configuration/standalone.xml
  docker/appserver/WebSphere/src/scripts/configureJdbc.py
  docker/appserver/WildFly/src/configuration/standalone.xml
  test/src/main/webapp/META-INF/context.xml
Labels: Bug, Backport

#5174 MariaDB support using MariaDB native driver instead of MySQL
  docker/JBoss/src/configuration/standalone.xml
  docker/WebSphere/src/configuration/02-configureJdbc.py
  docker/WildFly/src/configuration/standalone.xml
  test/src/main/webapp/META-INF/context.xml
Labels: Bug

#5182 Fix JDBC/JTA unit tests not running on MS-SQL
  core/pom.xml
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
  core/src/test/java/nl/nn/adapterframework/testutil/URLDataSourceFactory.java
Labels: Backport

#5148 Add StoredProcedureQuerySender
  core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/QueryExecutionContext.java
  core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureResultWrapper.java
  core/src/main/java/nl/nn/adapterframework/jdbc/XmlQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/Db2DbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/Dbms.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/GenericDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/H2DbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/IDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/MsSqlServerDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/MySqlDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/OracleDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/PostgresqlDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/util/DB2XMLWriter.java
  core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
  core/src/main/resources/SqlTranslationPatterns.properties
  core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd
  core/src/main/resources/xml/xsd/FrankConfig.xsd
  core/src/test/java/nl/nn/adapterframework/jdbc/H2TestProcedures.java
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
  core/src/test/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySenderTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/URLDataSourceFactory.java
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/multi-output-parameter-xml-result.xml
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/multi-row-results.xml
  test/src/main/configurations/JDBC/Configuration.xml
  test/src/main/configurations/JDBC/ConfigurationJdbcSenders.xml
  test/src/main/configurations/JDBC/ConfigurationStoredProcedureSender.xml
  test/src/main/resources/DatabaseChangelog.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/main/webapp/META-INF/context.xml
  test/src/test/testtool/JdbcSenders/common.properties
  test/src/test/testtool/JdbcSenders/scenario06.properties
  test/src/test/testtool/JdbcSenders/scenario06/out.txt
Labels: Feature

#5218 XA DataSource creation fix
  core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSource.java
  core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactory.java
  core/src/test/java/nl/nn/adapterframework/jdbc/FixedQuerySenderTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
  core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTestBase.java
  core/src/test/java/nl/nn/adapterframework/jdbc/migration/MigratorTest.java
  core/src/test/java/nl/nn/adapterframework/jta/StatusRecordingTransactionManagerTest.java
  core/src/test/java/nl/nn/adapterframework/jta/TransactionConnectorTest.java
  core/src/test/java/nl/nn/adapterframework/jta/btm/TestSelfRecoveringBTMDiskJournal.java
  core/src/test/java/nl/nn/adapterframework/testutil/BTMXADataSourceFactory.java
  core/src/test/java/nl/nn/adapterframework/testutil/NarayanaXADataSourceFactory.java
  core/src/test/java/nl/nn/adapterframework/testutil/TransactionManagerType.java
  core/src/test/java/nl/nn/adapterframework/testutil/URLXADataSourceFactory.java
  core/src/test/java/nl/nn/adapterframework/util/LockerTest.java
  core/src/test/java/nl/nn/adapterframework/util/MessageBrowsingFilterTest.java
  core/src/test/resources/AppConstants.properties
  pom.xml
Labels: Bug, Backport

#5224 Support StoredProcedure OUT parameters for Oracle
  .run/IAF-Example.run.xml
  core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureResultWrapper.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/IDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/OracleDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
  core/src/main/java/nl/nn/adapterframework/util/DB2XMLWriter.java
  core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
  core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd
  core/src/main/resources/xml/xsd/FrankConfig.xsd
  core/src/test/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySenderTest.java
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/multi-output-parameter-type-conversions-test-xml-result.xml
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/multi-output-parameter-xml-result.xml
  test/src/main/configurations/JDBC/ConfigurationStoredProcedureSender.xml
  test/src/main/resources/DatabaseChangelog.xml
  test/src/test/testtool/JdbcSenders/scenario06.properties
Labels: Feature

#5243 Backport StorageClass attribute to 7.8 release
  core/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java
  core/src/main/java/nl/nn/adapterframework/senders/AmazonS3Sender.java
Labels: Backport

#5259 Fix and add more logging to MessageUtils
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/scheduler/job/LoadDatabaseSchedulesJob.java
  core/src/main/java/nl/nn/adapterframework/util/MessageDataSource.java
  core/src/main/java/nl/nn/adapterframework/util/MessageUtils.java
Labels: Backport

#5306 Miscellaneous minor code cleanups
  core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/processors/InputOutputPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/senders/IbisLocalSender.java
  core/src/test/java/nl/nn/adapterframework/processors/InputOutputPipeProcessorTest.java
  core/src/test/java/nl/nn/adapterframework/senders/IbisLocalSenderTest.java
  ladybug/src/main/java/nl/nn/ibistesttool/Debugger.java
  ladybug/src/main/java/nl/nn/ibistesttool/PipeLineSessionDebugger.java
Labels: Technical Debt

#5303 Make logger `static final` for some of the most common classes
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/http/PartMessage.java
  core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
  core/src/main/java/nl/nn/adapterframework/parameters/ParameterValue.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java
Labels: Technical Debt

#5307 Preserve message when converting an image (7.8)
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/CellsConvertor.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/Fontsetter.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PdfImageConvertor.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/WordConvertor.java
  aspose/src/test/java/com/testautomationguru/utility/ImageUtil.java
  aspose/src/test/java/com/testautomationguru/utility/PDFUtil.java
  aspose/src/test/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipeTest.java
  aspose/src/test/resources/PdfPipe/imageDiffTest/rbgw.png
  aspose/src/test/resources/PdfPipe/imageDiffTest/rgbw.png
Labels: Backport
