Repository frankframework/frankframework, pull requests merged in 2023-01, with the labels that each got.

#4240 Add warning when char data is encountered when binary is expected to UnzipPipe (7.8)
  core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
Labels: Backport

#4271 Fix receiver ThreadCount check in GUI
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/AdapterStatus.java
  webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
Labels: Bug, Frank Console

#4273 Fix receiver ThreadCount check in GUI (7.8)
  webapp/src/main/webapp/iaf/gui/views/ShowConfigurationStatus.html
Labels: Bug, Frank Console, Backport

#4295 4254 Status 400 not 500 for bad multipart requests
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
Labels: Bug, Frank Framework

#4285 Updated instructions for running in IntelliJ.
  .run/IAF-Example.run.xml
  CONTRIBUTING.md
  TESTING_WITH_IAF-TEST.md
  docker/appserver/Tomcat/pom.xml
  docker/pom.xml
  pom.xml
  test/pom.xml
Labels: Frank Framework

#4274 Abort request when Content-Type does not match consumes
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/http/rest/MediaTypes.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/MediaTypeTest.java
  example/src/test/java/nl/nn/adapterframework/extensions/test/TestIbisTester.java
Labels: Bug, Frank Framework

#4301 Change CacheControl header to only work when no-etag is present
  core/src/main/java/nl/nn/adapterframework/http/CacheControlFilter.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  webapp/src/main/webapp/WEB-INF/web.xml
Labels: Backport

#4302 Fix messageId handling in ApiListenerServlet
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
Labels: Bug, Frank Framework

#4311 Updated instructions for running in IntelliJ (#4285)
  .run/IAF-Example.run.xml
  CONTRIBUTING.md
  TESTING_WITH_IAF-TEST.md
  docker/appserver/Tomcat/pom.xml
  docker/pom.xml
  pom.xml
  test/pom.xml
Labels: Frank Framework, Backport

#4309 Abort request when Content-Type does not match consumes (#4274)
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/http/rest/MediaTypes.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/MediaTypeTest.java
Labels: Bug, Frank Framework, Backport

#4308 Return status 400 (instead of 500) for bad multipart requests (#4295)
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
Labels: Bug, Frank Framework, Backport

#4321 Fix missing message context headers on GET requests
  core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java
  core/src/main/java/nl/nn/adapterframework/util/MessageUtils.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
Labels: Bug, Backport

#4318 Support elementFormDefault="unqualified" (7.8)
  core/src/main/java/nl/nn/adapterframework/validation/JavaxXmlValidator.java
  core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java
  core/src/test/java/nl/nn/adapterframework/pipes/XmlValidatorTest.java
  core/src/test/java/nl/nn/adapterframework/validation/ValidatorTestBase.java
  core/src/test/resources/Validation/ElementFormDefaultUnqualified/ElementFormDefaultUnqualified.xsd
  core/src/test/resources/Validation/ElementFormDefaultUnqualified/input.xml
Labels: Backport

#4336 Make Accept header more robust and validate it's legitimacy
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/http/rest/MediaTypes.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/MediaTypeTest.java
Labels: Technical Debt

#4338 Backport of 'Migrate to new MySql maven project'
  core/pom.xml
  docker/appserver/JBoss/pom.xml
  docker/appserver/Tomcat/pom.xml
  docker/appserver/WebSphere/pom.xml
  docker/appserver/WebSphere/src/scripts/configureJdbc.py
  docker/appserver/WildFly/pom.xml
Labels: Backport

#4341 Fix MongoDB for use with MongoDB Atlas shipwrecks collection
  core/src/main/java/nl/nn/adapterframework/mongodb/StrictJsonDocumentWriter.java
  core/src/main/java/nl/nn/adapterframework/stream/document/ArrayBuilder.java
  core/src/main/java/nl/nn/adapterframework/stream/document/DocumentUtils.java
  core/src/main/java/nl/nn/adapterframework/stream/document/INodeBuilder.java
  core/src/main/java/nl/nn/adapterframework/stream/document/Json2XmlHandler.java
  core/src/main/java/nl/nn/adapterframework/stream/document/JsonNodeBuilder.java
  core/src/main/java/nl/nn/adapterframework/stream/document/ObjectBuilder.java
  core/src/main/java/nl/nn/adapterframework/stream/document/XmlNodeBuilder.java
  core/src/main/java/nl/nn/adapterframework/stream/document/XmlObjectBuilder.java
  core/src/main/java/nl/nn/adapterframework/stream/xml/JsonXslt3XmlHandler.java
  core/src/main/java/nl/nn/adapterframework/util/DB2DocumentWriter.java
  core/src/test/java/nl/nn/adapterframework/stream/document/DocumentBuilderTest.java
  core/src/test/java/nl/nn/adapterframework/stream/document/DocumentUtilsTest.java
  test/src/test/testtool/MongoDbSender/scenario09.properties
  test/src/test/testtool/MongoDbSender/scenario09/in.xml
  test/src/test/testtool/MongoDbSender/scenario09/out.txt
  test/src/test/testtool/MongoDbSender/scenario10.properties
  test/src/test/testtool/MongoDbSender/scenario10/in.xml
  test/src/test/testtool/MongoDbSender/scenario10/out.txt
Labels: Bug

#4323 Suppress deprecation warnings from annotations per adapter
  copyrightExcludeFile.txt
  core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java
  core/src/main/java/nl/nn/adapterframework/configuration/digester/DigesterRuleBase.java
  core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java
  core/src/test/java/nl/nn/adapterframework/configuration/digester/MapPropertyDescriptorsTest.java
  core/src/test/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRuleTest.java
  core/src/test/resources/AppConstants/AppConstants.properties
  core/src/test/resources/AppConstants/AppConstants_ValidateAttributeRuleTest.properties
  core/src/test/resources/TestSuppressDeprecationWarningsConfiguration.xml
  core/src/test/resources/testConfigurationWithDigester.xml
Labels: Bug, Frank Framework

#4357 SQL injections warning not suppressed
  copyrightExcludeFile.txt
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSecurityItems.java
Labels: Bug, Frank Framework

#4362 Ensure that that fieldname in configuration warnings is correct
  .github/workflows/codeql-analysis.yml
  core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java
  core/src/test/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRuleTest.java
Labels: Backport

#4366 Backport 7.8 Fix NPE getting scheduled jobs from inactive configuration (#4363)
  core/src/main/java/nl/nn/adapterframework/configuration/Configuration.java
  core/src/main/java/nl/nn/adapterframework/scheduler/job/CleanupDatabaseJob.java
  core/src/test/java/nl/nn/adapterframework/configuration/ConfigurationTest.java
  core/src/test/java/nl/nn/adapterframework/scheduler/CleanupDatabaseJobTest.java
Labels: Bug, Frank Framework, Backport

#4370 4257 Backport fix for spurious "SQL Injections" warning.
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowSecurityItems.java
Labels: Bug, Frank Framework, Backport

#4382 Fix urlmapping property and OpenApi spec endpoints
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
  webapp/src/main/webapp/iaf/gui/js/controllers.js
  webapp/src/main/webapp/iaf/gui/views/Webservices.html
Labels: Backport

#4389 Fix suppression of default attribute warnings
  core/src/main/java/nl/nn/adapterframework/configuration/digester/DigesterRuleBase.java
  core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java
  core/src/test/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRuleTest.java
Labels: Bug, Frank Framework

#4392 Fix ci wildfly and jboss issue in 7.8 release
  test/pom.xml
Labels: Backport

#4375 Show driver specific ConnectionFactory details under BTM and Narayana (7.8)
  core/src/main/java/nl/nn/adapterframework/jms/MessagingSource.java
Labels: Backport

#4385 Avoid log clutter if JmsSender has no default destinationName (7.8)
  core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java
Labels: Backport

#4393 Backport 7.8 Fix suppression of default attribute warnings (#4389)
  core/src/main/java/nl/nn/adapterframework/configuration/digester/DigesterRuleBase.java
  core/src/main/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRule.java
  core/src/test/java/nl/nn/adapterframework/configuration/digester/ValidateAttributeRuleTest.java
Labels: Bug, Frank Framework, Backport

#4399 Upgrade CXF
  cmis/pom.xml
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/Base.java
  core/src/test/java/nl/nn/adapterframework/webcontrol/api/ApiTestBaseTest.java
  core/src/test/java/nl/nn/adapterframework/webcontrol/api/TestPipelineTest.java
  pom.xml
Labels: Backport

#4376 Issues/4276 timeout guards extra logging (7.7)
  copyrightExcludeFile.txt
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/task/TimeoutGuard.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/PollGuard.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerBase.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerWithPollGuard.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowPullingListener.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowPushingListener.java
Labels: Bug, Frank Framework

#4394 Add debug logging for Exchange handling (7.8)
  core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java
  core/src/main/java/nl/nn/adapterframework/receivers/ExchangeMailListener.java
  core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java
Labels: Bug, Frank Framework

#4418 Add debug logging for Exchange handling
  core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java
  core/src/main/java/nl/nn/adapterframework/receivers/ExchangeMailListener.java
  core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java
Labels: Bug, Frank Framework

#4417 Pollguard / TimeoutGuard extra logging (master)
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/task/TimeoutGuard.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/PollGuard.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerBase.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerWithPollGuard.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowPullingListener.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowPushingListener.java
Labels: Bug, Frank Framework, Backport

#4421 Updated logging for Exchange handling
  core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ExchangeFileSystem.java
Labels: Bug, Frank Framework

#4416 TimeoutGuard extra logging (7.8)
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/task/TimeoutGuard.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/PollGuard.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/SpringJmsConnector.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerBase.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowListenerWithPollGuard.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowPullingListener.java
  core/src/test/java/nl/nn/adapterframework/receivers/SlowPushingListener.java
Labels: Frank Framework, Backport

#4427 Cleanup Frank!Console module
  console/.project
  console/pom.xml
  console/src/main/java/nl/nn/adapterframework/management/web/ApiException.java
  console/src/main/java/nl/nn/adapterframework/management/web/ApiExceptionHandler.java
  console/src/main/java/nl/nn/adapterframework/management/web/Authentication.java
  console/src/main/java/nl/nn/adapterframework/management/web/AuthorizationFilter.java
  console/src/main/java/nl/nn/adapterframework/management/web/BrowseJdbcTable.java
  console/src/main/java/nl/nn/adapterframework/management/web/BrowseQueue.java
  console/src/main/java/nl/nn/adapterframework/management/web/ExceptionHandler.java
  console/src/main/java/nl/nn/adapterframework/management/web/FrankApiBase.java
  console/src/main/java/nl/nn/adapterframework/management/web/Init.java
  console/src/main/java/nl/nn/adapterframework/management/web/SendJmsMessage.java
  console/src/main/java/nl/nn/adapterframework/management/web/ServletDispatcher.java
  console/src/main/java/nl/nn/adapterframework/management/web/ShowConnectionOverview.java
  console/src/main/java/nl/nn/adapterframework/management/web/ShowInlineMessageStoreOverview.java
  console/src/main/java/nl/nn/adapterframework/management/web/ShowLiquibaseScript.java
  console/src/main/java/nl/nn/adapterframework/management/web/ShowLogging.java
  console/src/main/java/nl/nn/adapterframework/management/web/SpringBusExceptionHandler.java
  console/src/main/java/nl/nn/adapterframework/management/web/TestPipeline.java
  console/src/main/java/nl/nn/adapterframework/management/web/TestServiceListener.java
  console/src/main/java/nl/nn/adapterframework/management/web/TransactionalStorage.java
  console/src/main/java/nl/nn/adapterframework/management/web/UpdateLoggingConfig.java
  console/src/main/java/nl/nn/adapterframework/management/web/Webservices.java
  console/src/test/java/nl/nn/adapterframework/management/web/TestTransactionalStorage.java
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/lifecycle/ShowLogDirectory.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  pom.xml
Labels: Technical Debt

#4439 Enable legacy css under IbisOnCloud
  core/src/main/java/nl/nn/adapterframework/webcontrol/FileViewerServlet.java
  core/src/main/resources/xml/xsl/stats_html.xsl
  core/src/main/resources/xml/xsl/web/adapterSite.xsl
  webapp/src/main/webapp/iaf/body.css
  webapp/src/main/webapp/iaf/ie4.css
  webapp/src/main/webapp/iaf/ie55.css
Labels: Backport
