Repository frankframework/frankframework, pull requests merged in 2023-07, with the labels that each got.

#5068 Backport #4854 and #4976
  core/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java
Labels: Backport, FileSystem

#5091 Lcm JDBC code cleanups pt. 3
  core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcListener.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/QueryExecutionContext.java
  core/src/main/java/nl/nn/adapterframework/jdbc/XmlQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/GenericDbmsSupport.java
  core/src/main/java/nl/nn/adapterframework/jdbc/dbms/IDbmsSupport.java
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTableListenerTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
  core/src/test/java/nl/nn/adapterframework/jdbc/dbms/DbmsSupportTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/dbms/H2DbmsSupportTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/dbms/SqlTranslatorOracleToH2Test.java
  core/src/test/java/nl/nn/adapterframework/jdbc/dbms/SqlTranslatorOracleToMsSqlTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/dbms/TestBlobs.java
Labels: Frank Framework, Technical Debt

#5095 Add StringUtil.split() method to replace most uses of legacy StringTokenizer
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisUtils.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/mtom/MtomResponseWrapper.java
  console/backend/src/main/java/nl/nn/adapterframework/management/web/ServletDispatcher.java
  core/src/main/java/nl/nn/adapterframework/batch/AbstractRecordHandler.java
  core/src/main/java/nl/nn/adapterframework/batch/RecordTransformer.java
  core/src/main/java/nl/nn/adapterframework/batch/RecordXmlTransformer.java
  core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsListener.java
  core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWrapperPipe.java
  core/src/main/java/nl/nn/adapterframework/http/HttpSenderBase.java
  core/src/main/java/nl/nn/adapterframework/http/RestServiceDispatcher.java
  core/src/main/java/nl/nn/adapterframework/http/WebServiceListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/MessageStoreListener.java
  core/src/main/java/nl/nn/adapterframework/jdbc/MessageStoreSender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/XmlQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsSender.java
  core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
  core/src/main/java/nl/nn/adapterframework/lifecycle/ServletManager.java
  core/src/main/java/nl/nn/adapterframework/monitoring/Monitor.java
  core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
  core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/RemoveFromSession.java
  core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java
  core/src/main/java/nl/nn/adapterframework/processors/InputOutputPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/receivers/FileRecordListener.java
  core/src/main/java/nl/nn/adapterframework/senders/MailSenderBase.java
  core/src/main/java/nl/nn/adapterframework/util/AppConstants.java
  core/src/main/java/nl/nn/adapterframework/util/ProcessUtil.java
  core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/FileViewerServlet.java
  core/src/main/java/nl/nn/adapterframework/xcom/XComSender.java
  core/src/test/java/nl/nn/adapterframework/pipes/PgpPipeTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/mock/PreparedStatementMock.java
  credentialProvider/src/main/java/nl/nn/credentialprovider/util/AppConstants.java
  iaf-commons/src/main/java/nl/nn/adapterframework/util/StringUtil.java
  iaf-commons/src/test/java/nl/nn/adapterframework/util/StringUtilTest.java
  ladybug/src/main/java/nl/nn/ibistesttool/PipeDescription.java
  ladybug/src/main/java/nl/nn/ibistesttool/PipeDescriptionProvider.java
  larva/src/main/java/nl/nn/adapterframework/pipes/LarvaPipe.java
  larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
Labels: Frank Framework, Technical Debt

#5112 Add deprecation filter for older API endpoints
  RELEASES.md
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/CompatibilityShowScheduler.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/DeprecationFilter.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/Init.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowScheduler.java
  core/src/main/resources/AppConstants.properties
  core/src/test/java/nl/nn/adapterframework/webcontrol/api/TestDeprecationFilter.java
Labels: Bug, Backport

#5105 Add deprecation filter for older API endpoints
  RELEASES.md
  console/backend/pom.xml
  console/backend/src/main/java/nl/nn/adapterframework/management/web/CompatibilityShowScheduler.java
  console/backend/src/main/java/nl/nn/adapterframework/management/web/DeprecationFilter.java
  console/backend/src/main/java/nl/nn/adapterframework/management/web/FrankApiBase.java
  console/backend/src/main/java/nl/nn/adapterframework/management/web/Init.java
  console/backend/src/main/java/nl/nn/adapterframework/management/web/ShowScheduler.java
  console/backend/src/test/java/nl/nn/adapterframework/management/web/TestDeprecationFilter.java
  console/backend/src/test/java/nl/nn/adapterframework/util/TestAppender.java
  core/src/main/resources/AppConstants.properties
Labels: Bug, Feature, Technical Debt

#5124 Add RestListener authroles and monitor test
  core/src/main/java/nl/nn/adapterframework/http/RestListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/monitoring/MonitorDestinationBase.java
  core/src/main/java/nl/nn/adapterframework/monitoring/MonitorManager.java
  core/src/main/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapter.java
  core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowMonitors.java
  core/src/test/java/nl/nn/adapterframework/monitoring/MonitorTest.java
  core/src/test/java/nl/nn/adapterframework/monitoring/SenderMonitorAdapterTest.java
  core/src/test/resources/Management/Monitoring/getManagerToXML.xml
  core/src/test/resources/testMonitoringContext.xml
Labels: Backport

#5131 Test updates for issue #5104
  core/src/test/java/nl/nn/adapterframework/pipes/CompressPipeTest.java
Labels: Bug

#5130 Fix CompressPipe not closing streams
  core/src/main/java/nl/nn/adapterframework/pipes/CompressPipe.java
  core/src/test/java/nl/nn/adapterframework/pipes/CompressPipeTest.java
Labels: Bug, Backport

#5127 Fix Json2XmlValidator response type parsing (7.8)
  core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java
  core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
Labels: Bug, Backport

#5137 Backport JWT principal claim name to 7.8
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
Labels: Backport

#5151 Fix #5149 JMS Ack not being sent when in mode CLIENT_ACKNOWLEDGE
  core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsListener.java
  core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfListener.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsListenerBase.java
  core/src/main/java/nl/nn/adapterframework/jms/PullingJmsListener.java
  ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/PullingIfsaProviderListener.java
  ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/PushingIfsaProviderListener.java
Labels: Bug

#5141 Prevent runtime type exceptions and check lists for JWT role claim (7.8)
  core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
Labels: Backport
