Repository frankframework/frankframework, pull requests merged in 2023-11, with the labels that each got.

#5677 Some small preparatory changes for JDK17 support
  iaf-commons/pom.xml
  iaf-commons/src/main/java/nl/nn/adapterframework/core/IbisException.java
  iaf-commons/src/test/java/nl/nn/adapterframework/core/IbisExceptionTest.java
  management-gateway/pom.xml
  management-gateway/src/main/java/nl/nn/adapterframework/management/security/JwtKeyGenerator.java
  management-gateway/src/main/java/nl/nn/adapterframework/management/security/JwtSecurityFilter.java
Labels: Technical Debt

#5720 Add supportedCipherSuites attribute to HTTP senders
  core/src/main/java/nl/nn/adapterframework/encryption/AuthSSLContextFactory.java
  core/src/main/java/nl/nn/adapterframework/http/HttpSessionBase.java
  core/src/test/java/nl/nn/adapterframework/http/HttpSenderTest.java
Labels: Backport, 7.9

#5726 Fix zip with empty files added by sub-adapters
  core/src/main/java/nl/nn/adapterframework/collection/Collection.java
  core/src/main/java/nl/nn/adapterframework/compression/ZipWriter.java
  core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
  core/src/main/java/nl/nn/adapterframework/util/StreamCaptureUtils.java
  test/src/main/configurations/MainConfig/ConfigurationZip.xml
  test/src/test/testtool/Zip/ZipWriter/output-3.xml
  test/src/test/testtool/Zip/ZipWriter/scenario03.properties
Labels: Bug, 7.9

#5731 Backport Oracle xa resource
  docker/JBoss/src/configuration/standalone.xml
  docker/WebSphere/src/configuration/02-configureJdbc.py
  docker/WildFly/src/configuration/standalone.xml
  docker/oracle-xa.yml
  test/src/main/webapp/META-INF/context.xml
Labels: Backport, 7.9

#5732 Backport Oracle xa resource
  docker/JBoss/src/configuration/standalone.xml
  docker/WebSphere/src/configuration/02-configureJdbc.py
  docker/WildFly/src/configuration/standalone.xml
  docker/oracle-xa.yml
  test/src/main/webapp/META-INF/context.xml
Labels: Backport, 7.8

#5734 Fix zip with empty files added by sub-adapters (#5702)
  core/src/main/java/nl/nn/adapterframework/collection/Collection.java
  core/src/main/java/nl/nn/adapterframework/compression/ZipWriter.java
  core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java
  core/src/main/java/nl/nn/adapterframework/util/StreamCaptureUtils.java
  test/src/main/configurations/MainConfig/ConfigurationZip.xml
  test/src/test/testtool/Zip/ZipWriter/output-3.xml
  test/src/test/testtool/Zip/ZipWriter/scenario03.properties
Labels: Bug

#5736 Introduce AnyMatchClaims attribute (#5201)
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/jwt/JwtSecurityHandler.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
Labels: Feature

#5757 Fix for StringIndexOutOfBoundsException (#5752)
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
Labels: 7.8

#5753 Fixes for the MultipartUtils headers parser
  core/src/main/java/nl/nn/adapterframework/http/mime/MultipartUtils.java
  core/src/test/java/nl/nn/adapterframework/http/mime/MultipartUtilsTest.java
Labels: Backport, 7.9

#5768 Fix issue #5752 (forward port from 7.8-release)
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
Labels: Bug

#5764 Fix MultipartUtils headers parser (#5718)
  core/src/main/java/nl/nn/adapterframework/http/mime/MultipartUtils.java
  core/src/test/java/nl/nn/adapterframework/http/mime/MultipartUtilsTest.java
Labels: Bug, 7.8

#5770 Fix messagelog MDC pattern notation
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLineResult.java
  core/src/main/java/nl/nn/adapterframework/http/cxf/SOAPProviderBase.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactory.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisNdcPatternConverter.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisPatternLayout.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisThrowablePatternConverter.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/util/LogUtil.java
  core/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  core/src/main/resources/log4j4ibis.xml
  core/src/test/java/nl/nn/adapterframework/logging/TestLogMessages.java
  test/src/main/configurations/MainConfig/CorrelationMessageId/result.xml
  test/src/test/testtool/CorrelationMessageId/scenario01.properties
  test/src/test/testtool/CorrelationMessageId/scenario01/out.xml
  test/src/test/testtool/CorrelationMessageId/scenario02.properties
  test/src/test/testtool/CorrelationMessageId/scenario02/out.xml
  test/src/test/testtool/CorrelationMessageId/scenario03.properties
  test/src/test/testtool/CorrelationMessageId/scenario03/out.xml
  test/src/test/testtool/CorrelationMessageId/scenario04.properties
  test/src/test/testtool/CorrelationMessageId/scenario04/out.xml
  test/src/test/testtool/CorrelationMessageId/scenario05.properties
  test/src/test/testtool/CorrelationMessageId/scenario05/out.xml
  test/src/test/testtool/ForEachChildElementPipe/01/out.json
  test/src/test/testtool/ForEachChildElementPipe/05/out.json
Labels: Bug, Backport, 7.8

#5769 Fix messagelog MDC pattern notation
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/core/Adapter.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLineResult.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisLoggerConfigurationFactory.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisNdcPatternConverter.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisPatternLayout.java
  core/src/main/java/nl/nn/adapterframework/logging/IbisThrowablePatternConverter.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/util/LogUtil.java
  core/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  core/src/main/resources/log4j4ibis.xml
  core/src/test/java/nl/nn/adapterframework/logging/TestLogMessages.java
  test/src/test/testtool/ForEachChildElementPipe/01/out.json
  test/src/test/testtool/ForEachChildElementPipe/05/out.json
Labels: Bug, Backport, 7.9

#5788 Chore/compare enums with equality operator
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisUtils.java
  core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationMessageEvent.java
  core/src/main/java/nl/nn/adapterframework/extensions/test/IbisTester.java
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java
  core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java
  core/src/main/java/nl/nn/adapterframework/http/HttpSender.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/lifecycle/ApplicationMessageEvent.java
  core/src/main/java/nl/nn/adapterframework/lifecycle/IbisApplicationContext.java
  core/src/main/java/nl/nn/adapterframework/mongodb/StrictJsonDocumentWriter.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/scheduler/JobDefFunctions.java
  core/src/main/java/nl/nn/adapterframework/stream/xml/JsonXslt3XmlHandler.java
  core/src/main/java/nl/nn/adapterframework/stream/xml/JsonXslt3XmlReader.java
  core/src/main/java/nl/nn/adapterframework/util/RunStateManager.java
  core/src/test/java/nl/nn/adapterframework/configuration/classloaders/ConfigurationClassLoaderTestBase.java
  core/src/test/java/nl/nn/adapterframework/filesystem/smb/Samba2FileSystemTestHelper.java
  core/src/test/java/nl/nn/adapterframework/http/HttpMessageEntityTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/OpenApiTestBase.java
  core/src/test/java/nl/nn/adapterframework/testutil/MessageTestUtils.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/rekenbox/CalcboxOutputReader.java
Labels: Technical Debt

#5787 Code Quality: Use the diamond operator
  aspose/src/test/java/com/testautomationguru/utility/PDFUtil.java
  cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisSenderTestBase.java
  cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisTestObject.java
  console/backend/src/test/java/nl/nn/adapterframework/management/web/FrankApiTestBase.java
  console/backend/src/test/java/nl/nn/adapterframework/management/web/SendJmsMessageTest.java
  console/backend/src/test/java/nl/nn/adapterframework/management/web/TestPipelineTest.java
  console/backend/src/test/java/nl/nn/adapterframework/management/web/TestServiceListenerTest.java
  console/backend/src/test/java/nl/nn/adapterframework/management/web/TestShowLiquibaseScript.java
  core/src/test/java/nl/nn/adapterframework/align/OverridesMapTest.java
  core/src/test/java/nl/nn/adapterframework/align/TestDomTreeAligner.java
  core/src/test/java/nl/nn/adapterframework/align/TestJson2Xml.java
  core/src/test/java/nl/nn/adapterframework/collection/CollectionSenderTest.java
  core/src/test/java/nl/nn/adapterframework/collection/CollectorPipeTest.java
  core/src/test/java/nl/nn/adapterframework/configuration/Stub4TesttoolTest.java
  core/src/test/java/nl/nn/adapterframework/configuration/classloaders/ClassLoaderMock.java
  core/src/test/java/nl/nn/adapterframework/configuration/classloaders/ConfigurationClassLoaderTestBase.java
  core/src/test/java/nl/nn/adapterframework/filesystem/BasicFileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemListenerTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockAttachment.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockFile.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockFileSystem.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockFileSystemListenerTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockFileSystemSenderTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockFileWithAttachments.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockFolder.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockForEachAttachmentPipeTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/smb/Samba2FileSystemTestHelper.java
  core/src/test/java/nl/nn/adapterframework/http/PartMessageTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcherTest.java
  core/src/test/java/nl/nn/adapterframework/http/rest/OpenApiTestBase.java
  core/src/test/java/nl/nn/adapterframework/management/bus/BusTestEndpoints.java
  core/src/test/java/nl/nn/adapterframework/parameters/ParameterTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/ForEachChildElementPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/GetFromSessionTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/JwtPipeTest.java
  core/src/test/java/nl/nn/adapterframework/senders/mail/MailSenderTestBase.java
  core/src/test/java/nl/nn/adapterframework/stream/FileMessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/PathMessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/UrlMessageTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/MatchUtils.java
  core/src/test/java/nl/nn/adapterframework/util/AppConstantsTest.java
  core/src/test/java/nl/nn/adapterframework/util/XmlUtilsTest.java
  core/src/test/java/nl/nn/adapterframework/validation/ValidatorTestBase.java
  core/src/test/java/nl/nn/adapterframework/xslt/ParallelXsltTest.java
  credentialProvider/src/test/java/nl/nn/credentialprovider/WildFlyCredentialFactoryTest.java
  iaf-commons/src/test/java/nl/nn/adapterframework/util/StringUtilTest.java
  idin/src/test/java/nl/nn/adapterframework/extensions/idin/IdinSenderTest.java
  test-integration/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisSenderTest.java
  test-integration/src/test/java/nl/nn/adapterframework/filesystem/BasicFileSystemTestBase.java
  test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeMailListenerTest.java
  test-integration/src/test/java/nl/nn/adapterframework/filesystem/ExchangeMailListenerTestBase.java
  test-integration/src/test/java/nl/nn/adapterframework/ldap/LdapFindMembershipsPipeTest.java
Labels: Technical Debt

#5830 Fix "OnlyIfSessionKey" behaviour on missing that session key
  core/src/main/java/nl/nn/adapterframework/processors/InputOutputPipeProcessor.java
  core/src/test/java/nl/nn/adapterframework/processors/InputOutputPipeProcessorTest.java
Labels: Bug

#5827 Add security-constraint to web.xml
  .github/workflows/maven-build.yml
  security/src/main/java/nl/nn/adapterframework/lifecycle/servlets/ServletAuthenticatorBase.java
  security/src/main/java/nl/nn/adapterframework/lifecycle/servlets/ServletConfiguration.java
  webapp/src/main/webapp/WEB-INF/web.xml
Labels: Bug, Backport, 7.9

#5843 Code Quality: Use Diamond Operator
  aws/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisHttpInvoker.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSender.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisUtils.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/FilterCmisService.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/server/impl/IbisRepositoryService.java
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/servlets/CmisLifecycleBean.java
  core/src/main/java/nl/nn/adapterframework/align/DomTreeAligner.java
  core/src/main/java/nl/nn/adapterframework/align/Json2Xml.java
  core/src/main/java/nl/nn/adapterframework/align/Properties2Xml.java
  core/src/main/java/nl/nn/adapterframework/align/SubstitutionNode.java
  core/src/main/java/nl/nn/adapterframework/align/ToXml.java
  core/src/main/java/nl/nn/adapterframework/align/Tree2Xml.java
  core/src/main/java/nl/nn/adapterframework/align/Xml2Map.java
  core/src/main/java/nl/nn/adapterframework/align/XmlAligner.java
  core/src/main/java/nl/nn/adapterframework/align/XmlTo.java
  core/src/main/java/nl/nn/adapterframework/align/XmlTypeToJsonSchemaConverter.java
  core/src/main/java/nl/nn/adapterframework/align/content/JsonElementContainer.java
  core/src/main/java/nl/nn/adapterframework/align/content/MapContentContainer.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ConnectedFileSystemBase.java
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemUtils.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ForEachAttachmentPipe.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java
  core/src/main/java/nl/nn/adapterframework/filesystem/LocalFileSystem.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTransactionalStorage.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsRealmFactory.java
  core/src/main/java/nl/nn/adapterframework/jta/TransactionConnector.java
  core/src/main/java/nl/nn/adapterframework/jta/TransactionConnectorCoordinator.java
  core/src/main/java/nl/nn/adapterframework/jwt/JwtValidator.java
  core/src/main/java/nl/nn/adapterframework/ldap/LdapClient.java
  core/src/main/java/nl/nn/adapterframework/ldap/LdapFindGroupMembershipsPipe.java
  core/src/main/java/nl/nn/adapterframework/ldap/LdapFindMemberPipe.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/AdapterStatistics.java
  core/src/main/java/nl/nn/adapterframework/mongodb/ResourceBasedMongoClientFactory.java
  core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/ValidatorBase.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/main/java/nl/nn/adapterframework/soap/WsdlGenerator.java
  core/src/main/java/nl/nn/adapterframework/statistics/StatisticsKeeper.java
  core/src/main/java/nl/nn/adapterframework/util/Dir2Map.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  core/src/main/java/nl/nn/adapterframework/util/ProcessMetrics.java
  core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java
  core/src/main/java/nl/nn/adapterframework/xml/SkipEmptyTagsFilter.java
  ladybug/src/main/java/nl/nn/ibistesttool/Debugger.java
  ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
  ladybug/src/main/java/nl/nn/ibistesttool/LadybugPipe.java
  ladybug/src/main/java/nl/nn/ibistesttool/tibet2/Storage.java
  larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/svn/ScanTibcoSolutionPipe.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/SapSystemFactory.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/IdocXmlHandler.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/SapFunctionFacade.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/tx/JcoResourceHolder.java
Labels: Technical Debt

#5840 Code Quality: String replace fixes
  core/src/main/java/nl/nn/adapterframework/soap/SoapVersion.java
  core/src/main/java/nl/nn/adapterframework/soap/WsdlGeneratorUtils.java
  core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java
  core/src/main/java/nl/nn/adapterframework/util/flow/graphviz/GraphvizEngine.java
  core/src/test/java/nl/nn/adapterframework/http/HttpResponseMock.java
  core/src/test/java/nl/nn/adapterframework/http/RestSenderTest.java
  core/src/test/java/nl/nn/adapterframework/http/cxf/SoapProviderTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/migration/MigratorTest.java
  core/src/test/java/nl/nn/adapterframework/stream/document/DocumentBuilderTest.java
  core/src/test/java/nl/nn/adapterframework/util/XmlBuilderTest.java
  dbms/src/main/java/nl/nn/adapterframework/dbms/GenericDbmsSupport.java
  dbms/src/test/java/nl/nn/adapterframework/dbms/SqlTranslatorOracleToH2Test.java
  dbms/src/test/java/nl/nn/adapterframework/dbms/SqlTranslatorOracleToMsSqlTest.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/afm/Afm2EdiFactSender.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/esb/WsdlGeneratorPipe.java
Labels: Technical Debt

#5842 Code Quality: Remove redundant casts
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisUtils.java
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemUtils.java
  core/src/main/java/nl/nn/adapterframework/management/bus/endpoints/SecurityItems.java
  core/src/main/java/nl/nn/adapterframework/pgp/Encrypt.java
  core/src/main/java/nl/nn/adapterframework/pipes/XmlFileElementIteratorPipe.java
  core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  core/src/test/java/nl/nn/adapterframework/configuration/ClassLoaderManagerTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/mock/MockFileSystemTestHelper.java
  core/src/test/java/nl/nn/adapterframework/http/HttpMessageEntityTest.java
  core/src/test/java/nl/nn/adapterframework/jta/TransactionConnectorTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/MoveFilePipeTest.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
  core/src/test/java/nl/nn/adapterframework/testutil/mock/MockIbisManager.java
  ifsa/src/main/java/nl/nn/adapterframework/extensions/ifsa/jms/IfsaFacade.java
  larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
  larva/src/main/java/nl/nn/adapterframework/testtool/queues/QueueCreator.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/svn/ScanTibcoSolutionPipe.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/SapSystemFactory.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/IdocXmlHandler.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/handlers/RootHandler.java
  sap/src/main/java/nl/nn/adapterframework/extensions/sap/jco3/tx/JcoResourceHolder.java
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
Labels: Technical Debt

#5848 Fix issue with BytesMessage not being correctly processed (#5794)
  core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbJmsListener.java
  core/src/main/java/nl/nn/adapterframework/jms/BytesMessageInputStream.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsListener.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsMessageBrowserIteratorItem.java
  core/src/main/java/nl/nn/adapterframework/util/JdbcUtil.java
  core/src/test/java/nl/nn/adapterframework/extensions/esb/EsbJmsListenerTest.java
  core/src/test/resources/AppConstants.properties
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/SendTibcoMessage.java
Labels: Bug, 7.9

#5836 Remove more streaming pipes
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/IteratingPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/XsltPipe.java
  core/src/main/java/nl/nn/adapterframework/stream/MessageOutputStream.java
  core/src/main/java/nl/nn/adapterframework/stream/StreamingPipe.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/ForEachChildElementPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/JsonXsltPipeTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/MessageSendingPipeTest.java
  core/src/test/java/nl/nn/adapterframework/stream/StreamingPipeTest.java
  core/src/test/java/nl/nn/adapterframework/stream/StreamingPipeTestBase.java
  core/src/test/java/nl/nn/adapterframework/xslt/XsltErrorTestBase.java
  core/src/test/java/nl/nn/adapterframework/xslt/XsltTestBase.java
  ladybug/src/main/resources/springIbisDebuggerAdvice.xml
  test/src/test/testtool/ForEachChildElementPipe/01/out.json
  test/src/test/testtool/ForEachChildElementPipe/05/out.json
  test/src/test/testtool/global.properties
Labels: Technical Debt

#5868 Minor code cleanups in FileUtils and FileListener
  core/src/main/java/nl/nn/adapterframework/pipes/CleanupOldFilesPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/MoveFilePipe.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  larva/src/main/java/nl/nn/adapterframework/testtool/FileListener.java
Labels: Technical Debt

#5864 Reduce duplicate implementations to remove namespaces from XML
  core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsSender.java
  core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
  core/src/main/java/nl/nn/adapterframework/pipes/Json2XmlValidator.java
  core/src/main/java/nl/nn/adapterframework/pipes/XmlBuilderPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/XmlValidator.java
  core/src/main/java/nl/nn/adapterframework/processors/CorePipeLineProcessor.java
  core/src/main/java/nl/nn/adapterframework/soap/SoapWrapperPipe.java
  core/src/main/java/nl/nn/adapterframework/util/XmlException.java
  core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java
  core/src/main/java/nl/nn/adapterframework/xml/NamespaceRemovingFilter.java
  core/src/test/java/nl/nn/adapterframework/core/ResourceTest.java
  core/src/test/java/nl/nn/adapterframework/util/XmlUtilsTest.java
  core/src/test/java/nl/nn/adapterframework/xml/ClassLoaderURIResolverTest.java
  ear/pom.xml
  ear/src/main/application/META-INF/jboss-deployment-structure.xml
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/bis/BisJmsListener.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/bis/BisWrapperPipe.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/svn/ScanTibcoSolutionPipe.java
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/svn/SvnUtils.java
Labels: Technical Debt

#5873 Remove more streaming pipes; follow up on #5836
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemSender.java
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemSenderWithAttachments.java
  core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/FixedQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcSenderBase.java
  core/src/main/java/nl/nn/adapterframework/mongodb/MongoDbSender.java
  core/src/main/java/nl/nn/adapterframework/pipes/ForEachChildElementPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/XsltPipe.java
  core/src/main/java/nl/nn/adapterframework/senders/JsonXsltSender.java
  core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java
  core/src/main/java/nl/nn/adapterframework/stream/IStreamingSender.java
  core/src/main/java/nl/nn/adapterframework/stream/StreamingSenderBase.java
  core/src/main/java/nl/nn/adapterframework/xml/IXmlDebugger.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemSenderTest.java
  core/src/test/java/nl/nn/adapterframework/senders/JsonXsltSenderTest.java
  core/src/test/java/nl/nn/adapterframework/xslt/ParallelXsltTest.java
  ladybug/src/main/java/nl/nn/ibistesttool/IbisDebuggerAdvice.java
  ladybug/src/main/resources/springIbisDebuggerAdvice.xml
Labels: Technical Debt

#5872 Some code cleanups in ConfigurationUtils
  core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java
  core/src/main/java/nl/nn/adapterframework/configuration/classloaders/DatabaseClassLoader.java
Labels: Technical Debt

#5884 Fix spaces in timestamps that are added to filenames.
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemListener.java
  core/src/main/java/nl/nn/adapterframework/util/DateUtils.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemListenerTest.java
Labels: 7.9

#5889 Some small moves and code-enhancements before real refactoring
  core/src/main/java/nl/nn/adapterframework/extensions/esb/EsbSoapWrapperPipe.java
  core/src/test/java/nl/nn/adapterframework/receivers/ReceiverTest.java
  core/src/test/java/nl/nn/adapterframework/senders/JavascriptSenderCallbackTest.java
  core/src/test/java/nl/nn/adapterframework/senders/JavascriptSenderTest.java
  core/src/test/java/nl/nn/adapterframework/xslt/ParallelXsltTest.java
  nn-specials/pom.xml
  nn-specials/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java
  nn-specials/src/test/java/nl/nn/adapterframework/extensions/esb/EsbJmsListenerTest.java
Labels: Technical Debt

#5886 Removeunused copy of FilenameUtils
  credentialProvider/src/main/java/nl/nn/credentialprovider/util/FilenameUtils.java
Labels: Technical Debt, 7.9
