Repository frankframework/frankframework, pull requests merged in 2024-06, with the labels that each got.

#6941 Use DatabaseTest instead of TxManagerTest for 2 tests
  core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java
  core/src/test/java/org/frankframework/scheduler/CheckReloadJobTest.java
Labels: Technical Debt

#6938 Fix some JTA tests, disable some other broken JTA tests
  core/src/test/java/org/frankframework/jta/StatusRecordingTransactionManagerImplementationTest.java
  core/src/test/java/org/frankframework/jta/TransactionConnectorTest.java
  core/src/test/resources/AppConstants.properties
Labels: Technical Debt

#6940 Minor cleanup of some test code
  core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java
  core/src/test/java/org/frankframework/scheduler/CheckReloadJobTest.java
  core/src/test/java/org/frankframework/scheduler/CleanupDatabaseJobTest.java
Labels: Technical Debt

#6942 Test improvement: use enums instead of strings for checks on database type
  core/src/test/java/org/frankframework/jdbc/FixedQuerySenderTest.java
  core/src/test/java/org/frankframework/jdbc/StoredProcedureQuerySenderTest.java
  core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java
  core/src/test/java/org/frankframework/jta/StatusRecordingTransactionManagerImplementationTest.java
Labels: Technical Debt

#6888 Add nightly release workflow
  .github/workflows/nightly-release.yml
Labels: 8.0

#6943 Fix detection of "Skip locked row" support for MariaDB
  core/src/test/java/org/frankframework/jdbc/dbms/DbmsSupportTest.java
  dbms/src/main/java/org/frankframework/dbms/Dbms.java
  dbms/src/main/java/org/frankframework/dbms/MariaDbDbmsSupport.java
  dbms/src/test/java/org/frankframework/dbms/MariaDbDbmsSupportTest.java
Labels: Backport, 8.1

#6925 Add CSRF handling to Spring MVC & Angular
  console/backend/src/main/java/org/frankframework/management/web/ConfigurationStatus.java
  console/backend/src/main/java/org/frankframework/web/filters/CsrfCookieFilter.java
  console/backend/src/main/java/org/frankframework/web/filters/DynamicFilterConfigurer.java
  console/frontend/src/main/frontend/src/app/app.module.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
  core/src/main/resources/AppConstants.properties
  core/src/main/resources/StageSpecifics_LOC.properties
  security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
  security/src/main/java/org/frankframework/lifecycle/servlets/SpaCsrfTokenRequestHandler.java
Labels: Frank Console

#6951 Fix error when csrf is disabled
  console/backend/src/main/java/org/frankframework/web/filters/CsrfCookieFilter.java
Labels: Frank Console

#6953 Few more small test improvements after code review
  core/src/test/java/org/frankframework/jdbc/FixedQuerySenderTest.java
  core/src/test/java/org/frankframework/jdbc/dbms/DbmsSupportTest.java
Labels: Technical Debt

#6956 Remove HttpOnly from CSRF cookie
  console/frontend/src/main/frontend/src/app/views/webservices/webservices.component.html
  security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
Labels: Frank Console

#6955 Improve Message closing and fail when using a closed message
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/main/java/org/frankframework/parameters/ParameterList.java
  core/src/main/java/org/frankframework/processors/CorePipeProcessor.java
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/test/java/org/frankframework/monitoring/MonitorTest.java
Labels: Technical Debt

#6939 Fix misplaced data-cy-status-alert
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
Labels: Frank Console

#6970 Add search & sort to uploaded configurations table
  console/backend/src/main/java/org/frankframework/management/web/Configuration.java
  console/backend/src/main/java/org/frankframework/management/web/FrankApiBase.java
  console/frontend/src/main/frontend/src/app/components/th-sortable.directive.ts
  console/frontend/src/main/frontend/src/app/utils.ts
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component.html
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component.ts
Labels: Frank Console

#6972 Catch more Console API exceptions & Sanitize exception message in error page jsp
  console/backend/src/main/java/org/frankframework/management/web/ApiExceptionHandler.java
  console/backend/src/main/java/org/frankframework/management/web/SpringBusExceptionHandler.java
  core/src/main/resources/META-INF/resources/iaf/jsp/debuginfo.jsp
  core/src/main/resources/META-INF/resources/iaf/jsp/errorPage.jsp
Labels: Frank Console

#7000 Fix MongoDbSender: process array with objects
  core/pom.xml
  core/src/main/java/org/frankframework/jdbc/datasource/FrankResources.java
  core/src/main/java/org/frankframework/mongodb/IMongoClientFactory.java
  core/src/main/java/org/frankframework/mongodb/JndiMongoClientFactory.java
  core/src/main/java/org/frankframework/mongodb/JsonDocumentWriter.java
  core/src/main/java/org/frankframework/mongodb/MongoDbSender.java
  core/src/main/java/org/frankframework/mongodb/StrictJsonDocumentWriter.java
  core/src/test/java/org/frankframework/mongodb/JsonDocumentWriterTest.java
  core/src/test/java/org/frankframework/mongodb/MongoDbSenderTest.java
  docker/mongodb.yml
  pom.xml
  test-integration/src/test/java/org/frankframework/mongodb/MongoDbSenderTest.java
  test/pom.xml
  test/src/main/configurations/MainConfig/ConfigurationMongoDbSender.xml
  test/src/main/resources/resources.yml
  test/src/main/webapp/META-INF/context.xml
Labels: Backport, 8.1

#7008 Pipe/Validator related refactoring and code-cleanup
  core/src/main/java/org/frankframework/core/AbstractResponseValidatorWrapper.java
  core/src/main/java/org/frankframework/core/Adapter.java
  core/src/main/java/org/frankframework/core/IPipe.java
  core/src/main/java/org/frankframework/pipes/AbstractPipe.java
  core/src/main/java/org/frankframework/pipes/ValidatorBase.java
  core/src/main/java/org/frankframework/pipes/XmlValidator.java
  core/src/main/java/org/frankframework/processors/MonitoringPipeProcessor.java
  core/src/test/java/org/frankframework/core/AdapterTest.java
Labels: Technical Debt

#7039 Some code refactoring that I couldn't stop myself from doing.
  core/src/main/java/org/frankframework/configuration/ConfigurationMessageEvent.java
  core/src/main/java/org/frankframework/lifecycle/ApplicationMessageEvent.java
  core/src/main/java/org/frankframework/management/bus/endpoints/AdapterStatus.java
  core/src/main/java/org/frankframework/management/bus/endpoints/GetSchedules.java
  core/src/main/java/org/frankframework/management/bus/endpoints/ServerStatistics.java
  core/src/main/java/org/frankframework/util/MessageKeeper.java
  core/src/main/java/org/frankframework/util/MessageKeeperMessage.java
  core/src/test/java/org/frankframework/http/openapi/OpenApiTestBase.java
Labels: Technical Debt

#7028 Improve performance of hideRegex in logging
  commons/src/main/java/org/frankframework/util/StringUtil.java
  commons/src/test/java/org/frankframework/util/StringUtilTest.java
  core/src/main/java/org/frankframework/core/Adapter.java
  core/src/main/java/org/frankframework/logging/IbisMaskingLayout.java
  core/src/main/java/org/frankframework/stream/ThreadConnector.java
  core/src/main/java/org/frankframework/util/MessageKeeperMessage.java
  core/src/test/java/org/frankframework/logging/TestLogMessages.java
  ladybug/src/main/java/org/frankframework/ibistesttool/transform/HideRegexMessageTransformer.java
Labels: Performance, Technical Debt

#7062 Exclude testtool & larva from CSRF
  security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
Labels: Frank Console

#7072 Set actual defaults of jdbc-browse-tables as set in core
  console/backend/src/main/java/org/frankframework/management/web/ApiExceptionHandler.java
  console/backend/src/main/java/org/frankframework/management/web/SpringBusExceptionHandler.java
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
Labels: Frank Console

#7076 Change pace-js settings to work better with firefox
  console/frontend/src/main/frontend/src/app/app.component.ts
Labels: Frank Console

#7071 Fix switching from custom view to custom view
  console/frontend/src/main/frontend/src/app/components/custom-views/custom-views.component.html
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-custom-view/iframe-custom-view.component.ts
Labels: Frank Console
