Repository frankframework/frankframework, pull requests merged in 2024-03, with the labels that each got.

#6394 Improve Larva code base
  larva/src/main/java/org/frankframework/larva/FileListener.java
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/ListenerMessage.java
  larva/src/main/java/org/frankframework/larva/PropertyParser.java
  larva/src/main/java/org/frankframework/larva/ScenarioRunner.java
  larva/src/main/java/org/frankframework/larva/SenderThread.java
  larva/src/main/java/org/frankframework/larva/Util.java
  larva/src/main/java/org/frankframework/larva/XsltProviderListener.java
  larva/src/main/java/org/frankframework/larva/queues/QueueWrapper.java
Labels: Technical Debt

#6412 Small code improvement for use of TestConfigurations
  core/src/test/java/org/frankframework/receivers/ReceiverTest.java
  core/src/test/java/org/frankframework/receivers/TestReceiverOnError.java
  core/src/test/java/org/frankframework/senders/IbisLocalSenderTest.java
  core/src/test/java/org/frankframework/testutil/TestConfiguration.java
  core/src/test/java/org/frankframework/testutil/TransactionManagerType.java
Labels: Technical Debt

#6414 Add basic unit tests to LarvaPipe; upgrade plugin
  console/frontend/pom.xml
  larva/pom.xml
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/ListenerMessageHandler.java
  larva/src/main/java/org/frankframework/pipes/LarvaPipe.java
  larva/src/test/java/org/frankframework/pipes/LarvaPipeTest.java
  pom.xml
Labels: Technical Debt

#6421 Small backports: RELEASES.md file and make Larva working with Java 17+
  RELEASES.md
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario01/md-select.xml
  test/src/test/testtool/TransactionHandling/FailureInNonDbPipe/scenario02/md-select.xml
Labels: 8.0

#6435 SFTP Unit testing: Test if port is free, before using it for unit test
  filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemSenderTest.java
  filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/SftpFileSystemTestHelper.java
Labels: Bug, Technical Debt

#6437 Clean up TransformerPool.getInstance()
  core/src/main/java/org/frankframework/core/Resource.java
  core/src/main/java/org/frankframework/pipes/ForEachChildElementPipe.java
  core/src/main/java/org/frankframework/pipes/IteratingPipe.java
  core/src/main/java/org/frankframework/pipes/XmlIf.java
  core/src/main/java/org/frankframework/pipes/XmlValidator.java
  core/src/main/java/org/frankframework/soap/SoapWrapper.java
  core/src/main/java/org/frankframework/util/ClassLoaderUtils.java
  core/src/main/java/org/frankframework/util/TransformerPool.java
  core/src/main/java/org/frankframework/util/XmlUtils.java
  core/src/test/java/org/frankframework/align/TestAlignNamespacesXml.java
  core/src/test/java/org/frankframework/util/FunctionalTransformerPoolTestBase.java
  core/src/test/java/org/frankframework/util/TransformerPoolTest.java
  core/src/test/java/org/frankframework/util/XmlUtilsTest.java
  core/src/test/java/org/frankframework/util/XsltStreamingTest.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsListener.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsSender.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisUtils.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisWrapperPipe.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsListener.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/WsdlGeneratorPipe.java
  nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfWrapperPipe.java
Labels: Technical Debt

#6357 Use provided charset when converting to InputSource
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
  core/src/test/java/nl/nn/adapterframework/util/XmlUtilsTest.java
  core/src/test/resources/Util/MessageUtils/iso-8859-1.xml
  core/src/test/resources/Util/MessageUtils/iso-8859-1_without_xml_declaration.xml
  core/src/test/resources/Util/MessageUtils/utf8-with-bom.xml
  core/src/test/resources/Util/MessageUtils/utf8-without-bom.xml
Labels: Backport, 7.9

#6440 Update Java code style configuration
  .editorconfig
  Frank_Framework_CodeStyle Eclipse.xml
  Frank_Framework_CodeStyle IntelliJ.xml
Labels: 7.9

#6441 Update Java code style configuration
  .editorconfig
  Frank_Framework_CodeStyle Eclipse.xml
  Frank_Framework_CodeStyle IntelliJ.xml
Labels: 8.0

#6462 Use provided charset when converting to InputSource
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/test/java/org/frankframework/util/XmlUtilsTest.java
  core/src/test/resources/Util/MessageUtils/iso-8859-1.xml
  core/src/test/resources/Util/MessageUtils/iso-8859-1_without_xml_declaration.xml
  core/src/test/resources/Util/MessageUtils/utf8-with-bom.xml
  core/src/test/resources/Util/MessageUtils/utf8-without-bom.xml
Labels: 8.0

#6463 Selecting all messages will only select messages on screen
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
Labels: Backport, 8.0

#6464 Ibisstore fix table columns & link to store
  console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc.service.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/IbisstoreSummary.java
Labels: Backport, 8.0

#6465 Ibisstore fix table columns & link to store
  console/frontend/src/main/frontend/src/app/views/ibisstore-summary/ibisstore-summary.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc.service.ts
Labels: Backport, 7.9

#6475 Small improvements
  core/src/main/java/org/frankframework/core/PipeLineExit.java
  core/src/main/java/org/frankframework/pipes/BytesOutputPipe.java
  core/src/main/java/org/frankframework/pipes/ExceptionPipe.java
  core/src/main/java/org/frankframework/pipes/PasswordGeneratorPipe.java
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/main/java/org/frankframework/util/Misc.java
  core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd
  core/src/main/resources/xml/xsd/FrankConfig.xsd
  core/src/test/java/org/frankframework/receivers/JavaListenerTest.java
  docker/Tomcat/webapp/Dockerfile
Labels: Technical Debt

#6487 Fix Test a Pipeline not reading zip entries in certain cases
  console/backend/src/main/java/org/frankframework/management/web/TestPipeline.java
  console/backend/src/main/java/org/frankframework/management/web/TransactionalStorage.java
  console/backend/src/test/java/org/frankframework/management/web/TestPipelineTest.java
  console/backend/src/test/resources/TestPipeline/deflated.zip
  console/backend/src/test/resources/TestPipeline/stored.zip
Labels: Backport, 8.0

#6504 Fix duplicated messages in exception forwards
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisHttpSender.java
  cmis/src/test/java/org/frankframework/extensions/cmis/CmisHttpInvokerTest.java
  core/src/main/java/org/frankframework/processors/ExceptionHandlingPipeProcessor.java
  core/src/main/resources/SpringApplicationContext.xml
  core/src/test/java/org/frankframework/http/HttpResponseMock.java
  test/src/test/testtool/ClobAndBlob/scenario07/out.xml
  test/src/test/testtool/Senders/scenario01/out.xml
  test/src/test/testtool/UnzipPipeExceptionForwardTest/scenario01/out1.txt
Labels: Backport, 8.0

#6501 Use different defaults for Narayana JMS connection and session pools
  core/src/main/resources/AppConstants.properties
Labels: Backport, 7.9

#6500 Use different defaults for Narayana JMS connection and session pools
  core/src/main/resources/AppConstants.properties
Labels: Backport, 8.0

#6497 Fix duplicated messages in exception forwards
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisHttpSender.java
  cmis/src/test/java/nl/nn/adapterframework/extensions/cmis/CmisHttpInvokerTest.java
  core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/processors/TransactionAttributePipeProcessor.java
  core/src/main/resources/SpringApplicationContext.xml
  core/src/test/java/nl/nn/adapterframework/http/HttpResponseMock.java
  test/src/main/configurations/TX/TransactionFailureInDbPipe.xml
  test/src/test/testtool/ClobAndBlob/scenario07/out.xml
  test/src/test/testtool/Senders/scenario01/out.xml
  test/src/test/testtool/UnzipPipeExceptionForwardTest/scenario01/out1.txt
Labels: Backport, 7.9

#6512 Update vulnerable dependencies
  core/pom.xml
  management-gateway/pom.xml
  pom.xml
Labels: 8.0

#6513 Show toast on adapter reload
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/services/poller.service.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
Labels: Frank Console

#6516 Console iframe pages show pop out button
  console/frontend/src/main/frontend/src/app/app.service.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topinfobar/pages-topinfobar.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-topinfobar/pages-topinfobar.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-custom-view/iframe-custom-view.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug-beta/iframe-ladybug-beta.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug/iframe-ladybug.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-larva/iframe-larva.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe.base.ts
Labels: Frank Console, Feature

#6517 Add feedback on JMS 'Send Message' success & fix TestServiceListener
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
Labels: Frank Console

#6527 Bump Aspose, sec update commons-compress, move nimbus-jose-jwt to parent management
  aspose/pom.xml
  core/pom.xml
  management-gateway/pom.xml
  pom.xml
Labels: Dependencies

#6526 Manage AWS dependencies through BOM import in parent pom. Upgrade AWS deps
  aws/pom.xml
  pom.xml
Labels: Dependencies

#6528 Update vulnerable dependencies
  aspose/pom.xml
  aws/pom.xml
  credentialProvider/pom.xml
  ladybug/pom.xml
  pom.xml
Labels: Dependencies, 8.0

#6520 Add feedback on JMS 'Send Message' success & fix TestServiceListener
  console/frontend/src/main/frontend/src/app/services/poller.service.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
Labels: Frank Console, Backport, 7.9

#6519 Add feedback on JMS 'Send Message' success & fix TestServiceListener
  console/frontend/src/main/frontend/src/app/services/poller.service.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
Labels: Frank Console, Backport, 8.0

#6515 Update vulnerable dependencies
  README.md
  RELEASES.md
  aspose/pom.xml
  aws/pom.xml
  core/pom.xml
  credentialProvider/pom.xml
  docker/Tomcat/webapp/Dockerfile
  ladybug/pom.xml
  management-gateway/pom.xml
  pom.xml
Labels: Dependencies, 7.9

#6531 Fix elementToMove preserve
  core/src/main/java/org/frankframework/receivers/Receiver.java
  test/src/main/configurations/HTTP/ConfigurationApiListener.xml
  test/src/main/configurations/JMS/ConfigurationJmsListenerSender.xml
  test/src/test/testtool/ApiListener/04/call-exception-insert.xml
  test/src/test/testtool/ApiListener/04/md-select-result.xml
  test/src/test/testtool/ApiListener/04/md-select.xml
  test/src/test/testtool/ApiListener/scenario04.properties
  test/src/test/testtool/JmsListenerSender/FF/scenario03/in.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario03/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario03/out.xml
Labels: Bug

#6530 Fix elementToMove preserve and add test
  core/src/main/java/nl/nn/adapterframework/core/IBulkDataListener.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  test/src/main/configurations/HTTP/ConfigurationApiListener.xml
  test/src/main/configurations/JMS/ConfigurationJmsListenerSender.xml
  test/src/test/testtool/ApiListener/04/call-exception-insert.xml
  test/src/test/testtool/ApiListener/04/md-select-result.xml
  test/src/test/testtool/ApiListener/04/md-select.xml
  test/src/test/testtool/ApiListener/scenario04.properties
  test/src/test/testtool/JmsListenerSender/FF/scenario03/in.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario03/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario03/out.xml
Labels: Bug, Backport, 7.9

#6533 Fix elementToMove preserve
  core/src/main/java/org/frankframework/receivers/Receiver.java
  test/src/main/configurations/HTTP/ConfigurationApiListener.xml
  test/src/main/configurations/JMS/ConfigurationJmsListenerSender.xml
  test/src/test/testtool/ApiListener/04/call-exception-insert.xml
  test/src/test/testtool/ApiListener/04/md-select-result.xml
  test/src/test/testtool/ApiListener/04/md-select.xml
  test/src/test/testtool/ApiListener/scenario04.properties
  test/src/test/testtool/JmsListenerSender/FF/scenario03/in.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario03/md-select-result.xml
  test/src/test/testtool/JmsListenerSender/FF/scenario03/out.xml
Labels: Bug, Backport, 8.0

#6521 Add Kubernetes Module and CredentialFactory
  core/src/main/java/org/frankframework/lifecycle/IbisApplicationContext.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/Credentials.java
  kubernetes/pom.xml
  kubernetes/src/main/java/org/frankframework/credentialprovider/KubernetesCredentialFactory.java
  kubernetes/src/test/java/org/frankframework/credentialprovider/KubernetesCredentialFactoryTest.java
  pom.xml
Labels: Feature, Credential Provider

#6544 Add Spring Boot dependency management
  console/war/pom.xml
  core/pom.xml
  ladybug/pom.xml
  pom.xml
  test/pom.xml
Labels: Dependencies
