Repository frankframework/frankframework, pull requests merged in 2024-08, with the labels that each got.

#7218 Remove waitingDuration parameter and unused Receiver IdleStatistics
  core/src/main/java/org/frankframework/core/IMessageHandler.java
  core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/main/java/org/frankframework/statistics/FrankMeterType.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
  core/src/test/resources/metrics/myAdapter.json
  core/src/test/resources/metrics/myAdapter2.json
  larva/src/main/java/org/frankframework/larva/ListenerMessageHandler.java
Labels: Technical Debt

#7137 Implement SSL options for Tibco Classes
  docker/WebSphere/Dockerfile
  iaf-commons/src/main/java/nl/nn/adapterframework/util/PropertyLoader.java
  tibco/pom.xml
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/GetTibcoQueues.java
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/SendTibcoMessage.java
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/TibcoEmsProperties.java
  tibco/src/main/java/nl/nn/adapterframework/extensions/tibco/TibcoUtils.java
  tibco/src/test/java/nl/nn/adapterframework/extensions/tibco/TibcoJndiPropertiesTest.java
  tibco/src/test/resources/jndi.properties
  tibco/src/test/resources/log4j4ibis.xml
Labels: 7.9

#7236 Implement custom properties for Tibco classes
  commons/src/main/java/org/frankframework/util/PropertyLoader.java
  tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
  tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoEmsProperties.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
  tibco/src/test/java/org/frankframework/extensions/tibco/TibcoJndiPropertiesTest.java
  tibco/src/test/resources/jndi.properties
  tibco/src/test/resources/log4j4ibis.xml
Labels: Backport, 8.2

#7235 Implement custom properties for Tibco classes
  commons/src/main/java/org/frankframework/util/PropertyLoader.java
  tibco/pom.xml
  tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
  tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoEmsProperties.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
  tibco/src/test/java/org/frankframework/extensions/tibco/TibcoJndiPropertiesTest.java
  tibco/src/test/resources/jndi.properties
  tibco/src/test/resources/log4j4ibis.xml
Labels: Backport, 8.0

#7238 Implement custom properties for Tibco classes
  commons/src/main/java/org/frankframework/util/PropertyLoader.java
  tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
  tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoEmsProperties.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
  tibco/src/test/java/org/frankframework/extensions/tibco/TibcoJndiPropertiesTest.java
  tibco/src/test/resources/jndi.properties
  tibco/src/test/resources/log4j4ibis.xml
Labels: Backport, 8.1

#7246 Selecting all messages will only select messages on screen
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
Labels: 7.9

#7249 Fix asserting empty value in BrowseQueue
  console/backend/src/main/java/org/frankframework/management/web/BrowseQueue.java
Labels: Backport, 8.2

#7251 Fix asserting empty value in BrowseQueue
  console/backend/src/main/java/nl/nn/adapterframework/management/web/BrowseQueue.java
Labels: Backport, 7.9

#7252 Remove '/' in liquibase download url
  console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.ts
Labels: Backport, 8.2

#7265 Add local users yaml authenticator
  security/src/main/java/org/frankframework/lifecycle/servlets/AuthenticationType.java
  security/src/main/java/org/frankframework/lifecycle/servlets/YmlFileAuthenticator.java
Labels: Backport, 8.2

#7299 Tibco age field may not be negative (#7263)
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
Labels: Backport, 8.0

#7300 Tibco age field may not be negative (#7263)
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
Labels: Backport, 8.1

#7302 Tibco age field may not be negative (#7263)
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
Labels: Backport

#7301 Tibco age field may not be negative (#7263)
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoUtils.java
Labels: Backport, 8.2

#7304 Fix Json2XmlInputValidator with multiple optional elements (#7271)
  core/src/main/java/org/frankframework/align/DomTreeAligner.java
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/OverridesMap.java
  core/src/main/java/org/frankframework/align/Properties2Xml.java
  core/src/main/java/org/frankframework/align/ToXml.java
  core/src/main/java/org/frankframework/align/Tree2Xml.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/AttributesOnDifferentLevels/CommonResponse.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/MultipleOptionalElements.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-all.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-none.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial1.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial2.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial3.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial4.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial5.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-all.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-none.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial1.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial2.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial3.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial4.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial5.xml
Labels: Backport, 8.0

#7305 Fix Json2XmlInputValidator with multiple optional elements (#7271)
  core/src/main/java/org/frankframework/align/DomTreeAligner.java
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/OverridesMap.java
  core/src/main/java/org/frankframework/align/Properties2Xml.java
  core/src/main/java/org/frankframework/align/ToXml.java
  core/src/main/java/org/frankframework/align/Tree2Xml.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/AttributesOnDifferentLevels/CommonResponse.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/MultipleOptionalElements.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-all.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-none.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial1.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial2.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial3.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial4.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial5.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-all.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-none.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial1.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial2.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial3.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial4.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial5.xml
Labels: Backport, 8.1

#7306 Fix Json2XmlInputValidator with multiple optional elements (#7271)
  core/src/main/java/org/frankframework/align/DomTreeAligner.java
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/OverridesMap.java
  core/src/main/java/org/frankframework/align/Properties2Xml.java
  core/src/main/java/org/frankframework/align/ToXml.java
  core/src/main/java/org/frankframework/align/Tree2Xml.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/AttributesOnDifferentLevels/CommonResponse.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/MultipleOptionalElements.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-all.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-none.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial1.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial2.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial3.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial4.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial5.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-all.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-none.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial1.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial2.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial3.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial4.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial5.xml
Labels: Backport, 8.2

#7307 Fix Json2XmlInputValidator with multiple optional elements (#7271)
  core/src/main/java/org/frankframework/align/DomTreeAligner.java
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/OverridesMap.java
  core/src/main/java/org/frankframework/align/Properties2Xml.java
  core/src/main/java/org/frankframework/align/ToXml.java
  core/src/main/java/org/frankframework/align/Tree2Xml.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/AttributesOnDifferentLevels/CommonResponse.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/MultipleOptionalElements.xsd
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-all.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-none.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial1.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial2.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial3.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial4.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/input-partial5.json
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-all.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-none.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial1.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial2.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial3.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial4.xml
  core/src/test/resources/Validation/AttributesOnDifferentLevels/output-partial5.xml
Labels: Backport

#7308 Remove dead code from the "ToXml" subclasses
  core/src/main/java/org/frankframework/align/DomTreeAligner.java
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/Map2Xml.java
  core/src/main/java/org/frankframework/align/NamespaceAligningFilter.java
  core/src/main/java/org/frankframework/align/Properties2Xml.java
  core/src/main/java/org/frankframework/align/ToXml.java
  core/src/main/java/org/frankframework/align/Tree2Xml.java
  core/src/main/java/org/frankframework/align/XmlAligner.java
  core/src/test/java/org/frankframework/align/TestAlignNamespacesXml.java
  core/src/test/java/org/frankframework/align/TestAlignXml.java
  core/src/test/java/org/frankframework/align/TestDomTreeAligner.java
  core/src/test/java/org/frankframework/align/TestMap2Xml.java
  core/src/test/java/org/frankframework/validation/Json2XmlValidatorSmileyTest.java
Labels: Technical Debt

#7180 Console Backend unit tests for all endpoints
  console/backend/pom.xml
  console/backend/src/main/java/org/frankframework/management/web/AdapterStatistics.java
  console/backend/src/main/java/org/frankframework/management/web/ApiException.java
  console/backend/src/main/java/org/frankframework/management/web/ApiExceptionHandler.java
  console/backend/src/main/java/org/frankframework/management/web/BrowseJdbcTable.java
  console/backend/src/main/java/org/frankframework/management/web/BrowseQueue.java
  console/backend/src/main/java/org/frankframework/management/web/ClassInfo.java
  console/backend/src/main/java/org/frankframework/management/web/ConfigurationStatus.java
  console/backend/src/main/java/org/frankframework/management/web/ConfigurationsEndpoint.java
  console/backend/src/main/java/org/frankframework/management/web/ConnectionOverview.java
  console/backend/src/main/java/org/frankframework/management/web/EnvironmentVariables.java
  console/backend/src/main/java/org/frankframework/management/web/ExecuteJdbcQuery.java
  console/backend/src/main/java/org/frankframework/management/web/FileViewer.java
  console/backend/src/main/java/org/frankframework/management/web/FrankApiBase.java
  console/backend/src/main/java/org/frankframework/management/web/IbisstoreSummary.java
  console/backend/src/main/java/org/frankframework/management/web/Init.java
  console/backend/src/main/java/org/frankframework/management/web/InlineMessageStoreOverview.java
  console/backend/src/main/java/org/frankframework/management/web/LiquibaseScript.java
  console/backend/src/main/java/org/frankframework/management/web/Logging.java
  console/backend/src/main/java/org/frankframework/management/web/Monitors.java
  console/backend/src/main/java/org/frankframework/management/web/RequestMessageBuilder.java
  console/backend/src/main/java/org/frankframework/management/web/Scheduler.java
  console/backend/src/main/java/org/frankframework/management/web/SecurityItems.java
  console/backend/src/main/java/org/frankframework/management/web/SendJmsMessage.java
  console/backend/src/main/java/org/frankframework/management/web/ServerStatistics.java
  console/backend/src/main/java/org/frankframework/management/web/TestPipeline.java
  console/backend/src/main/java/org/frankframework/management/web/TestServiceListener.java
  console/backend/src/main/java/org/frankframework/management/web/TransactionalStorage.java
  console/backend/src/main/java/org/frankframework/management/web/UpdateLoggingConfig.java
  console/backend/src/main/java/org/frankframework/management/web/Webservices.java
  console/backend/src/main/java/org/frankframework/util/ResponseUtils.java
  console/backend/src/main/java/org/frankframework/web/AllowAllIbisUserRoles.java
  console/backend/src/test/java/org/frankframework/management/web/ApiExceptionHandlerTest.java
  console/backend/src/test/java/org/frankframework/management/web/BrowseJdbcTableTest.java
  console/backend/src/test/java/org/frankframework/management/web/BrowseQueueTest.java
  console/backend/src/test/java/org/frankframework/management/web/ClassInfoTest.java
  console/backend/src/test/java/org/frankframework/management/web/ConfigurationStatusTest.java
  console/backend/src/test/java/org/frankframework/management/web/ConfigurationTest.java
  console/backend/src/test/java/org/frankframework/management/web/ConfigurationsEndpointTest.java
  console/backend/src/test/java/org/frankframework/management/web/ConnectionOverviewTest.java
  console/backend/src/test/java/org/frankframework/management/web/EnvironmentVariablesTest.java
  console/backend/src/test/java/org/frankframework/management/web/ExecuteJdbcQueryTest.java
  console/backend/src/test/java/org/frankframework/management/web/IbisstoreSummaryTest.java
  console/backend/src/test/java/org/frankframework/management/web/InitTest.java
  console/backend/src/test/java/org/frankframework/management/web/InlineMessageStoreOverviewTest.java
  console/backend/src/test/java/org/frankframework/management/web/MonitorsTest.java
  console/backend/src/test/java/org/frankframework/management/web/SchedulerTest.java
  console/backend/src/test/java/org/frankframework/management/web/SendJmsMessageTest.java
  console/backend/src/test/java/org/frankframework/management/web/ServerStatisticsTest.java
  console/backend/src/test/java/org/frankframework/management/web/TestController.java
  console/backend/src/test/java/org/frankframework/management/web/TestPipelineTest.java
  console/backend/src/test/java/org/frankframework/management/web/TestServiceListenerTest.java
  console/backend/src/test/java/org/frankframework/management/web/TransactionalStorageTest.java
  console/backend/src/test/java/org/frankframework/management/web/UpdateLoggingConfigTest.java
  console/backend/src/test/java/org/frankframework/management/web/WebservicesTest.java
  console/frontend/src/main/frontend/src/app/views/liquibase/liquibase.component.ts
  core/src/main/resources/AppConstants.properties
Labels: Frank Console

#7328 Fix ReplacerPipe
  core/src/main/java/org/frankframework/pipes/ReplacingInputStream.java
  core/src/main/java/org/frankframework/pipes/ReplacingVariablesInputStream.java
Labels: Backport, 8.2

#7334 Download all active configurations
  console/backend/src/main/java/org/frankframework/management/web/ServerStatistics.java
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage.component.html
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-manage/configurations-manage.component.ts
  core/src/main/java/org/frankframework/configuration/ConfigurationUtils.java
  core/src/main/java/org/frankframework/configuration/IbisContext.java
  core/src/main/java/org/frankframework/configuration/IbisManager.java
  core/src/main/java/org/frankframework/lifecycle/MessageEventListener.java
  core/src/main/java/org/frankframework/management/bus/endpoints/AdapterStatistics.java
  core/src/main/java/org/frankframework/management/bus/endpoints/BrowseMessageBrowsers.java
  core/src/main/java/org/frankframework/management/bus/endpoints/BusEndpointBase.java
  core/src/main/java/org/frankframework/management/bus/endpoints/ConfigManagement.java
  core/src/main/java/org/frankframework/management/bus/endpoints/DatabaseMigrator.java
  core/src/main/java/org/frankframework/management/bus/endpoints/HandleIbisManagerAction.java
  core/src/main/java/org/frankframework/unmanaged/DefaultIbisManager.java
  core/src/test/java/org/frankframework/management/bus/endpoints/TestDatabaseMigrator.java
  management-gateway/src/main/java/org/frankframework/management/bus/BusMessageUtils.java
Labels: Frank Console, Feature

#7320 Replace some LinkedLists with ArrayLists
  commons/src/main/java/org/frankframework/util/ClassUtils.java
  console/backend/src/main/java/org/frankframework/web/filters/CspFilter.java
  core/src/main/java/org/frankframework/align/XmlAligner.java
  core/src/main/java/org/frankframework/align/content/JsonElementContainer.java
  core/src/main/java/org/frankframework/configuration/ApplicationWarningsBase.java
  core/src/main/java/org/frankframework/configuration/ConfigurationUtils.java
  core/src/main/java/org/frankframework/core/PipeForwards.java
  core/src/main/java/org/frankframework/core/PipeLineExits.java
  core/src/main/java/org/frankframework/http/authentication/OAuthAccessTokenManager.java
  core/src/main/java/org/frankframework/http/authentication/OAuthPreferringAuthenticationStrategy.java
  core/src/main/java/org/frankframework/jdbc/migration/LiquibaseResourceAccessor.java
  core/src/main/java/org/frankframework/jta/TransactionConnectorCoordinator.java
  core/src/main/java/org/frankframework/ldap/LdapClient.java
  core/src/main/java/org/frankframework/management/bus/dto/StorageItemsDTO.java
  core/src/main/java/org/frankframework/management/bus/endpoints/ConfigManagement.java
  core/src/main/java/org/frankframework/management/bus/endpoints/ConnectionOverview.java
  core/src/main/java/org/frankframework/management/bus/endpoints/InlineStorage.java
  core/src/main/java/org/frankframework/management/bus/endpoints/SecurityItems.java
  core/src/main/java/org/frankframework/management/bus/endpoints/WebServices.java
  core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
  core/src/main/java/org/frankframework/monitoring/Trigger.java
  core/src/main/java/org/frankframework/pipes/JsonValidator.java
  core/src/main/java/org/frankframework/pipes/ReplacingInputStream.java
  core/src/main/java/org/frankframework/pipes/ReplacingVariablesInputStream.java
  core/src/main/java/org/frankframework/senders/MailSenderBase.java
  core/src/main/java/org/frankframework/senders/SenderSeries.java
  core/src/main/java/org/frankframework/util/XmlBuilder.java
  core/src/main/java/org/frankframework/validation/XercesXmlValidator.java
  core/src/test/java/org/frankframework/align/TestXmlSchema2JsonSchema.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/RoleToGroupMappingJndiRealm.java
  dbms/src/main/java/org/frankframework/dbms/Db2DbmsSupport.java
  filesystem/src/main/java/org/frankframework/util/FileHandler.java
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/queues/QueueWrapper.java
  tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
Labels: Technical Debt

#7353 Fix Parameters not shown in ladybug
  ladybug/src/main/java/org/frankframework/ibistesttool/Debugger.java
  ladybug/src/main/java/org/frankframework/ibistesttool/IbisDebugger.java
  ladybug/src/main/java/org/frankframework/ibistesttool/IbisDebuggerAdvice.java
  ladybug/src/main/resources/springIbisDebuggerAdvice.xml
Labels: Backport, 8.2

#7381 Fix copy paste error in AOP config
  ladybug/src/main/resources/springIbisDebuggerAdvice.xml
Labels: Backport, 8.2

#7382 Fix iDin equals check
  idin/src/main/java/org/frankframework/extensions/idin/IdinSender.java
  idin/src/test/java/org/frankframework/extensions/idin/IdinSenderTest.java
Labels: Backport, 8.2

#7385 Fix iDin equals check
  idin/src/main/java/nl/nn/adapterframework/extensions/idin/IdinSender.java
  idin/src/test/java/nl/nn/adapterframework/extensions/idin/IdinSenderTest.java
  idin/src/test/resources/expected/simpleRequestResponse.xml
Labels: Backport, 7.9

#7384 Fix iDin equals check
  idin/src/main/java/org/frankframework/extensions/idin/IdinSender.java
  idin/src/test/java/org/frankframework/extensions/idin/IdinSenderTest.java
  idin/src/test/resources/expected/simpleRequestResponse.xml
Labels: Backport, 8.0

#7387 Prevent configurations messages from turning red incorrectly
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/app.service.ts
Labels: Frank Console, Backport, 8.2

#7411 Subscribe to websocket channels based on selected cluster member
  console/backend/src/main/java/org/frankframework/console/controllers/socket/EventHandler.java
  console/frontend/src/main/frontend/src/app/app.component.html
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/app.service.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.ts
Labels: Frank Console
