Repository frankframework/frankframework, pull requests merged in 2024-07, with the labels that each got.

#7103 Some minor code cleanups
  core/src/main/java/org/frankframework/jms/IbisMessageListenerContainer.java
  core/src/main/java/org/frankframework/senders/IsolatedServiceCaller.java
Labels: Technical Debt

#7085 Remove frontend-maven-plugin from console-frontend pom
  CONTRIBUTING.md
  TESTING_WITH_IAF-TEST.md
  console/frontend/pom.xml
Labels: Frank Console

#7111 Remove dead code from MessageOutputStream
  core/src/main/java/org/frankframework/jdbc/DirectQuerySender.java
  core/src/main/java/org/frankframework/jdbc/FixedQuerySender.java
  core/src/main/java/org/frankframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/org/frankframework/jdbc/ResultSet2FileSender.java
  core/src/main/java/org/frankframework/jdbc/XmlQuerySender.java
  core/src/main/java/org/frankframework/management/bus/endpoints/IbisstoreSummary.java
  core/src/main/java/org/frankframework/mongodb/MongoDbSender.java
  core/src/main/java/org/frankframework/stream/ContentHandlerOutputStream.java
  core/src/main/java/org/frankframework/stream/MessageOutputStream.java
  core/src/main/java/org/frankframework/stream/MessageOutputStreamCap.java
  core/src/test/java/org/frankframework/stream/MessageOutputStreamTest.java
  core/src/test/java/org/frankframework/stream/MessageStreamCapTest.java
Labels: Technical Debt

#7114 Minor cleanup in FileSystem tests
  filesystem/src/test/java/org/frankframework/filesystem/FileSystemListenerExtraTest.java
  filesystem/src/test/java/org/frankframework/filesystem/FileSystemUtilsTest.java
  filesystem/src/test/java/org/frankframework/filesystem/LocalFileSystemListenerTest.java
  filesystem/src/test/java/org/frankframework/filesystem/mock/MockFileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/mock/MockFileSystemPipeTest.java
  filesystem/src/test/java/org/frankframework/filesystem/mock/MockFileSystemSenderTest.java
  filesystem/src/test/java/org/frankframework/filesystem/mock/MockFileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/mock/MockFileSystemUtilTest.java
Labels: Technical Debt

#7113 Remove the interface IAdapter, use Adapter instead everywhere
  core/src/main/java/org/frankframework/configuration/Configuration.java
  core/src/main/java/org/frankframework/configuration/ConfigurationWarnings.java
  core/src/main/java/org/frankframework/configuration/digester/DigesterRuleBase.java
  core/src/main/java/org/frankframework/core/Adapter.java
  core/src/main/java/org/frankframework/core/IAdapter.java
  core/src/main/java/org/frankframework/http/openapi/OpenApiGenerator.java
  core/src/main/java/org/frankframework/jdbc/DirectQuerySender.java
  core/src/main/java/org/frankframework/jmx/JmxNamingStrategy.java
  core/src/main/java/org/frankframework/management/bus/endpoints/CreateScheduledJob.java
  core/src/main/java/org/frankframework/management/bus/endpoints/HealthCheck.java
  core/src/main/java/org/frankframework/management/bus/endpoints/TestPipeline.java
  core/src/main/java/org/frankframework/management/bus/endpoints/WebServices.java
  core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
  core/src/main/java/org/frankframework/processors/CorePipeLineProcessor.java
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/main/java/org/frankframework/scheduler/ConfiguredJob.java
  core/src/main/java/org/frankframework/scheduler/job/CleanupDatabaseJob.java
  core/src/main/java/org/frankframework/soap/WsdlGeneratorUtils.java
  core/src/main/java/org/frankframework/util/LogUtil.java
  core/src/main/java/org/frankframework/util/flow/FlowDiagramManager.java
  core/src/test/java/org/frankframework/jmx/JmxNamingStrategyTest.java
  ladybug/src/main/java/org/frankframework/ibistesttool/Debugger.java
  ladybug/src/main/java/org/frankframework/ibistesttool/filter/TibetView.java
  ladybug/src/main/java/org/frankframework/ibistesttool/tibet2/Debugger.java
  ladybug/src/main/java/org/frankframework/ibistesttool/tibet2/Storage.java
  nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfListener.java
  test/src/main/resources/DeploymentSpecifics.properties
Labels: Technical Debt

#7121 Display logout button in console when properly logged in
  console/frontend/src/main/frontend/src/app/app.component.html
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.ts
  console/frontend/src/main/frontend/src/app/http-interceptors/auth-interceptor.ts
  console/frontend/src/main/frontend/src/app/services/auth.service.ts
  console/frontend/src/main/frontend/src/app/views/login/login.component.html
  console/frontend/src/main/frontend/src/app/views/login/login.component.ts
Labels: Frank Console

#7129 Fix sessionkey types for both console & core
  console/backend/src/test/java/org/frankframework/management/web/TestPipelineTest.java
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/TestPipeline.java
  core/src/test/java/org/frankframework/management/bus/endpoints/TestPipelineTest.java
Labels: Bug, Frank Console

#7151 Fix console message store endpoints
  console/backend/src/main/java/org/frankframework/management/web/TransactionalStorage.java
  console/backend/src/main/java/org/frankframework/management/web/configuration/WebConfiguration.java
  console/backend/src/test/java/org/frankframework/management/web/TransactionalStorageTest.java
Labels: Frank Console

#7152 Fix console message store endpoints
  console/backend/src/main/java/org/frankframework/management/web/TransactionalStorage.java
  console/backend/src/main/java/org/frankframework/management/web/configuration/WebConfiguration.java
  console/backend/src/test/java/org/frankframework/management/web/TransactionalStorageTest.java
Labels: Frank Console, Backport, 8.2

#7157 Add method ParameterList#hasParameter and apply where relevant.
  akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageSender.java
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisSender.java
  core/src/main/java/org/frankframework/compression/ZipWriter.java
  core/src/main/java/org/frankframework/jdbc/MessageStoreSender.java
  core/src/main/java/org/frankframework/jms/JmsSender.java
  core/src/main/java/org/frankframework/ldap/LdapChallengePipe.java
  core/src/main/java/org/frankframework/ldap/LdapSender.java
  core/src/main/java/org/frankframework/mongodb/MongoDbSender.java
  core/src/main/java/org/frankframework/parameters/ParameterList.java
  core/src/main/java/org/frankframework/pipes/CompareIntegerPipe.java
  core/src/main/java/org/frankframework/pipes/CompareStringPipe.java
  core/src/main/java/org/frankframework/pipes/JwtPipe.java
  core/src/main/java/org/frankframework/pipes/SignaturePipe.java
  core/src/main/java/org/frankframework/senders/LogSender.java
  core/src/main/java/org/frankframework/senders/SenderWithParametersBase.java
  core/src/test/java/org/frankframework/parameters/ParameterListTest.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemActor.java
  nn-specials/src/main/java/org/frankframework/extensions/api/ApiSoapWrapperPipe.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsSender.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbSoapWrapperPipe.java
  nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfWrapperPipe.java
  sap/src/main/java/org/frankframework/extensions/sap/jco3/SapSenderBase.java
  sap/src/main/java/org/frankframework/extensions/sap/jco3/SapSenderImpl.java
  tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
  tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java
Labels: Technical Debt

#7133 Fix sessionkey types for both console & core
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/TestPipeline.java
  core/src/test/java/org/frankframework/management/bus/endpoints/TestPipelineTest.java
Labels: Frank Console, Backport, 8.1

#7135 Fix sessionkey types for both console & core
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/TestPipeline.java
  core/src/test/java/org/frankframework/management/bus/endpoints/TestPipelineTest.java
Labels: Frank Console, Backport, 8.0

#6889 Add nightly release workflow
  .github/workflows/nightly-release.yml
Labels: 7.9

#7163 LCM XmlUnit and MSAL4J
  core/pom.xml
Labels: 8.0

#7164 LCM XmlUnit and MSAL4J
  core/pom.xml
  filesystem/pom.xml
Labels: 8.1

#7169 Fix message browser selected messages with non-numbers
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
Labels: Frank Console, Backport, 8.0

#7166 Fix message browser selected messages with non-numbers
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
Labels: Bug, Frank Console

#7162 LCM MSAL4J
  core/pom.xml
Labels: 7.9

#7170 Fix message browser selected messages with non-numbers
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
Labels: Frank Console, Backport, 7.9

#7167 Fix message browser selected messages with non-numbers
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
Labels: Frank Console, Backport, 8.2

#7174 Test a pipeline clearing configuration also clears adapter
  console/frontend/src/main/frontend/.vscode/launch.json
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
Labels: Frank Console

#7190 Bump CXF
  pom.xml
Labels: Dependencies, 8.0

#7191 Bump CXF and Tomcat (embedded)
  pom.xml
Labels: Dependencies, 8.1

#7192 Bump msal
  core/pom.xml
Labels: Dependencies, 7.9

#7197 Speed up startup and shutdown of configurations
  core/src/main/java/org/frankframework/configuration/AdapterManager.java
  core/src/main/java/org/frankframework/core/Adapter.java
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/main/java/org/frankframework/senders/IbisLocalSender.java
  core/src/test/java/org/frankframework/receivers/JavaListenerTest.java
Labels: Technical Debt

#7199 No redelivery-delay when final max retry count reached
  core/src/main/java/org/frankframework/core/IKnowsDeliveryCount.java
  core/src/main/java/org/frankframework/core/IRedeliveringListener.java
  core/src/main/java/org/frankframework/jms/JmsListenerBase.java
  core/src/main/java/org/frankframework/receivers/Receiver.java
Labels: Technical Debt

#7208 Log Mime Multipart exception in ApiListenerServlet (#7205)
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
Labels: Backport, 8.2

#7209 Log Mime Multipart exception in ApiListenerServlet
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
Labels: Backport, 8.1

#7210 Log Mime Multipart exception in ApiListenerServlet
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
Labels: Backport, 8.0

#7213 Message and Session arguments passed to a Sender should never be NULL.
  akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageSender.java
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisSender.java
  core/src/main/java/org/frankframework/collection/CollectorSenderBase.java
  core/src/main/java/org/frankframework/compression/ZipWriterSender.java
  core/src/main/java/org/frankframework/core/ISender.java
  core/src/main/java/org/frankframework/http/HttpSenderBase.java
  core/src/main/java/org/frankframework/jdbc/JdbcSenderBase.java
  core/src/main/java/org/frankframework/jdbc/MessageStoreSender.java
  core/src/main/java/org/frankframework/jms/JmsSender.java
  core/src/main/java/org/frankframework/jms/XmlJmsBrowserSender.java
  core/src/main/java/org/frankframework/ldap/LdapSender.java
  core/src/main/java/org/frankframework/mongodb/MongoDbSender.java
  core/src/main/java/org/frankframework/scheduler/SchedulerSender.java
  core/src/main/java/org/frankframework/senders/BlockEnabledSenderBase.java
  core/src/main/java/org/frankframework/senders/CommandSender.java
  core/src/main/java/org/frankframework/senders/DelaySender.java
  core/src/main/java/org/frankframework/senders/EchoSender.java
  core/src/main/java/org/frankframework/senders/FixedResultSender.java
  core/src/main/java/org/frankframework/senders/FrankSender.java
  core/src/main/java/org/frankframework/senders/IbisJavaSender.java
  core/src/main/java/org/frankframework/senders/IbisLocalSender.java
  core/src/main/java/org/frankframework/senders/JavascriptSender.java
  core/src/main/java/org/frankframework/senders/LogSender.java
  core/src/main/java/org/frankframework/senders/MailSenderBase.java
  core/src/main/java/org/frankframework/senders/ReloadSender.java
  core/src/main/java/org/frankframework/senders/SenderWrapperBase.java
  core/src/main/java/org/frankframework/senders/ShadowSender.java
  core/src/main/java/org/frankframework/senders/XmlValidatorSender.java
  core/src/main/java/org/frankframework/senders/XsltSender.java
  core/src/test/java/org/frankframework/jdbc/ResultSetIteratingPipeTest.java
  core/src/test/java/org/frankframework/monitoring/MessageCapturingEchoSender.java
  core/src/test/java/org/frankframework/pipes/ForEachChildElementPipeTest.java
  core/src/test/java/org/frankframework/pipes/IteratingPipeTestBase.java
  core/src/test/java/org/frankframework/pipes/MessageSendingPipeTest.java
  core/src/test/java/org/frankframework/processors/InputOutputSenderWrapperProcessorTest.java
  core/src/test/java/org/frankframework/receivers/DummySender.java
  core/src/test/java/org/frankframework/senders/JavascriptSenderCallbackTest.java
  core/src/test/java/org/frankframework/senders/MailSenderTest.java
  core/src/test/java/org/frankframework/senders/ParallelSendersTest.java
  core/src/test/java/org/frankframework/senders/ReconnectSenderWrapperTest.java
  core/src/test/java/org/frankframework/senders/ShadowSenderTest.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemSender.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemSenderWithAttachments.java
  filesystem/src/main/java/org/frankframework/http/WebServiceNtlmSender.java
  filesystem/src/main/java/org/frankframework/senders/FileSender.java
  idin/src/main/java/org/frankframework/extensions/idin/IdinSender.java
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/queues/QueueCreator.java
  larva/src/main/java/org/frankframework/larva/queues/QueueWrapper.java
  messaging/src/main/java/org/frankframework/extensions/kafka/KafkaSender.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttSender.java
  nn-specials/src/main/java/org/frankframework/extensions/afm/Afm2EdiFactSender.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsSender.java
  nn-specials/src/main/java/org/frankframework/extensions/svn/ScanTibcoSolutionPipe.java
  nn-specials/src/main/java/org/frankframework/extensions/svn/SvnUtils.java
  nn-specials/src/main/java/org/frankframework/extensions/xfb/XfbSender.java
  nn-specials/src/main/java/org/frankframework/xcom/XComSender.java
  sap/src/main/java/org/frankframework/extensions/sap/jco3/IdocSenderImpl.java
  sap/src/main/java/org/frankframework/extensions/sap/jco3/SapSenderImpl.java
  tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
Labels: Technical Debt
