Repository frankframework/frankframework, pull requests merged in 2024-10, with the labels that each got.

#7586 Fix minimum page height & hide scrollbars on testing & custom views
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-custom-view/iframe-custom-view.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug-legacy/iframe-ladybug-legacy.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-ladybug/iframe-ladybug.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe-larva/iframe-larva.component.ts
  console/frontend/src/main/frontend/src/app/views/iframe/iframe.base.ts
  console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css
  console/frontend/src/main/frontend/src/assets/css/style.css
Labels: Frank Console

#7619 Update Spring, Tomcat and Protobuf dependencies
  pom.xml
Labels: 8.2

#7618 Update Spring, Tomcat and Protobuf dependencies
  credentialProvider/pom.xml
  pom.xml
Labels: 8.0

#7617 Update Spring, Tomcat and Protobuf dependencies
  credentialProvider/pom.xml
  pom.xml
Labels: 8.1

#7616 Update Spring, Tomcat and Protobuf dependencies
  credentialProvider/pom.xml
  pom.xml
Labels: 7.9

#7610 Fix sap idoc flow (#7589)
  sap/src/main/java/org/frankframework/extensions/sap/jco3/SapListenerImpl.java
Labels: Backport, 8.0

#7641 Show WSS on Test-ServiceListener console page
  core/src/main/java/org/frankframework/http/WebServiceListener.java
Labels: 8.0

#7640 Show WSS on Test-ServiceListener console page
  core/src/main/java/nl/nn/adapterframework/http/WebServiceListener.java
Labels: 7.9

#7660 Show warning popup alert when websocket & fallback don't work
  console/frontend/src/main/frontend/src/app/services/websocket.service.ts
Labels: Frank Console

#7653 Some code cleanups in XSD and related classes
  core/src/main/java/org/frankframework/validation/IXSD.java
  core/src/main/java/org/frankframework/validation/XSD.java
  core/src/main/java/org/frankframework/validation/xsd/ResourceXsd.java
  core/src/main/java/org/frankframework/validation/xsd/WsdlXsd.java
  core/src/test/java/org/frankframework/soap/WsdlTest.java
Labels: Technical Debt

#7662 Minor startup performance improvement by caching results of XSD compare
  core/src/main/java/org/frankframework/validation/IXSD.java
  core/src/main/java/org/frankframework/validation/XSD.java
  core/src/main/java/org/frankframework/validation/xsd/ResourceXsd.java
  core/src/main/java/org/frankframework/validation/xsd/StringXsd.java
  core/src/main/java/org/frankframework/validation/xsd/WsdlXsd.java
Labels: Technical Debt

#7669 Minor optimisations
  commons/src/main/java/org/frankframework/util/StringUtil.java
  core/src/main/java/org/frankframework/core/PipeLine.java
  core/src/main/java/org/frankframework/jdbc/datasource/FrankResources.java
  core/src/test/java/org/frankframework/testutil/junit/JUnitDatabaseExtension.java
  larva/src/main/java/org/frankframework/larva/ScenarioRunner.java
Labels: Technical Debt

#7670 Code cleanup in SchemaUtils and XSD
  core/src/main/java/org/frankframework/pipes/XmlValidator.java
  core/src/main/java/org/frankframework/soap/WsdlGenerator.java
  core/src/main/java/org/frankframework/util/XmlUtils.java
  core/src/main/java/org/frankframework/validation/SchemaUtils.java
  core/src/main/java/org/frankframework/validation/XSD.java
  core/src/main/java/org/frankframework/validation/xsd/StringXsd.java
  core/src/test/java/org/frankframework/pipes/XmlValidatorPipelineTest.java
  core/src/test/java/org/frankframework/validation/ValidatorTestBase.java
  core/src/test/java/org/frankframework/validation/XSDTest.java
  core/src/test/resources/Validation/Basic/xsd/A_correct.xsd
  core/src/test/resources/Validation/Basic/xsd/A_correct.xsd-after-adding-namespace.xsd
  core/src/test/resources/Validation/Basic/xsd/A_without_targetnamespace.xsd-after-adding-namespace.xsd
  core/src/test/resources/XSDTest/XsdMergingTest/imported_schema1.xsd
  core/src/test/resources/XSDTest/XsdMergingTest/imported_schema2.xsd
  core/src/test/resources/XSDTest/XsdMergingTest/merged_xsd_expected_output.xsd
  core/src/test/resources/XSDTest/XsdMergingTest/root_schema1.xsd
  core/src/test/resources/XSDTest/XsdMergingTest/root_schema2.xsd
  test/src/test/testtool/Validators/Schema/SoapValidator.wsdl
  test/src/test/testtool/WsdlGenerator/scenario01/out.wsdl.xml
  test/src/test/testtool/WsdlGenerator/scenario02/out.wsdl.xml
  test/src/test/testtool/WsdlGenerator/scenario03/out.wsdl.xml
  test/src/test/testtool/WsdlGenerator/scenario04/out.wsdl.xml
  test/src/test/testtool/WsdlGeneratorPipe/01/out.xml
  test/src/test/testtool/WsdlGeneratorPipe/02/out.xml
  test/src/test/testtool/WsdlGeneratorPipe/03/out.xml
Labels: Technical Debt

#7742 Fix monitor trigger url & missing 'Security Items' page title
  console/frontend/src/main/frontend/src/app/app-routing.module.ts
  console/frontend/src/main/frontend/src/app/services/websocket.service.ts
  console/frontend/src/main/frontend/src/app/views/monitors/monitors.service.ts
Labels: FF! Console, Backport, 8.3

#7741 Fix monitor trigger url & missing 'Security Items' page title
  console/frontend/src/main/frontend/src/app/app-routing.module.ts
  console/frontend/src/main/frontend/src/app/services/websocket.service.ts
  console/frontend/src/main/frontend/src/app/views/monitors/monitors.service.ts
Labels: FF! Console

#7751 Consolidate Ladybug and Console authentication properties
  core/src/main/java/org/frankframework/lifecycle/ServletManager.java
  core/src/main/resources/AppConstants.properties
  core/src/main/resources/StageSpecifics_LOC.properties
  core/src/test/java/org/frankframework/receivers/ReceiverTest.java
  core/src/test/java/org/frankframework/testutil/TestAssertions.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/FileSystemCredentialFactory.java
  ladybug/common/src/main/java/org/frankframework/ladybug/config/LadybugSecurityChainConfigurer.java
  security/src/main/java/org/frankframework/lifecycle/servlets/ServletConfiguration.java
  security/src/test/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorTest.java
  security/src/test/java/org/frankframework/lifecycle/servlets/ServletConfigurationTest.java
  security/src/test/java/org/frankframework/lifecycle/servlets/YmlFileAuthenticatorTest.java
Labels: 8.3

#7726 Minor code improvement
  core/src/main/java/org/frankframework/validation/SchemaUtils.java
  core/src/main/java/org/frankframework/validation/XSD.java
Labels: Technical Debt

#7760 Use a ThreadLocal for the micrometer http interceptor (#7717)
  core/src/main/java/org/frankframework/http/MicrometerHttpClientInterceptor.java
Labels: 8.3

#7783 Change generated XML for monitors to the new style
  core/src/main/java/org/frankframework/monitoring/Monitor.java
  core/src/main/java/org/frankframework/monitoring/Trigger.java
  core/src/test/resources/Management/Monitoring/getManagerToXML.xml
  core/src/test/resources/Management/Monitoring/getMonitor.xml
  core/src/test/resources/Management/Monitoring/getMonitors.xml
Labels: 8.3

#7814 Remove example role-mapping files and fix application security defaults
  RELEASES.md
  commons/src/main/java/org/frankframework/util/ClassUtils.java
  console/backend/src/main/java/org/frankframework/console/configuration/SecurityChainConfigurer.java
  core/src/main/resources/AppConstants.properties
  core/src/main/resources/StageSpecifics_LOC.properties
  core/src/test/java/org/frankframework/lifecycle/ServletManagerTest.java
  ladybug/common/src/main/java/org/frankframework/ladybug/config/LadybugSecurityChainConfigurer.java
  security/pom.xml
  security/src/main/java/org/frankframework/lifecycle/servlets/AuthenticationType.java
  security/src/main/java/org/frankframework/lifecycle/servlets/AuthenticatorUtils.java
  security/src/main/java/org/frankframework/lifecycle/servlets/SecuritySettings.java
  security/src/main/resources/oauth-role-mapping.properties
  security/src/test/java/org/frankframework/lifecycle/servlets/AuthenticationTypeTest.java
  security/src/test/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorTest.java
  security/src/test/java/org/frankframework/lifecycle/servlets/ServletConfigurationTest.java
  security/src/test/resources/ldap-role-mapping.properties
  security/src/test/resources/log4j2.xml
Labels: 8.3

#7817 Fix issue where the name attribute is not being substituted
  core/src/main/java/org/frankframework/configuration/digester/DigesterRuleBase.java
  core/src/main/java/org/frankframework/configuration/digester/ValidateAttributeRule.java
  core/src/main/java/org/frankframework/core/PipeLine.java
  core/src/main/java/org/frankframework/xml/NamespaceRemovingAttributesWrapper.java
  core/src/test/java/org/frankframework/configuration/digester/ValidateAttributeRuleTest.java
  core/src/test/java/org/frankframework/xml/AttributePropertyResolverTest.java
  core/src/test/resources/Entities/AttributePropertyResolver/data.properties
  core/src/test/resources/Entities/AttributePropertyResolver/property-resolving-result.xml
  core/src/test/resources/Entities/AttributePropertyResolver/property-resolving.xml
  test/src/main/configurations/HTTP/ConfigurationApiListener.xml
  test/src/main/configurations/HTTP/DeploymentSpecifics.properties
Labels: 8.3

#7834 Revert monaco-editor update to 0.52.0
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/package.json
Labels: Bug, FF! Console

#7822 Minor refactoring of interface hierarchy to remove some duplication
  core/src/main/java/org/frankframework/core/IPortConnectedListener.java
  core/src/main/java/org/frankframework/http/rest/ApiListener.java
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/main/java/org/frankframework/receivers/ReceiverAware.java
Labels: Technical Debt
