Repository frankframework/frankframework, pull requests merged in 2024-02, with the labels that each got.

#6192 Samba2FileSystem: always close diskShare, sessions, Samba client, con…
  core/src/main/java/nl/nn/adapterframework/filesystem/Samba2FileSystem.java
  core/src/test/java/nl/nn/adapterframework/filesystem/smb/Samba2FileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/smb/Samba2PipeTest.java
Labels: FileSystem, 7.9

#6191 Samba2FileSystem: always close diskShare, sessions, Samba client, con…
  core/src/main/java/org/frankframework/filesystem/Samba2FileSystem.java
  core/src/test/java/org/frankframework/filesystem/smb/Samba2FileSystemTest.java
  core/src/test/java/org/frankframework/filesystem/smb/Samba2PipeTest.java
Labels: 8.0

#6194 Improve reliability of ParallelSender and ShadowSender
  core/src/main/java/nl/nn/adapterframework/senders/ParallelSenders.java
  core/src/main/java/nl/nn/adapterframework/senders/ShadowSender.java
  core/src/test/java/nl/nn/adapterframework/senders/ParallelSendersTest.java
  core/src/test/java/nl/nn/adapterframework/senders/ShadowSenderTest.java
  core/src/test/resources/Senders/ParallelSenders/test10SubSendersNonRepeatableMessage.txt
Labels: 7.9

#6202 Make MermaidFlowGenerator more resilient to class loading errors
  core/src/main/java/org/frankframework/util/flow/MermaidFlowGenerator.java
  core/src/test/java/org/frankframework/configuration/digester/MapPropertyDescriptorsTest.java
  core/src/test/java/org/frankframework/configuration/digester/TestAnnotationUtils.java
  core/src/test/java/org/frankframework/util/flow/UnloadableClass.java
Labels: 8.0

#6209 Change custom build ActiveMQ ci-image to the Apache pre-build `activemq-classic` image
  docker/activemq.yml
  docker/jboss.yml
Labels: Backport, 8.0

#6208 test: remove unnecesary entrypoint from compose-file
  docker/activemq.yml
Labels: Backport, 7.8

#6206 Change custom build ActiveMQ ci-image to the Apache pre-build `activemq-classic` image
  docker/activemq.yml
Labels: Backport, 7.9

#6224 Version pin JUnit to 5.10.1
  pom.xml
Labels: Dependencies

#6228 Version pin JUnit to 5.10.1
  pom.xml
Labels: 7.9

#6229 Version pin JUnit to 5.10.1
  pom.xml
Labels: 7.8

#6241 Fix bad package name in Spring context
  core/src/main/resources/springTOMCAT.xml
Labels: 8.0

#6222 Larva improvements
  larva/src/main/java/org/frankframework/extensions/test/IbisTester.java
  larva/src/main/java/org/frankframework/pipes/LarvaPipe.java
  larva/src/main/java/org/frankframework/testtool/FileListener.java
  larva/src/main/java/org/frankframework/testtool/LarvaServlet.java
  larva/src/main/java/org/frankframework/testtool/ScenarioRunner.java
  larva/src/main/java/org/frankframework/testtool/TestConfig.java
  larva/src/main/java/org/frankframework/testtool/TestTool.java
  larva/src/main/java/org/frankframework/testtool/queues/QueueCreator.java
  test/src/test/testtool/WebServiceListenerSender/scenario11b/init.xml
  test/src/test/testtool/WebServiceListenerSender/scenario11c/init.xml
  test/src/test/testtool/WebServiceListenerSender/scenario11d/init.xml
Labels: Larva

#6242 Remove JdbcTestBase
  core/src/test/java/org/frankframework/http/cxf/SoapProviderTest.java
  core/src/test/java/org/frankframework/http/rest/OpenApiTest.java
  core/src/test/java/org/frankframework/jdbc/JdbcTestBase.java
  core/src/test/java/org/frankframework/jdbc/TransactionManagerTest.java
  core/src/test/java/org/frankframework/jdbc/TransactionManagerTestBase.java
  core/src/test/java/org/frankframework/jdbc/migration/LiquibaseResourceAccessorTest.java
  core/src/test/java/org/frankframework/jta/StatusRecordingTransactionManagerImplementationTest.java
  core/src/test/java/org/frankframework/jta/StatusRecordingTransactionManagerTest.java
  core/src/test/java/org/frankframework/jta/StatusRecordingTransactionManagerTestBase.java
  core/src/test/java/org/frankframework/jta/TransactionConnectorTest.java
  core/src/test/java/org/frankframework/jta/btm/TestSelfRecoveringBTMDiskJournal.java
  core/src/test/java/org/frankframework/testutil/junit/DatabaseTest.java
  core/src/test/java/org/frankframework/testutil/junit/DatabaseTestInvocationContext.java
  core/src/test/java/org/frankframework/testutil/junit/JUnitLiquibaseExtension.java
  core/src/test/java/org/frankframework/testutil/junit/WithLiquibase.java
  core/src/test/java/org/frankframework/testutil/threading/IsolatedThread.java
  core/src/test/java/org/frankframework/testutil/threading/RunInThreadRule.java
  core/src/test/java/org/frankframework/testutil/threading/RunTestInThread.java
  pom.xml
Labels: Technical Debt

#6256 Improve visibility of error message summary & counters on status page
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.scss
Labels: Frank Console

#6257 Forwardport 8.0 of Improve visibility of error message summary on status page
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.scss
Labels: Frank Console

#6258 Forwardport of Improve visibility of error message counters on status page
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.scss
Labels: Frank Console

#6255 Remove maven Jetty plugin
  CONTRIBUTING.md
  RELEASES.md
  core/src/main/java/org/frankframework/core/JndiContextPrefixFactory.java
  core/src/main/java/org/frankframework/jms/JmsMessagingSourceFactory.java
  core/src/main/java/org/frankframework/lifecycle/FrankEnvironmentInitializer.java
  core/src/main/resources/springTIBCOAMX.xml
  example/pom.xml
  example/src/main/resources/StageSpecifics_LOC.properties
  test/src/main/resources/StageSpecifics_LOC.properties
  webapp/src/main/webapp/index.html
Labels: Technical Debt

#6265 Pad authAlias and sharedSecret parameter when jwtAllowWeakSecrets is true
  core/src/main/java/org/frankframework/pipes/AbstractPipe.java
  core/src/main/java/org/frankframework/pipes/JwtPipe.java
  core/src/main/java/org/frankframework/util/CredentialFactory.java
  core/src/test/java/org/frankframework/pipes/JwtPipeTest.java
  credentialProvider/pom.xml
  credentialProvider/src/main/java/org/frankframework/credentialprovider/Credentials.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/ICredentialFactory.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/ICredentials.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/MapCredentials.java
Labels: 8.0

#6266 Pad authAlias and sharedSecret parameter when jwtAllowWeakSecrets is true
  core/src/main/java/nl/nn/adapterframework/pipes/AbstractPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/JwtPipe.java
  core/src/main/java/nl/nn/adapterframework/util/CredentialFactory.java
  core/src/test/java/nl/nn/adapterframework/pipes/JwtPipeTest.java
  credentialProvider/pom.xml
  credentialProvider/src/main/java/nl/nn/credentialprovider/Credentials.java
  credentialProvider/src/main/java/nl/nn/credentialprovider/ICredentialFactory.java
  credentialProvider/src/main/java/nl/nn/credentialprovider/ICredentials.java
  credentialProvider/src/main/java/nl/nn/credentialprovider/MapCredentials.java
Labels: 7.9

#6172 Make LogContextPipe not throw when it has an error during execution
  core/src/main/java/nl/nn/adapterframework/core/ParameterException.java
  core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
  core/src/main/java/nl/nn/adapterframework/parameters/ParameterList.java
  core/src/main/java/nl/nn/adapterframework/parameters/ParameterValue.java
  core/src/main/java/nl/nn/adapterframework/pipes/LogContextPipe.java
  core/src/main/java/nl/nn/adapterframework/util/FileUtils.java
  core/src/test/java/nl/nn/adapterframework/parameters/ParameterTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/LogContextPipeTest.java
Labels: 7.9

#6285 Convert last classes from JUnit4 to JUnit5; remove JUnit 4/Vintage deps
  core/pom.xml
  core/src/test/java/org/frankframework/configuration/classloaders/WebAppClassLoaderTest.java
  core/src/test/java/org/frankframework/core/ConfiguredTestBase.java
  core/src/test/java/org/frankframework/http/authentication/HttpSenderAuthenticationTest.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
  core/src/test/java/org/frankframework/jdbc/JdbcTransactionalStorageTest.java
  core/src/test/java/org/frankframework/jdbc/transformer/ToCsvTest.java
  core/src/test/java/org/frankframework/jdbc/transformer/ToJsonTest.java
  core/src/test/java/org/frankframework/jdbc/transformer/ToListOfMapsTest.java
  core/src/test/java/org/frankframework/management/bus/BusExceptionTest.java
  core/src/test/java/org/frankframework/management/bus/TestBusAuthorisation.java
  core/src/test/java/org/frankframework/management/bus/TestSpringBusExceptionHandling.java
  core/src/test/java/org/frankframework/management/bus/endpoints/TestSecurityItems.java
  core/src/test/java/org/frankframework/pipes/ForwardHandlingTest.java
  core/src/test/java/org/frankframework/pipes/StreamPipeTest.java
  core/src/test/java/org/frankframework/pipes/XmlValidatorPipelineTest.java
  core/src/test/java/org/frankframework/soap/WsdlTest.java
  core/src/test/java/org/frankframework/testutil/SpringRootInitializer.java
  core/src/test/java/org/frankframework/util/FileHandlerTest.java
  core/src/test/java/org/frankframework/util/FileHandlerTestBase.java
  core/src/test/java/org/frankframework/util/MessageUtilsCharsetDetectionTest.java
  core/src/test/java/org/frankframework/validation/AbstractXmlValidatorTestBase.java
  core/src/test/java/org/frankframework/validation/AllXmlValidatorTest.java
  core/src/test/java/org/frankframework/validation/Json2XmlValidatorTest.java
  core/src/test/java/org/frankframework/validation/SingleJson2XmlValidatorTest.java
  core/src/test/java/org/frankframework/validation/SingleXmlValidatorTest.java
  core/src/test/java/org/frankframework/validation/ValidatorTestBase.java
  core/src/test/java/org/frankframework/validation/XmlValidatorExtraTest.java
  core/src/test/java/org/frankframework/validation/XmlValidatorTest.java
  core/src/test/java/org/frankframework/validation/XmlValidatorTestBase.java
  core/src/test/java/org/frankframework/xslt/ParallelXsltTest.java
  core/src/test/java/org/frankframework/xslt/XsltErrorTestBase.java
  core/src/test/java/org/frankframework/xslt/XsltTestBase.java
  idin/pom.xml
  idin/src/test/java/org/frankframework/extensions/idin/IdinSenderTest.java
  messaging/pom.xml
  nn-specials/src/test/java/org/frankframework/extensions/fxf/FxfWrapperPipeTest.java
  pom.xml
  security/src/test/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorTest.java
Labels: Technical Debt

#6296 Updated pooled-jms dependency for 7.9
  core/pom.xml
Labels: Dependencies, 7.9

#6299 Make LogContextPipe not throw when it has an error during execution
  core/src/main/java/org/frankframework/core/ParameterException.java
  core/src/main/java/org/frankframework/parameters/Parameter.java
  core/src/main/java/org/frankframework/parameters/ParameterList.java
  core/src/main/java/org/frankframework/parameters/ParameterValue.java
  core/src/main/java/org/frankframework/pipes/LogContextPipe.java
  core/src/main/java/org/frankframework/util/FileUtils.java
  core/src/test/java/org/frankframework/parameters/ParameterTest.java
  core/src/test/java/org/frankframework/pipes/LogContextPipeTest.java
Labels: 8.0

#6309 Don't catch all exceptions but rethrow (#6284)
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/test/java/org/frankframework/receivers/MockListenerBase.java
  core/src/test/java/org/frankframework/receivers/MockPullingListener.java
  core/src/test/java/org/frankframework/receivers/MockPushingListener.java
  core/src/test/java/org/frankframework/receivers/TestReceiverOnError.java
Labels: Backport, 8.0

#6310 Don't catch all exceptions but rethrow (#6284)
  core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationUtils.java
  core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/receivers/PullingListenerContainer.java
  core/src/main/java/nl/nn/adapterframework/receivers/Receiver.java
  core/src/test/java/nl/nn/adapterframework/receivers/MockListenerBase.java
  core/src/test/java/nl/nn/adapterframework/receivers/MockPullingListener.java
  core/src/test/java/nl/nn/adapterframework/receivers/MockPushingListener.java
  core/src/test/java/nl/nn/adapterframework/receivers/TestReceiverOnError.java
Labels: Backport, 7.9

#6220 Replace FileViewerServlet for 'native bus' & api implementation
  console/backend/src/main/java/org/frankframework/management/web/FileViewer.java
  console/backend/src/main/java/org/frankframework/util/ResponseUtils.java
  console/backend/src/test/java/org/frankframework/management/web/FrankApiTestBase.java
  console/backend/src/test/java/org/frankframework/management/web/TestFileViewer.java
  console/backend/src/test/resources/FileViewer/FileViewer.txt
  console/frontend/src/main/frontend/src/app/app.module.ts
  console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.html
  console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.scss
  console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.spec.ts
  console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.ts
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.html
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.ts
  core/src/main/java/org/frankframework/lifecycle/ShowLogDirectory.java
  core/src/main/java/org/frankframework/management/bus/endpoints/FileViewer.java
  core/src/main/java/org/frankframework/webcontrol/FileViewerServlet.java
  core/src/main/resources/AppConstants.properties
  core/src/main/resources/META-INF/resources/iaf/ie4.css
  core/src/test/java/org/frankframework/management/bus/endpoints/TestFileViewer.java
  core/src/test/resources/Management/FileViewer.txt
  docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties
  management-gateway/src/main/java/org/frankframework/management/bus/BusTopic.java
  management-gateway/src/main/java/org/frankframework/management/bus/ResponseMessageBase.java
Labels: Frank Console, Frank Framework

#6321 Add inline image generation for mermaid flows
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/package.json
  console/frontend/src/main/frontend/src/app/app.module.ts
  console/frontend/src/main/frontend/src/app/components/ng-mermaid/ng-mermaid.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/scroll-to-top.component.ts
  console/frontend/src/main/frontend/src/app/views/status/flow/flow.component.html
  console/frontend/src/main/frontend/src/app/views/status/flow/flow.component.scss
  console/frontend/src/main/frontend/src/app/views/status/flow/flow.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.service.ts
  console/frontend/src/main/frontend/src/main.ts
Labels: Frank Console

#6317 Add FtpFileSystemActorTest and improve FTP implementation
  core/src/main/java/org/frankframework/filesystem/FtpFileSystem.java
  core/src/main/java/org/frankframework/pipes/FilePipe.java
  core/src/test/java/org/frankframework/filesystem/FileSystemActorTest.java
  core/src/test/java/org/frankframework/filesystem/FtpFileSystemActorTest.java
  core/src/test/java/org/frankframework/filesystem/FtpFileSystemTest.java
  core/src/test/java/org/frankframework/filesystem/FtpFileSystemTestHelper.java
  core/src/test/java/org/frankframework/testutil/junit/LocalFileServer.java
  core/src/test/java/org/frankframework/util/FileHandlerTestBase.java
Labels: FileSystem

#6328 Close Message properly; remove 2 static methods from Message
  core/src/main/java/org/frankframework/errormessageformatters/XslErrorMessageFormatter.java
  core/src/main/java/org/frankframework/http/HttpSenderBase.java
  core/src/main/java/org/frankframework/parameters/Parameter.java
  core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
  core/src/main/java/org/frankframework/senders/FixedResultSender.java
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/main/java/org/frankframework/util/XmlUtils.java
  core/src/test/java/org/frankframework/stream/MessageTest.java
  core/src/test/java/org/frankframework/util/XmlParserTest.java
Labels: 8.0

#6329 Close Message properly; remove 2 static methods from Message
  core/src/main/java/nl/nn/adapterframework/errormessageformatters/XslErrorMessageFormatter.java
  core/src/main/java/nl/nn/adapterframework/http/HttpSenderBase.java
  core/src/main/java/nl/nn/adapterframework/parameters/Parameter.java
  core/src/main/java/nl/nn/adapterframework/pipes/FixedResultPipe.java
  core/src/main/java/nl/nn/adapterframework/senders/FixedResultSender.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
  core/src/test/java/nl/nn/adapterframework/util/XmlParserTest.java
Labels: 7.9

#6318 Make query-timeout more consistently for all query senders
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcSenderBase.java
  core/src/main/java/nl/nn/adapterframework/jdbc/StoredProcedureQuerySender.java
  core/src/main/java/nl/nn/adapterframework/jdbc/XmlQuerySender.java
Labels: 7.9

#6320 Rename jdbc minPoolSize to minIdle
  core/src/main/java/nl/nn/adapterframework/jdbc/datasource/JdbcPoolUtil.java
  core/src/main/java/nl/nn/adapterframework/jndi/PoolingJndiDataSourceFactory.java
  core/src/main/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactory.java
  core/src/main/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactory.java
  core/src/main/resources/AppConstants.properties
  core/src/test/java/nl/nn/adapterframework/jta/btm/BtmDataSourceFactoryTest.java
  core/src/test/java/nl/nn/adapterframework/jta/narayana/NarayanaDataSourceFactoryTest.java
Labels: 7.9

#6341 Make query-timeout more consistently for all query senders
  core/src/main/java/org/frankframework/jdbc/JdbcQuerySenderBase.java
  core/src/main/java/org/frankframework/jdbc/JdbcSenderBase.java
  core/src/main/java/org/frankframework/jdbc/StoredProcedureQuerySender.java
  core/src/main/java/org/frankframework/jdbc/XmlQuerySender.java
Labels: 8.0

#6343 Add FtpFileSystemActorTest and improve FTP implementation (#6317)
  core/src/main/java/org/frankframework/filesystem/FtpFileSystem.java
  core/src/main/java/org/frankframework/pipes/FilePipe.java
  core/src/test/java/org/frankframework/filesystem/FileSystemActorTest.java
  core/src/test/java/org/frankframework/filesystem/FtpFileSystemActorTest.java
  core/src/test/java/org/frankframework/filesystem/FtpFileSystemTest.java
  core/src/test/java/org/frankframework/filesystem/FtpFileSystemTestHelper.java
  core/src/test/java/org/frankframework/testutil/junit/LocalFileServer.java
  core/src/test/java/org/frankframework/util/FileHandlerTestBase.java
Labels: 8.0

#6250 Improve SFTP implementation and unit tests
  core/src/main/java/nl/nn/adapterframework/filesystem/SftpFileSystem.java
  core/src/main/java/nl/nn/adapterframework/ftp/SftpSession.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/SftpFileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/SftpFileSystemTestHelper.java
Labels: 7.9

#6249 Improve SFTP implementation and unit tests
  core/src/main/java/org/frankframework/filesystem/SftpFileSystem.java
  core/src/main/java/org/frankframework/ftp/SftpSession.java
  core/src/test/java/org/frankframework/filesystem/FileSystemTest.java
  core/src/test/java/org/frankframework/filesystem/SftpFileSystemTest.java
Labels: 8.0

#6345 Add FtpFileSystemActorTest and improve FTP implementation (#6317)
  core/src/main/java/nl/nn/adapterframework/filesystem/FtpFileSystem.java
  core/src/main/java/nl/nn/adapterframework/pipes/FilePipe.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FileSystemActorTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FtpFileSystemActorTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FtpFileSystemTest.java
  core/src/test/java/nl/nn/adapterframework/filesystem/FtpFileSystemTestHelper.java
  core/src/test/java/nl/nn/adapterframework/filesystem/LocalFileServer.java
  core/src/test/java/nl/nn/adapterframework/util/FileHandlerTestBase.java
Labels: 7.9

#6349 Add ReconnectSenderWrapper (#6338)
  core/src/main/java/org/frankframework/senders/ReconnectSenderWrapper.java
  core/src/test/java/org/frankframework/senders/ReconnectSenderWrapperTest.java
Labels: Backport, 8.0

#6339 Store message-context in ErrorStorage
  core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemUtils.java
  core/src/main/java/nl/nn/adapterframework/filesystem/ImapFileSystem.java
  core/src/main/java/nl/nn/adapterframework/http/PartMessage.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/main/java/nl/nn/adapterframework/jms/JMSFacade.java
  core/src/main/java/nl/nn/adapterframework/receivers/MessageWrapper.java
  core/src/main/java/nl/nn/adapterframework/stream/Message.java
  core/src/main/java/nl/nn/adapterframework/stream/MessageContext.java
  core/src/main/java/nl/nn/adapterframework/stream/UrlMessage.java
  core/src/test/java/nl/nn/adapterframework/receivers/MessageWrapperTest.java
  core/src/test/java/nl/nn/adapterframework/stream/MessageTest.java
  core/src/test/java/nl/nn/adapterframework/stream/UrlMessageTest.java
  test/src/main/java/nl/nn/adapterframework/pipes/RetrieveContextPipe.java
Labels: 7.9

#6352 Store message-context in ErrorStorage
  core/src/main/java/org/frankframework/filesystem/FileSystemUtils.java
  core/src/main/java/org/frankframework/filesystem/ImapFileSystem.java
  core/src/main/java/org/frankframework/http/PartMessage.java
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
  core/src/main/java/org/frankframework/jms/JMSFacade.java
  core/src/main/java/org/frankframework/receivers/MessageWrapper.java
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/main/java/org/frankframework/stream/MessageContext.java
  core/src/main/java/org/frankframework/stream/UrlMessage.java
  core/src/test/java/org/frankframework/receivers/MessageWrapperTest.java
  core/src/test/java/org/frankframework/stream/MessageTest.java
  core/src/test/java/org/frankframework/stream/UrlMessageTest.java
  test/src/main/java/org/frankframework/pipes/RetrieveContextPipe.java
Labels: 8.0

#6356 Copy button for mermaid image
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/src/app/components/ng-mermaid/ng-mermaid.component.ts
  console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.html
  console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.scss
  console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.ts
  console/frontend/src/main/frontend/src/assets/mermaid-boostrap.scss
  console/frontend/src/main/frontend/src/styles.scss
Labels: Frank Console

#6359 Update Angular to v17
  console/frontend/pom.xml
  console/frontend/src/main/frontend/angular.json
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/package.json
  console/frontend/src/main/frontend/src/app/app-routing.module.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
Labels: Frank Console

#6368 Reduce number of connections to JMS
  core/src/main/java/org/frankframework/jms/MessagingSource.java
  core/src/main/resources/AppConstants.properties
Labels: 8.0

#6370 Clean JdbcUtil class
  batch/src/main/java/org/frankframework/jdbc/Result2BlobWriter.java
  core/src/main/java/org/frankframework/jdbc/JdbcListener.java
  core/src/main/java/org/frankframework/jdbc/JdbcTransactionalStorage.java
  core/src/main/java/org/frankframework/util/DB2DocumentWriter.java
  core/src/main/java/org/frankframework/util/JdbcUtil.java
  core/src/test/java/org/frankframework/senders/LogSenderTest.java
  nn-specials/src/main/java/org/frankframework/extensions/api/ApiStreamPipe.java
Labels: Technical Debt
