Repository frankframework/frankframework, pull requests merged in 2024-04, with the labels that each got.

#6550 Add log message when pipe is skipped
  console/war/pom.xml
  core/pom.xml
  core/src/main/java/nl/nn/adapterframework/pipes/FixedForwardPipe.java
  core/src/main/java/nl/nn/adapterframework/processors/InputOutputPipeProcessor.java
  core/src/main/java/nl/nn/adapterframework/util/MessageUtils.java
  core/src/test/java/nl/nn/adapterframework/util/MessageUtilsTest.java
Labels: 7.9

#6551 Fix spring boot CVE + Add log message when pipe is skipped
  console/war/pom.xml
  core/src/main/java/org/frankframework/pipes/FixedForwardPipe.java
  core/src/main/java/org/frankframework/processors/InputOutputPipeProcessor.java
  core/src/main/java/org/frankframework/util/MessageUtils.java
  core/src/test/java/org/frankframework/util/MessageUtilsTest.java
  pom.xml
Labels: Backport, 8.0

#6570 For now, remove noise when message is stored in ErrorStorage
  core/src/main/java/org/frankframework/jta/SpringTxManagerProxy.java
Labels: Backport, 8.0

#6569 Remove noise when message is stored in ErrorStorage
  core/src/main/java/nl/nn/adapterframework/jta/SpringTxManagerProxy.java
Labels: Backport, 7.9

#6577 Deprecate 'CleanupOldFilesPipe'
  core/src/main/java/nl/nn/adapterframework/pipes/CleanupOldFilesPipe.java
  core/src/main/java/nl/nn/adapterframework/pipes/UploadFilePipe.java
Labels: Backport, 7.9

#6576 Remove CleanupOldFilesPipe and UploadFilePipe
  core/src/main/java/org/frankframework/pipes/CleanupOldFilesPipe.java
  core/src/main/java/org/frankframework/pipes/UploadFilePipe.java
  core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd
  core/src/main/resources/xml/xsd/FrankConfig.xsd
  core/src/main/resources/xml/xsl/uglify_lookup.xml
  core/src/test/java/org/frankframework/pipes/CleanupOldFilesPipeTest.java
  core/src/test/java/org/frankframework/pipes/UploadFilePipeTest.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemPipe.java
  filesystem/src/test/java/org/frankframework/filesystem/FileSystemPipeTest.java
  test/src/main/configurations/FileHandling/ConfigurationUploadFile.xml
  test/src/main/configurations/MainConfig/ConfigurationMoveFilePipe.xml
Labels: Technical Debt

#6592 Remove CleanupOldFilesPipe and UploadFilePipe
  core/src/main/java/org/frankframework/filesystem/FileSystemPipe.java
  core/src/main/java/org/frankframework/pipes/CleanupOldFilesPipe.java
  core/src/main/java/org/frankframework/pipes/UploadFilePipe.java
  core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd
  core/src/main/resources/xml/xsd/FrankConfig.xsd
  core/src/main/resources/xml/xsl/uglify_lookup.xml
  core/src/test/java/org/frankframework/filesystem/FileSystemPipeTest.java
  core/src/test/java/org/frankframework/pipes/CleanupOldFilesPipeTest.java
  core/src/test/java/org/frankframework/pipes/UploadFilePipeTest.java
  test/src/main/configurations/FileHandling/ConfigurationUploadFile.xml
  test/src/main/configurations/MainConfig/ConfigurationMoveFilePipe.xml
Labels: Backport, 8.0

#6612 AllowUrlEncodedSlash
  console/war/src/main/resources/FrankConsoleContext.xml
  core/src/main/resources/SpringEnvironmentContext.xml
Labels: Backport, 8.0

#6613 AllowUrlEncodedSlash
  console/war/src/main/resources/FrankConsoleContext.xml
  core/src/main/resources/SpringEnvironmentContext.xml
Labels: Backport, 8.1

#6611 Allow url encoded slash
  console/war/src/main/resources/FrankConsoleContext.xml
  core/src/main/resources/SpringEnvironmentContext.xml
Labels: Backport, 7.9

#6624 Improve user facing error messages on Console's JDBC Executy Query page
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/ExecuteJdbcQuery.java
Labels: Frank Console

#6632 Improve user facing error messages on Console's JDBC Executy Query page
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/ExecuteJdbcQuery.java
Labels: Frank Console, Backport, 8.1

#6602 No longer swallow exception from commit if TX status is rollback-only
  core/src/main/java/org/frankframework/jta/SpringTxManagerProxy.java
Labels: Bug

#6598 Increase max log file size; increase message persist to disk size
  core/src/main/java/org/frankframework/logging/FrankLogConfigurationFactory.java
  core/src/main/resources/AppConstants.properties
  core/src/main/resources/log4j4ibis.properties
  core/src/test/resources/log4j4ibis.properties
Labels: Technical Debt

#6637 Allow custom headers in CMIS
  cmis/src/main/java/org/frankframework/extensions/cmis/CloseableCmisSession.java
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisHttpInvoker.java
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisSender.java
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisSessionBuilder.java
  cmis/src/main/java/org/frankframework/extensions/cmis/server/BridgedCmisService.java
Labels: Backport, 8.0

#6644 Chore: Code clean ups & persist disk size change from master PRs
  RELEASES.md
  batch/src/main/java/org/frankframework/batch/RecordHandlerManager.java
  core/src/main/java/org/frankframework/http/HttpSessionBase.java
  core/src/main/java/org/frankframework/jdbc/JdbcQueryListener.java
  core/src/main/java/org/frankframework/jdbc/JdbcTransactionalStorage.java
  core/src/main/java/org/frankframework/jms/MessagingSource.java
  core/src/main/java/org/frankframework/pipes/ForEachChildElementPipe.java
  core/src/main/java/org/frankframework/pipes/IteratingPipe.java
  core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java
  core/src/main/java/org/frankframework/pipes/StringIteratorPipe.java
  core/src/main/java/org/frankframework/pipes/WsdlXmlValidator.java
  core/src/main/java/org/frankframework/receivers/FileRecordListener.java
  core/src/main/java/org/frankframework/scheduler/JobDef.java
  core/src/main/java/org/frankframework/scheduler/NamedThreadFactory.java
  core/src/main/java/org/frankframework/senders/IsolatedServiceCaller.java
  core/src/main/java/org/frankframework/task/TimeoutGuard.java
  core/src/main/resources/AppConstants.properties
  core/src/test/java/org/frankframework/http/authentication/OAuthAccessTokenManagerRequestTest.java
  core/src/test/java/org/frankframework/pipes/IteratingPipeTestBase.java
  core/src/test/java/org/frankframework/pipes/StreamLineIteratorPipeTest.java
  core/src/test/java/org/frankframework/testutil/ConcurrentActionTester.java
  core/src/test/java/org/frankframework/testutil/junit/DatabaseTestEnvironment.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java
Labels: Technical Debt

#6656 Improved non-view components & made them standalone
  console/frontend/src/main/frontend/src/app/app.module.ts
  console/frontend/src/main/frontend/src/app/components/custom-views/custom-views.component.ts
  console/frontend/src/main/frontend/src/app/components/file-viewer/file-viewer.component.ts
  console/frontend/src/main/frontend/src/app/components/input-file-upload/input-file-upload.component.ts
  console/frontend/src/main/frontend/src/app/components/logout/logout.component.ts
  console/frontend/src/main/frontend/src/app/components/ng-mermaid/ng-mermaid.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/feedback-modal/feedback-modal.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-footer/pages-footer.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/minimaliza-sidebar.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/scroll-to-top.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topinfobar/pages-topinfobar.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/hamburger.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/side-navigation.directive.ts
  console/frontend/src/main/frontend/src/app/components/th-sortable.directive.ts
  console/frontend/src/main/frontend/src/app/components/time-since.directive.ts
  console/frontend/src/main/frontend/src/app/components/to-date.directive.ts
  console/frontend/src/main/frontend/src/app/components/toasts-container/toasts-container.component.ts
  console/frontend/src/main/frontend/src/main.ts
  console/frontend/src/main/frontend/tsconfig.json
Labels: Frank Console

#6665 Register inbound http filter
  management-gateway/src/main/java/org/frankframework/management/gateway/HttpInboundGateway.java
  management-gateway/src/main/java/org/frankframework/management/security/JwtSecurityFilter.java
Labels: Backport, 8.1

#6664 Register inbound http filter
  management-gateway/src/main/java/org/frankframework/management/gateway/HttpInboundGateway.java
  management-gateway/src/main/java/org/frankframework/management/security/JwtSecurityFilter.java
Labels: Backport, 8.0

#6600 Console rewrite frontend start & data flow
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/app.service.ts
  console/frontend/src/main/frontend/src/app/components/time-since.directive.ts
  console/frontend/src/main/frontend/src/app/components/to-date.directive.ts
  console/frontend/src/main/frontend/src/app/http-interceptors/connection-interceptor.ts
  console/frontend/src/main/frontend/src/app/services/auth.service.ts
  console/frontend/src/main/frontend/src/app/services/poller.service.ts
  console/frontend/src/main/frontend/src/app/views/adapterstatistics/adapterstatistics.component.html
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.ts
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html
Labels: Frank Console

#6667 Refactor iDinSender
  idin/pom.xml
  idin/src/main/java/org/frankframework/extensions/idin/DynamicMessengerCommunicator.java
  idin/src/main/java/org/frankframework/extensions/idin/IdinSender.java
  idin/src/main/resources/META-INF/services/javax.xml.transform.TransformerFactory
  idin/src/test/java/org/frankframework/extensions/idin/IdinSenderTest.java
  idin/src/test/resources/DeploymentSpecifics.properties
  idin/src/test/resources/bankid-config.xml
  idin/src/test/resources/certificates/BankID2020.Libs.sha256.2048.csp.jks
  idin/src/test/resources/certificates/custom/AcquirerCertificateBankId2020.Libs.sha256.2048.csp.jks
  idin/src/test/resources/certificates/custom/MerchantKeyPairBankID2020.Libs.sha256.2048.csp.jks
  idin/src/test/resources/configs/custom-key-provider-alternate-config.xml
  idin/src/test/resources/configs/custom-key-provider-config.xml
  idin/src/test/resources/configs/default-config.xml
  idin/src/test/resources/log4j4ibis.xml
  idin/src/test/resources/messages/directory-request.xml
  idin/src/test/resources/messages/directory-response.xml
  idin/src/test/resources/messages/full-status-response-message.xml
  idin/src/test/resources/messages/status-request.xml
  idin/src/test/resources/messages/status-response.xml
  idin/src/test/resources/messages/transaction-request.xml
  idin/src/test/resources/messages/transaction-response.xml
Labels: Backport, 8.1

#6668 Refactor iDinSender
  idin/pom.xml
  idin/src/main/java/org/frankframework/extensions/idin/DynamicMessengerCommunicator.java
  idin/src/main/java/org/frankframework/extensions/idin/IdinSender.java
  idin/src/main/resources/META-INF/services/javax.xml.transform.TransformerFactory
  idin/src/test/java/org/frankframework/extensions/idin/IdinSenderTest.java
  idin/src/test/resources/DeploymentSpecifics.properties
  idin/src/test/resources/bankid-config.xml
  idin/src/test/resources/certificates/BankID2020.Libs.sha256.2048.csp.jks
  idin/src/test/resources/certificates/custom/AcquirerCertificateBankId2020.Libs.sha256.2048.csp.jks
  idin/src/test/resources/certificates/custom/MerchantKeyPairBankID2020.Libs.sha256.2048.csp.jks
  idin/src/test/resources/configs/custom-key-provider-alternate-config.xml
  idin/src/test/resources/configs/custom-key-provider-config.xml
  idin/src/test/resources/configs/default-config.xml
  idin/src/test/resources/log4j4ibis.xml
  idin/src/test/resources/messages/directory-request.xml
  idin/src/test/resources/messages/directory-response.xml
  idin/src/test/resources/messages/full-status-response-message.xml
  idin/src/test/resources/messages/status-request.xml
  idin/src/test/resources/messages/status-response.xml
  idin/src/test/resources/messages/transaction-request.xml
  idin/src/test/resources/messages/transaction-response.xml
Labels: Backport, 8.0

#6692 Clean up SneakyThrows annotations
  core/src/main/java/org/frankframework/core/Adapter.java
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/main/java/org/frankframework/jdbc/MessageStoreSender.java
  core/src/main/java/org/frankframework/jms/JMSFacade.java
  core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java
  core/src/main/java/org/frankframework/pipes/RemoveFromSession.java
  core/src/test/java/org/frankframework/http/cxf/SoapProviderStub.java
  core/src/test/java/org/frankframework/monitoring/MessageCapturingEchoSender.java
  core/src/test/java/org/frankframework/receivers/ReceiverTest.java
  core/src/test/java/org/frankframework/testutil/TestFileUtils.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemListener.java
  ladybug/src/main/java/org/frankframework/ibistesttool/MessageEncoder.java
Labels: Technical Debt

#6721 Bump bouncycastle
  core/pom.xml
Labels: Backport, 8.1

#6729 Bump JMS pooling dep
  core/pom.xml
Labels: Backport, 8.0

#6734 Invalidate managed jms sessions instead of resetting them
  core/pom.xml
Labels: Dependencies

#6730 Invalidate managed jms sessions instead of resetting them
  core/pom.xml
Labels: Dependencies, 7.9

#6731 Invalide managed jms sessions instead of resetting them
  core/pom.xml
Labels: Dependencies, 8.0

#6732 Invalidate managed jms sessions instead of resetting them
  core/pom.xml
Labels: Dependencies, 8.1
