Repository frankframework/frankframework, pull requests merged in 2024-11, with the labels that each got.

#7850 Fix js exception when no listener in receiver
  console/frontend/src/main/frontend/src/app/views/status/adapter-status/adapter-status.component.html
Labels: FF! Console, Backport, 8.3

#7837 Fix origin header schema when being a reverse proxy
  console/backend/src/main/java/org/frankframework/console/filters/CorsFilter.java
Labels: 8.3

#7849 Disable https setting by default in the Docker image
  docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties
Labels: 8.3

#7860 Some Sonar Love for LarvaTool
  larva/src/main/java/org/frankframework/larva/LarvaServlet.java
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/queues/QueueWrapper.java
Labels: Technical Debt

#7876 Update the actions/upload-artifact@v3 to actions/upload-artifact@v4
  .github/workflows/maven-build.yml
Labels: CI, Backport, 7.9

#7875 Update the actions/upload-artifact@v3 to actions/upload-artifact@v4
  .github/workflows/maven-build.yml
Labels: CI, Backport, 8.0

#7874 Update the actions/upload-artifact@v3 to actions/upload-artifact@v4
  .github/workflows/maven-build.yml
Labels: CI, Backport, 8.1

#7873 Update the actions/upload-artifact@v3 to actions/upload-artifact@v4
  .github/workflows/maven-build.yml
Labels: CI, Backport, 8.2

#7872 Update the actions/upload-artifact@v3 to actions/upload-artifact@v4
  .github/workflows/maven-build.yml
Labels: CI, Backport, 8.3

#7892 Fixing a number of leaks of unclosed PipeLineSessions and Messages
  ladybug/debugger/src/main/java/org/frankframework/ladybug/tibet2/Tibet2DatabaseStorage.java
  ladybug/debugger/src/main/java/org/frankframework/ladybug/tibet2/TibetView.java
  larva/src/main/java/org/frankframework/extensions/test/IbisTester.java
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/ListenerMessageHandler.java
  larva/src/main/java/org/frankframework/larva/SenderThread.java
  larva/src/main/java/org/frankframework/larva/queues/QueueCreator.java
  larva/src/main/java/org/frankframework/larva/queues/QueueWrapper.java
Labels: Technical Debt

#7896 Update HTTPS instructions and secrets configuration
  Docker.md
  docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties
  test/src/main/secrets/apiAlias/password
  test/src/main/secrets/apiAlias/username
  test/src/main/secrets/credentials.propertis
  test/src/main/secrets/influx/password
  test/src/main/secrets/mongodb/password
  test/src/main/secrets/mongodb/username
  test/src/main/secrets/testalias/password
  test/src/main/secrets/testalias/username
  test/src/main/secrets/testiaf_user/password
  test/src/main/secrets/testiaf_user/username
Labels: Documentation, Docker

#7902 Fix sidenav Overview menu closing on Connections page
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html
Labels: FF! Console, Backport, 8.3

#7901 Fix sidenav Overview menu closing on Connections page
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html
Labels: FF! Console

#7905 Add validations to JdbcTableListener for fields used in the query (#7894)
  core/src/main/java/org/frankframework/jdbc/JdbcListener.java
  core/src/main/java/org/frankframework/jdbc/JdbcTableListener.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerNonDbTest.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
Labels: 8.3

#7903 Add validations to JdbcTableListener for fields used in the query (#7894)
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcListener.java
  core/src/main/java/nl/nn/adapterframework/jdbc/JdbcTableListener.java
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTableListenerNonDbTest.java
  core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTableListenerTest.java
Labels: 7.9

#7904 Add validations to JdbcTableListener for fields used in the query (#7894)
  core/src/main/java/org/frankframework/jdbc/JdbcListener.java
  core/src/main/java/org/frankframework/jdbc/JdbcTableListener.java
  core/src/main/java/org/frankframework/receivers/PullingListenerContainer.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerNonDbTest.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
Labels: 8.0

#7908 Fix uploading artifact to existing artifact in matrix workflow
  .github/workflows/maven-build.yml
Labels: Backport, 8.3

#7909 Fix uploading artifact to existing artifact in matrix workflow
  .github/workflows/maven-build.yml
Labels: Backport, 8.2

#7910 Fix uploading artifact to existing artifact in matrix workflow
  .github/workflows/maven-build.yml
Labels: Backport, 8.1

#7911 Fix uploading artifact to existing artifact in matrix workflow
  .github/workflows/maven-build.yml
Labels: Backport, 8.0

#7906 Fix uploading artifact to existing artifact in matrix workflow
  .github/workflows/maven-build.yml
Labels: Backport, 7.9

#7915 Fix monitor edit not using put on submit
  console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.ts
Labels: FF! Console

#7916 Fix monitor edit not using put on submit
  console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.ts
Labels: FF! Console, Backport, 8.3

#7913 Handle lack of server info in console on slow / no backend
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.html
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html
  console/frontend/src/main/frontend/src/app/services/server-info.service.ts
Labels: FF! Console

#7914 Handle lack of server info in console on slow / no backend
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.html
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html
  console/frontend/src/main/frontend/src/app/services/server-info.service.ts
Labels: FF! Console, Backport, 8.3

#7922 Get server timezone from FF Core & handle in console frontend
  console/frontend/src/main/frontend/src/app/app.component.html
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/app.service.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-topnavbar/pages-topnavbar.component.ts
  console/frontend/src/main/frontend/src/app/components/time-since.directive.ts
  console/frontend/src/main/frontend/src/app/components/to-date.directive.ts
  console/frontend/src/main/frontend/src/app/services/server-info.service.ts
  console/frontend/src/main/frontend/src/app/services/server-time.service.spec.ts
  console/frontend/src/main/frontend/src/app/services/server-time.service.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/ServerStatistics.java
Labels: FF! Console

#7939 Remove logging of leaks that is now being made obsolete in 9.0
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/main/java/org/frankframework/stream/OverflowToDiskOutputStream.java
  core/src/main/java/org/frankframework/stream/SerializableFileReference.java
  core/src/test/java/org/frankframework/stream/MessageTest.java
Labels: Technical Debt

#7946 Fix file viewing rule and string resolving with multiple defaults
  commons/src/main/java/org/frankframework/util/StringResolver.java
  commons/src/test/java/org/frankframework/util/StringResolverTest.java
  commons/src/test/resources/StringResolver.properties
  docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties
Labels: Bug, Docker, Java

#7976 Fix add monitors view & set default type to ALARM
  console/frontend/src/main/frontend/src/app/app-routing.module.ts
  console/frontend/src/main/frontend/src/app/views/monitors/monitors-add-edit/monitors-add-edit.component.ts
Labels: FF! Console

#7956 Select new cluster member when previous selected has disappeared
  console/backend/src/main/java/org/frankframework/console/controllers/ClusterMemberEndpoint.java
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts
  console/frontend/src/main/frontend/src/app/services/server-info.service.ts
Labels: FF! Console, Backport, 8.3

#7948 Select new cluster member when previous selected has disappeared
  console/backend/src/main/java/org/frankframework/console/controllers/ClusterMemberEndpoint.java
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts
  console/frontend/src/main/frontend/src/app/services/server-info.service.ts
Labels: FF! Console

#7975 Move configuration tabs to separate component
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/app.module.ts
  console/frontend/src/main/frontend/src/app/app.service.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html
  console/frontend/src/main/frontend/src/app/components/tab-list/configuration-tab-list.component.ts
  console/frontend/src/main/frontend/src/app/components/tab-list/tab-list.component.html
  console/frontend/src/main/frontend/src/app/components/tab-list/tab-list.component.scss
  console/frontend/src/main/frontend/src/app/components/tab-list/tab-list.component.spec.ts
  console/frontend/src/main/frontend/src/app/components/tab-list/tab-list.component.ts
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.html
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.ts
  console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.html
  console/frontend/src/main/frontend/src/app/views/environment-variables/environment-variables.component.ts
  console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
Labels: FF! Console

#7999 Console frontend Types cleanup
  console/frontend/src/main/frontend/.eslintrc.js
  console/frontend/src/main/frontend/package.json
  console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.ts
  console/frontend/src/main/frontend/src/app/components/ng-mermaid/ng-mermaid.component.ts
Labels: FF! Console
