Repository frankframework/frankframework, pull requests merged in 2024-12, with the labels that each got.

#8063 Backport: fix scroll to top button visibility and behavior (#8053)
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/scroll-to-top.component.ts
  console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css
  console/frontend/src/main/frontend/src/main.ts
Labels: Backport, 8.3

#8061 Move conditional loading of 'testtool.enabled'
  ladybug/src/main/java/org/frankframework/ibistesttool/DebuggerActive.java
  ladybug/src/main/java/org/frankframework/ibistesttool/DeploymentSpecificsBeanPostProcessor.java
  ladybug/src/main/resources/springIbisDebuggerAdvice.xml
Labels: Backport, 8.2

#8066 One more cleanup in HttpSender code
  core/src/main/java/org/frankframework/http/HttpSender.java
  core/src/test/resources/Http/Responses/mtomWithoutFirstBodyPartName.txt
  core/src/test/resources/Http/Responses/multipartWithoutFirstBodyPartName.txt
  core/src/test/resources/Http/Responses/parametersToSkip.txt
  core/src/test/resources/Http/Responses/simpleMockedHttpMtom.txt
  core/src/test/resources/Http/Responses/simpleMockedHttpMultipart.txt
  core/src/test/resources/Http/Responses/simpleMockedHttpMultipartWithUrlPathAndQueryParam.txt
  core/src/test/resources/Http/Responses/simpleMockedHttpPostUrlEncoded.txt
  core/src/test/resources/Http/Responses/simpleMockedMultipartHttp1.txt
  core/src/test/resources/Http/Responses/simpleMockedMultipartHttp2.txt
  core/src/test/resources/Http/Responses/simpleMockedMultipartHttp3.txt
  core/src/test/resources/Http/Responses/simpleMockedMultipartMtom1.txt
  core/src/test/resources/Http/Responses/simpleMockedMultipartMtom2.txt
  core/src/test/resources/Http/Responses/simpleMockedMultipartMtom3.txt
  core/src/test/resources/Http/Responses/simpleMockedWssMtom.txt
  core/src/test/resources/Http/Responses/simpleMockedWssMultipart.txt
  core/src/test/resources/Http/Responses/simpleMockedWssMultipart2.txt
  core/src/test/resources/Http/Responses/simpleMockedWssMultipartMtom.txt
  core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXml.txt
  core/src/test/resources/Http/Responses/simpleMtomFromParametersAndMultipartXmlNoPartName.txt
  core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXml.txt
  core/src/test/resources/Http/Responses/simpleMultipartFromParametersAndMultipartXmlNoPartName.txt
  core/src/test/resources/Http/Responses/skipEmptyMultipartXmlSessionKey.txt
Labels: Technical Debt

#8064 Change messageId encoding to base64
  console/backend/src/main/java/org/frankframework/console/controllers/TransactionalStorage.java
  console/backend/src/main/resources/FrankConsoleContext.xml
  console/backend/src/test/java/org/frankframework/console/controllers/TransactionalStorageTest.java
  console/frontend/src/main/frontend/src/app/views/storage/storage-view/storage-view.component.ts
  console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
Labels: FF! Console

#8085 Add missing configuration name attribute in `InlineStoreItem`
  console/frontend/src/main/frontend/src/app/views/inlinestore/inlinestore.component.html
  core/src/main/java/org/frankframework/management/bus/endpoints/InlineStorage.java
  core/src/main/java/org/frankframework/processors/TrackPreviousPipeInMetadataProcessor.java
  core/src/test/resources/Management/getProcessStorage.json
Labels: FF! Console

#8101 Bump Log4J2 version to Log4J2.24.3
  pom.xml
Labels: Dependencies

#8128 JSON Validation parameter substitution deeper search
  core/src/main/java/org/frankframework/align/DomTreeAligner.java
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/Properties2Xml.java
  core/src/main/java/org/frankframework/align/ToXml.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/CommonResponse.xsd
  core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/Main.xsd
  core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/expected_output.json
Labels: Backport, 8.0

#8124 Remove more unused code
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/OverridesMap.java
  core/src/main/java/org/frankframework/align/SubstitutionNode.java
  core/src/main/java/org/frankframework/align/SubstitutionProvider.java
  core/src/main/java/org/frankframework/align/Xml2Json.java
  core/src/main/java/org/frankframework/align/Xml2Map.java
  core/src/main/java/org/frankframework/align/XmlAligner.java
  core/src/main/java/org/frankframework/align/XmlTo.java
  core/src/main/java/org/frankframework/align/content/DocumentContainer.java
  core/src/main/java/org/frankframework/align/content/ElementContainer.java
  core/src/main/java/org/frankframework/align/content/ElementGroupContainer.java
  core/src/main/java/org/frankframework/align/content/JsonDocumentContainer.java
  core/src/main/java/org/frankframework/align/content/JsonElementContainer.java
  core/src/main/java/org/frankframework/align/content/MapContentContainer.java
  core/src/main/java/org/frankframework/align/content/TreeContentContainer.java
  core/src/main/java/org/frankframework/pipes/Json2XmlValidator.java
  core/src/main/java/org/frankframework/pipes/JsonValidator.java
  core/src/test/java/org/frankframework/align/AlignTestBase.java
  core/src/test/java/org/frankframework/align/TestJson2Xml.java
  core/src/test/java/org/frankframework/align/TestXml2Json.java
  core/src/test/java/org/frankframework/align/TestXml2Map.java
  core/src/test/java/org/frankframework/align/TestXmlSchema2JsonSchema.java
Labels: Technical Debt

#8147 Deduping of repeated toasts
  console/frontend/src/main/frontend/src/app/components/toasts-container/toasts-container.component.html
  console/frontend/src/main/frontend/src/app/components/toasts-container/toasts-container.component.scss
  console/frontend/src/main/frontend/src/app/components/toasts-container/toasts-container.component.ts
  console/frontend/src/main/frontend/src/app/http-interceptors/connection-interceptor.ts
  console/frontend/src/main/frontend/src/app/services/toast.service.ts
  console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css
Labels: FF! Console
