Repository frankframework/frankframework, pull requests merged in 2024-05, with the labels that each got.

#6753 Fix object order
  core/src/main/java/org/frankframework/jdbc/datasource/ObjectFactoryBase.java
  core/src/main/java/org/frankframework/management/bus/endpoints/ExecuteJdbcQuery.java
  core/src/main/java/org/frankframework/management/bus/endpoints/SecurityItems.java
Labels: Backport, 8.1

#6759 Fix json conversion in restlistener
  core/src/main/java/org/frankframework/http/RestListener.java
  core/src/main/java/org/frankframework/management/bus/endpoints/AdapterStatus.java
  core/src/main/java/org/frankframework/pipes/JsonPipe.java
Labels: Backport, 8.1

#6773 Revert mariadb.driver.version to 2.7.10 because it fails with BTM
  RELEASES.md
  pom.xml
Labels: Bug, 8.0

#6774 Revert mariadb.driver.version to 2.7.10 because it fails with BTM
  RELEASES.md
  pom.xml
Labels: Bug, 8.1

#6775 Fix json conversion in restlistener
  core/src/main/java/nl/nn/adapterframework/http/RestListener.java
  core/src/main/java/nl/nn/adapterframework/pipes/JsonPipe.java
Labels: Backport, 7.9

#6782 Close streams in Aspose
  aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/convertors/CellsConvertor.java
  aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/convertors/PdfImageConvertor.java
Labels: Backport, 8.0

#6781 Close streams in Aspose
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/CellsConvertor.java
  aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/services/conv/impl/convertors/PdfImageConvertor.java
Labels: Backport, 7.9

#6783 Close streams in Aspose
  aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/convertors/CellsConvertor.java
  aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/convertors/PdfImageConvertor.java
Labels: Backport, 8.1

#6785 Deprecate IfMultipartPipe
  core/src/main/java/org/frankframework/pipes/IfMultipart.java
Labels: Backport, 8.0

#6786 Deprecate IfMultipartPipe
  core/src/main/java/org/frankframework/pipes/IfMultipart.java
Labels: Backport, 8.1

#6790 Backport param substitution
  RELEASES.md
  core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
  core/src/test/java/org/frankframework/pipes/FixedResultTest.java
  core/src/test/resources/FixedResult/fixedResultPipeInput.txt
  test/src/main/configurations/MainConfig/ConfigurationParameters.xml
  test/src/main/configurations/MainConfig/cache/resultTemplate.xml
  test/src/test/testtool/Parameters/scenario06.properties
  test/src/test/testtool/Parameters/scenario06/in.xml
  test/src/test/testtool/Parameters/scenario06/out.txt
  test/src/test/testtool/Parameters/scenario07.properties
  test/src/test/testtool/Parameters/scenario07/in.xml
  test/src/test/testtool/Parameters/scenario07/out.txt
Labels: Backport, 8.1

#6803 Add uwu easter egg
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-navigation/pages-navigation.component.ts
  console/frontend/src/main/frontend/src/assets/css/style.css
  console/frontend/src/main/frontend/src/assets/images/uwu-frank-exclamation.svg
  console/frontend/src/main/frontend/src/assets/images/uwu-frank-framework-logo.svg
Labels: Frank Console

#6794 Cleanup PR for IDbmsSupport
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
  core/src/test/java/org/frankframework/jdbc/ResultSetIteratingPipeTest.java
  core/src/test/java/org/frankframework/jdbc/TransactionManagerTest.java
  core/src/test/resources/Migrator/ChangelogBlobTests.xml
  dbms/src/main/java/org/frankframework/dbms/Db2DbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/GenericDbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/H2DbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/IDbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/MariaDbDbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/MsSqlServerDbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/MySqlDbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/OracleDbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/PostgresqlDbmsSupport.java
Labels: Technical Debt

#6811 Remove leftover javax.annotation imports
  checkstyle.xml
  core/src/main/java/org/frankframework/configuration/AdapterManager.java
  core/src/main/java/org/frankframework/jdbc/datasource/DataSourceFactory.java
  core/src/main/java/org/frankframework/jdbc/datasource/FrankResources.java
  core/src/main/java/org/frankframework/jdbc/datasource/TransactionalDbmsSupportAwareDataSourceProxy.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/WsdlGeneratorPipe.java
Labels: Technical Debt

#6797 Fix log levels and statements
  core/src/main/java/org/frankframework/jdbc/datasource/TransactionalDbmsSupportAwareDataSourceProxy.java
  core/src/main/java/org/frankframework/lifecycle/VerifyDatabaseConnectionBean.java
  core/src/main/java/org/frankframework/management/bus/MessageDispatcher.java
  core/src/main/java/org/frankframework/util/RunStateManager.java
Labels: Backport, 8.1

#6793 Reduce verbosity of toStringResult
  cmis/src/main/java/nl/nn/adapterframework/extensions/cmis/CmisSessionBuilder.java
  core/src/main/java/nl/nn/adapterframework/jms/JmsRealm.java
  core/src/main/java/nl/nn/adapterframework/jms/MessagingSource.java
  iaf-commons/pom.xml
  iaf-commons/src/main/java/nl/nn/adapterframework/util/FieldNameSensitiveToStringStyle.java
  iaf-commons/src/main/java/nl/nn/adapterframework/util/StringUtil.java
  iaf-commons/src/test/java/nl/nn/adapterframework/util/StringUtilTest.java
  iaf-commons/src/test/resources/log4j2.xml
  pom.xml
Labels: Backport, 7.9

#6812 Fix getDestinationName exceptions when no datasource or connection is available
  core/src/main/java/org/frankframework/jdbc/JdbcFacade.java
  core/src/main/java/org/frankframework/jdbc/datasource/TransactionalDbmsSupportAwareDataSourceProxy.java
  core/src/test/java/org/frankframework/receivers/ReceiverTest.java
  core/src/test/java/org/frankframework/testutil/mock/DataSourceFactoryMock.java
Labels: Backport, 8.0

#6817 Reduce verbosity of toStringResult
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisSessionBuilder.java
  commons/pom.xml
  commons/src/main/java/org/frankframework/util/FieldNameSensitiveToStringStyle.java
  commons/src/main/java/org/frankframework/util/StringUtil.java
  commons/src/test/java/org/frankframework/util/StringUtilTest.java
  commons/src/test/resources/log4j2.xml
  core/src/main/java/org/frankframework/jms/JmsRealm.java
  core/src/main/java/org/frankframework/jms/MessagingSource.java
  management-gateway/pom.xml
  pom.xml
Labels: Backport, 8.0

#6819 Reduce verbosity of toStringResult
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisSessionBuilder.java
  commons/src/main/java/org/frankframework/util/FieldNameSensitiveToStringStyle.java
  commons/src/main/java/org/frankframework/util/StringUtil.java
  commons/src/test/java/org/frankframework/util/StringUtilTest.java
  commons/src/test/resources/log4j2.xml
  core/src/main/java/org/frankframework/jms/JmsRealm.java
  core/src/main/java/org/frankframework/jms/MessagingSource.java
  management-gateway/pom.xml
Labels: Backport, 8.1

#6827 Fix missing page animations and other small fixes
  console/frontend/src/main/frontend/src/app/app-routing.module.ts
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-footer/pages-footer.component.html
  console/frontend/src/main/frontend/src/app/views/iaf-update/iaf-update.component.html
  console/frontend/src/main/frontend/src/app/views/logging/logging-manage/logging-manage.component.html
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.html
  console/frontend/src/main/frontend/src/app/views/login/login.component.html
  console/frontend/src/main/frontend/src/app/views/login/login.component.ts
  console/frontend/src/main/frontend/src/app/views/monitors/monitors.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css
Labels: Frank Console

#6837 Fix for date parser
  commons/src/main/java/org/frankframework/util/DateFormatUtils.java
  commons/src/test/java/org/frankframework/util/DateFormatUtilsTest.java
Labels: 8.0

#6843 Update ladybug to official release version
  ladybug/pom.xml
Labels: 8.1

#6850 Fix for any-date parser (#6837)
  commons/src/main/java/org/frankframework/util/DateFormatUtils.java
  commons/src/test/java/org/frankframework/util/DateFormatUtilsTest.java
Labels: 8.1

#6882 Fix case-sensitivity issue with Postgres & Liquibase
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml
  core/src/test/resources/Migrator/ChangelogBlobTests.xml
  core/src/test/resources/Migrator/CreateLockTable.xml
  core/src/test/resources/Migrator/DatabaseChangelog.xml
  core/src/test/resources/Migrator/DatabaseChangelogError.xml
  core/src/test/resources/Migrator/DatabaseChangelog_inserts.xml
  core/src/test/resources/Migrator/DatabaseChangelog_plus_changes.xml
  core/src/test/resources/Migrator/Ibisconfig_4_unittests_changeset.xml
  core/src/test/resources/Migrator/Ibisstore_4_unittests_changeset.xml
Labels: Technical Debt

#6892 Fix added poller not running immediately
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/services/poller.service.ts
Labels: Frank Console

#6895 Fix DbmsSupportTest.testQueueHandling
  core/src/test/java/org/frankframework/jdbc/dbms/DbmsSupportTest.java
Labels: Technical Debt

#6887 Add nightly release workflow
  .github/workflows/nightly-release.yml
Labels: 8.1

#6902 Improve quick-submit-form directive & apply to more textarea fields
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/quick-submit-form.directive.spec.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/quick-submit-form.directive.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
Labels: Frank Console

#6904 Improve quick-submit-form directive & apply to more textarea fields
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/quick-submit-form.directive.spec.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/quick-submit-form.directive.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
Labels: Frank Console, 8.1

#6909 Code cleanups with OpenRewrite
  aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/CisConversionResult.java
  cmis/src/main/java/org/frankframework/extensions/cmis/server/BridgedCmisService.java
  cmis/src/test/java/org/frankframework/extensions/cmis/CmisHttpInvokerTest.java
  cmis/src/test/java/org/frankframework/extensions/cmis/mtom/MtomRequestWrapperTest.java
  commons/src/main/java/org/frankframework/util/ClassUtils.java
  commons/src/test/java/org/frankframework/util/ClassUtilsTest.java
  commons/src/test/java/org/frankframework/util/PropertyLoaderTest.java
  commons/src/test/java/org/frankframework/util/UUIDUtilTest.java
  console/backend/src/test/java/org/frankframework/util/RequestUtilsTest.java
  core/src/main/java/org/frankframework/configuration/ConfigurationMessageEvent.java
  core/src/main/java/org/frankframework/configuration/ScheduleManager.java
  core/src/main/java/org/frankframework/configuration/classloaders/DatabaseClassLoader.java
  core/src/main/java/org/frankframework/configuration/classloaders/DirectoryClassLoader.java
  core/src/main/java/org/frankframework/http/authentication/OAuthAuthenticationScheme.java
  core/src/main/java/org/frankframework/lifecycle/ApplicationMessageEvent.java
  core/src/main/java/org/frankframework/lifecycle/ServletManager.java
  core/src/main/java/org/frankframework/management/bus/endpoints/UpdateLogSettings.java
  core/src/main/java/org/frankframework/parameters/Parameter.java
  core/src/main/java/org/frankframework/pipes/StreamPipe.java
  core/src/main/java/org/frankframework/processors/CoreListenerProcessor.java
  core/src/main/java/org/frankframework/scheduler/JobDef.java
  core/src/main/java/org/frankframework/scheduler/job/Job.java
  core/src/main/java/org/frankframework/senders/MailSenderBase.java
  core/src/test/java/org/frankframework/collection/CollectionSenderTest.java
  core/src/test/java/org/frankframework/collection/CollectorPipeTest.java
  core/src/test/java/org/frankframework/configuration/ConfigurationUtilsTest.java
  core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
  core/src/test/java/org/frankframework/http/HttpMessageEntityTest.java
  core/src/test/java/org/frankframework/http/HttpResponseMock.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/org/frankframework/parameters/ParameterTest.java
  core/src/test/java/org/frankframework/pipes/FilenameSwitchTest.java
  core/src/test/java/org/frankframework/pipes/GetPrincipalPipeTest.java
  core/src/test/java/org/frankframework/pipes/PasswordGeneratorPipeTest.java
  core/src/test/java/org/frankframework/pipes/UUIDGeneratorPipeTest.java
  core/src/test/java/org/frankframework/processors/InputOutputSenderWrapperProcessorTest.java
  core/src/test/java/org/frankframework/scheduler/CleanupDatabaseJobTest.java
  core/src/test/java/org/frankframework/util/AppConstantsTest.java
  core/src/test/java/org/frankframework/util/EntityResolvingTest.java
  core/src/test/java/org/frankframework/util/MessageBrowsingFilterTest.java
  core/src/test/java/org/frankframework/util/flow/graphviz/FormatTest.java
  dbms/src/main/java/org/frankframework/dbms/MsSqlServerDbmsSupport.java
  dbms/src/main/java/org/frankframework/dbms/MySqlDbmsSupport.java
  dbms/src/test/java/org/frankframework/dbms/SqlTranslatorOracleToH2Test.java
  filesystem/src/test/java/org/frankframework/filesystem/FileSystemPipeTest.java
  filesystem/src/test/java/org/frankframework/filesystem/FileSystemTest.java
  filesystem/src/test/java/org/frankframework/xml/StaxParserTest.java
  ladybug/src/main/java/org/frankframework/ibistesttool/tibet2/Storage.java
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  messaging/src/test/java/org/frankframework/extensions/kafka/KafkaSenderTest.java
  nn-specials/src/main/java/org/frankframework/extensions/rekenbox/Adios2XmlPipe.java
  security/src/main/java/org/frankframework/lifecycle/servlets/ServletConfiguration.java
  test-integration/src/test/java/org/frankframework/extensions/cmis/CmisSenderTest.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoLogJmsListener.java
Labels: Technical Debt

#6912 Allow null message (empty string for users) in Test a Pipeline
  console/backend/src/main/java/org/frankframework/management/web/SendJmsMessage.java
  console/backend/src/main/java/org/frankframework/management/web/TestPipeline.java
  console/backend/src/main/java/org/frankframework/management/web/TestServiceListener.java
  console/backend/src/main/java/org/frankframework/util/RequestUtils.java
  console/backend/src/test/java/org/frankframework/management/web/TestPipelineTest.java
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
  core/src/main/java/org/frankframework/management/bus/endpoints/TestPipeline.java
Labels: Frank Console
