Repository frankframework/frankframework, pull requests merged in 2025-02, with the labels that each got.

#8335 Add a Larva test with PubSub domain
  pom.xml
  test/src/main/configurations/JMS/Configuration.xml
  test/src/main/configurations/JMS/ConfigurationPubSub.xml
  test/src/main/resources/Configuration.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/test/testtool/JmsPubSub/common.properties
  test/src/test/testtool/JmsPubSub/common/md-delete-logs.xml
  test/src/test/testtool/JmsPubSub/common/md-delete-result.xml
  test/src/test/testtool/JmsPubSub/common/md-delete.xml
  test/src/test/testtool/JmsPubSub/common/md-select-logs.xml
  test/src/test/testtool/JmsPubSub/common/md-select.xml
  test/src/test/testtool/JmsPubSub/common/md-wait-till-message-done.xml
  test/src/test/testtool/JmsPubSub/scenario01.properties
  test/src/test/testtool/JmsPubSub/scenario01/out.txt
  test/src/test/testtool/JmsPubSub/scenario01/result-done-logs.xml
  test/src/test/testtool/JmsPubSub/scenario01/result-done.xml
Labels: 9.0

#8333 Add a Larva test with PubSub domain
  pom.xml
  test/src/main/configurations/JMS/Configuration.xml
  test/src/main/configurations/JMS/ConfigurationPubSub.xml
  test/src/main/resources/Configuration.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/test/testtool/JmsPubSub/common.properties
  test/src/test/testtool/JmsPubSub/common/md-delete-logs.xml
  test/src/test/testtool/JmsPubSub/common/md-delete-result.xml
  test/src/test/testtool/JmsPubSub/common/md-delete.xml
  test/src/test/testtool/JmsPubSub/common/md-select-logs.xml
  test/src/test/testtool/JmsPubSub/common/md-select.xml
  test/src/test/testtool/JmsPubSub/common/md-wait-till-message-done.xml
  test/src/test/testtool/JmsPubSub/scenario01.properties
  test/src/test/testtool/JmsPubSub/scenario01/out.txt
  test/src/test/testtool/JmsPubSub/scenario01/result-done-logs.xml
  test/src/test/testtool/JmsPubSub/scenario01/result-done.xml
Labels: 8.3

#8347 Create test for message captures
  core/src/main/java/org/frankframework/http/HttpResponseHandler.java
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/main/java/org/frankframework/util/StreamCaptureUtils.java
  core/src/test/java/org/frankframework/http/HttpSenderResultTest.java
  core/src/test/java/org/frankframework/util/StreamCaptureUtilsTest.java
  ladybug/debugger/pom.xml
  ladybug/debugger/src/main/java/org/frankframework/ladybug/MessageCapturer.java
  ladybug/debugger/src/main/java/org/frankframework/ladybug/capture/OutputStreamCaptureWrapper.java
  ladybug/debugger/src/main/java/org/frankframework/ladybug/capture/WriterCaptureWrapper.java
  ladybug/debugger/src/test/java/org/frankframework/ladybug/MessageCapturerTest.java
  ladybug/debugger/src/test/java/org/frankframework/ladybug/capture/TestOutputStreamCaptureWrapper.java
  ladybug/debugger/src/test/java/org/frankframework/ladybug/capture/TestWriterCaptureWrapper.java
  ladybug/debugger/src/test/resources/testString.txt
Labels: Backport, 9.0

#8345 Update config xsd and kafka dep
  example/src/main/resources/ConfigurationHelloBeautifulWorld.xml
  messaging/pom.xml
  test/src/main/configurations/MainConfig/Configuration.xml
  test/src/main/configurations/MainConfig/ConfigurationForPipe.xml
Labels: 9.0

#8348 Minor version updates for issues, mainly spring-security related
  pom.xml
Labels: 8.3

#8363 Backport 4 fixes to 7.9
  core/src/main/java/nl/nn/adapterframework/align/DomTreeAligner.java
  core/src/main/java/nl/nn/adapterframework/align/Json2Xml.java
  core/src/main/java/nl/nn/adapterframework/align/Properties2Xml.java
  core/src/main/java/nl/nn/adapterframework/align/ToXml.java
  core/src/main/java/nl/nn/adapterframework/align/Tree2Xml.java
  core/src/main/java/nl/nn/adapterframework/core/PipeLineSession.java
  core/src/main/java/nl/nn/adapterframework/util/TransformerPool.java
  core/src/test/java/nl/nn/adapterframework/core/PipeLineSessionTest.java
  core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/CommonResponse.xsd
  core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/Main.xsd
  core/src/test/resources/Validation/Json2Xml/ParameterSubstitution/expected_output.json
  core/src/test/resources/Validation/Parameters/out.xml
  core/src/test/resources/Validation/Parameters/simple.xsd
  pom.xml
Labels: Backport, 7.9

#8361 Show errorstore warnings even when no server warnings
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/src/app/views/status/server-warnings/server-warnings.component.html
Labels: FF! Console, Backport, 9.0

#8359 Show errorstore warnings even when no server warnings
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/src/app/views/status/server-warnings/server-warnings.component.html
Labels: FF! Console, Backport, 8.3

#8364 Try to make the PubSub Larva test more stable for all environments
  .gitattributes
  test/src/main/configurations/JMS/ConfigurationPubSub.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/test/testtool/JmsPubSub/common.properties
  test/src/test/testtool/JmsPubSub/common/md-select.xml
  test/src/test/testtool/JmsPubSub/common/md-wait-till-message-done.xml
  test/src/test/testtool/JmsPubSub/scenario01.properties
Labels: Bug

#8373 Change method parameter type to PipeLineSession in mergeToParent method
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/main/java/org/frankframework/pipes/StreamPipe.java
  core/src/main/java/org/frankframework/receivers/JavaListener.java
  core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
  core/src/test/java/org/frankframework/pipes/GetPrincipalPipeTest.java
  core/src/test/java/org/frankframework/pipes/IsUserInRolePipeTest.java
  core/src/test/java/org/frankframework/receivers/JavaListenerTest.java
Labels: Technical Debt

#8392 Clean up a few Sonar issues recently introduced
  ladybug/debugger/src/main/java/org/frankframework/ladybug/larva/ConvertToLarvaAction.java
Labels: Technical Debt

#8421 Fix reusing thread-names when reusing threads from pool
  core/src/main/java/org/frankframework/threading/ThreadNamingTaskDecorator.java
  core/src/main/resources/SpringApplicationContext.xml
  core/src/test/resources/testApplicationContext.xml
Labels: 9.0

#8408 Scroll to previously opened log file & log file popout button
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.html
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.scss
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.ts
Labels: FF! Console

#8418 Scroll to previously opened log file & log file popout button
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.html
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.scss
  console/frontend/src/main/frontend/src/app/views/logging/logging.component.ts
Labels: FF! Console, Backport, 9.0

#8423 Make code editor resizable and fix newline bug
  console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.html
  console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.ts
  console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.scss
  console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.spec.ts
  console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
Labels: FF! Console

#8424 Make code editor resizable and fix newline bug
  console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.html
  console/frontend/src/main/frontend/src/app/components/combobox/combobox.component.ts
  console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.scss
  console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.spec.ts
  console/frontend/src/main/frontend/src/app/components/quick-submit-form.directive.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.html
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.html
  console/frontend/src/main/frontend/src/app/views/scheduler/scheduler-add-edit-parent.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
Labels: FF! Console, Backport, 9.0

#8433 Disable PubSub Larva Test (backport for 9.0)
  .gitattributes
  test/src/main/configurations/JMS/ConfigurationPubSub.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/test/testtool/JmsPubSub/common.properties
  test/src/test/testtool/JmsPubSub/common/md-select.xml
  test/src/test/testtool/JmsPubSub/common/md-wait-till-message-done.xml
  test/src/test/testtool/JmsPubSub/scenario01.properties
Labels: 9.0

#8445 Disable Larva PubSub test b/c it is not stable
  .gitattributes
  test/src/main/configurations/JMS/ConfigurationPubSub.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/test/testtool/JmsPubSub/common.properties
  test/src/test/testtool/JmsPubSub/common/md-select.xml
  test/src/test/testtool/JmsPubSub/common/md-wait-till-message-done.xml
  test/src/test/testtool/JmsPubSub/scenario01.properties
Labels: Backport, 8.3

#8476 Remove IPipeLineExitHandler, remodel SapLUWHandle to be AutoCloseable
  core/src/main/java/org/frankframework/core/IPipeLineExitHandler.java
  core/src/main/java/org/frankframework/core/PipeLine.java
  core/src/main/java/org/frankframework/processors/CorePipeLineProcessor.java
  sap/src/main/java/org/frankframework/extensions/sap/jco3/SapLUWHandle.java
  sap/src/main/java/org/frankframework/extensions/sap/jco3/SapLUWManager.java
Labels: Technical Debt, NN

#8468 Fix files and directories retrieval using typeFilter FILES_AND_FOLDERS with the AmazonS3Sender
  aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java
  aws/src/main/java/org/frankframework/filesystem/S3FileRef.java
  aws/src/main/java/org/frankframework/senders/AmazonS3Sender.java
  aws/src/test/java/org/frankframework/senders/AmazonS3SenderTest.java
Labels: Backport, 9.0

#8469 Implement MessageContext refactorings
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/main/java/org/frankframework/stream/MessageContext.java
  core/src/main/java/org/frankframework/stream/UrlMessage.java
  core/src/test/java/org/frankframework/stream/MessageContextTest.java
  core/src/test/java/org/frankframework/stream/MessageTest.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemUtils.java
  messaging/src/main/java/org/frankframework/extensions/kafka/KafkaListener.java
  test/src/main/java/org/frankframework/pipes/RetrieveContextPipe.java
Labels: Technical Debt

#8512 Clean up some TODOs in XmlUtils and related code in callers
  core/src/main/java/org/frankframework/management/bus/endpoints/SecurityItems.java
  core/src/main/java/org/frankframework/util/XmlUtils.java
  larva/src/main/java/org/frankframework/extensions/test/IbisTester.java
  nn-specials/src/main/java/org/frankframework/extensions/svn/ScanTibcoSolutionPipe.java
  tibco/src/main/java/org/frankframework/extensions/tibco/GetTibcoQueues.java
Labels: Technical Debt

#8498 TransformerPool improvements and cleanups
  core/src/main/java/org/frankframework/align/content/JsonDocumentContainer.java
  core/src/main/java/org/frankframework/cache/AbstractCacheAdapter.java
  core/src/main/java/org/frankframework/errormessageformatters/FixedErrorMessageFormatter.java
  core/src/main/java/org/frankframework/http/AbstractHttpSender.java
  core/src/main/java/org/frankframework/parameters/AbstractParameter.java
  core/src/main/java/org/frankframework/pipes/AsyncSenderWithListenerPipe.java
  core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
  core/src/main/java/org/frankframework/pipes/IfPipe.java
  core/src/main/java/org/frankframework/pipes/IteratingPipe.java
  core/src/main/java/org/frankframework/pipes/JsonPipe.java
  core/src/main/java/org/frankframework/pipes/MessageSendingPipe.java
  core/src/main/java/org/frankframework/pipes/XmlSwitch.java
  core/src/main/java/org/frankframework/pipes/XmlValidator.java
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/main/java/org/frankframework/senders/FixedResultSender.java
  core/src/main/java/org/frankframework/soap/SoapWrapper.java
  core/src/main/java/org/frankframework/soap/SoapWrapperPipe.java
  core/src/main/java/org/frankframework/util/TransformerPool.java
  core/src/main/java/org/frankframework/util/XmlUtils.java
  core/src/main/java/org/frankframework/util/flow/DotFlowGenerator.java
  core/src/main/java/org/frankframework/util/flow/MermaidFlowGenerator.java
  core/src/test/java/org/frankframework/pipes/Json2WsdlXmlValidatorTest.java
  core/src/test/java/org/frankframework/util/FunctionalTransformerPoolTestBase.java
  core/src/test/java/org/frankframework/util/TransformerPoolNamespaceUnawarenessTest.java
  core/src/test/java/org/frankframework/util/TransformerPoolTest.java
  core/src/test/java/org/frankframework/util/flow/FlowDiagramTest.java
  filesystem/src/test/java/org/frankframework/filesystem/FileSystemTestBase.java
  ladybug/debugger/src/main/java/org/frankframework/ladybug/larva/ConvertToLarvaAction.java
  larva/src/main/java/org/frankframework/larva/XsltProviderListener.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsListener.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsSender.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisUtils.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisWrapperPipe.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsListener.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsTransactionalStorage.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/WsdlGeneratorPipe.java
  nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfWrapperPipe.java
  tibco/src/main/java/org/frankframework/extensions/tibco/SendTibcoMessage.java
Labels: Performance, Technical Debt
