Repository frankframework/frankframework, pull requests merged in 2025-03, with the labels that each got.

#8507 Improve adapter statistics overview
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/package.json
  console/frontend/src/main/frontend/src/app/views/adapterstatistics/adapterstatistics.component.html
  console/frontend/src/main/frontend/src/app/views/adapterstatistics/adapterstatistics.component.ts
Labels: FF! Console

#8535 Fix race condition on TransformerPool#getConfigMap
  core/src/main/java/org/frankframework/util/TransformerPool.java
Labels: Backport, 8.0

#8533 Fix race condition on TransformerPool#getConfigMap
  core/src/main/java/org/frankframework/util/TransformerPool.java
Labels: Backport, 8.1

#8534 Fix race condition on TransformerPool#getConfigMap
  core/src/main/java/org/frankframework/util/TransformerPool.java
Labels: Backport, 8.3

#8545 Keep form field values in session
  console/frontend/src/main/frontend/cypress/e2e/views/test-pipeline.cy.ts
  console/frontend/src/main/frontend/package-lock.json
  console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-browse-queue/jms-browse-queue.component.ts
  console/frontend/src/main/frontend/src/app/views/jms/jms-send-message/jms-send-message.component.ts
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.html
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.html
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
Labels: FF! Console

#8542 Make sure the storage id is present to be able to resend the message
  core/src/main/java/org/frankframework/jdbc/MessageStoreListener.java
  test/src/main/configurations/JMS/Configuration.xml
  test/src/main/configurations/JMS/ConfigurationMessageStoreListeners.xml
  test/src/test/testtool/MessageStoreSenderAndListener/scenario03/out-queue.xml
Labels: Backport, 9.0

#8569 Fix overwriting Monaco Editor with session value and add e2e video's
  console/frontend/src/main/frontend/cypress.config.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-execute-query/jdbc-execute-query.component.ts
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
  console/frontend/src/main/frontend/src/app/views/test-service-listener/test-service-listener.component.ts
Labels: FF! Console

#8574 Fix broken parameter pattern substitution (#8561)
  core/src/main/java/org/frankframework/parameters/AbstractParameter.java
  core/src/test/java/org/frankframework/http/HttpSenderTest.java
  core/src/test/java/org/frankframework/parameters/ParameterTest.java
  core/src/test/java/org/frankframework/testutil/ParameterBuilder.java
  core/src/test/resources/Http/Responses/simpleMockedHttpPostWithUrlPatternParam.txt
Labels: Backport, 8.3

#8579 Remove JMS dependency from ReceiverTest
  core/src/main/java/org/frankframework/receivers/Receiver.java
  core/src/test/java/org/frankframework/jms/PushingJmsListenerTest.java
  core/src/test/java/org/frankframework/jms/SlowListenerWithPollGuard.java
  core/src/test/java/org/frankframework/receivers/MockPushingListener.java
  core/src/test/java/org/frankframework/receivers/ReceiverTest.java
  core/src/test/java/org/frankframework/receivers/SlowListenerBase.java
  core/src/test/java/org/frankframework/receivers/SlowPullingListener.java
  core/src/test/java/org/frankframework/receivers/SlowPushingListener.java
Labels: Technical Debt

#8585 Fix message field bing overwriten by test pipeline session
  console/frontend/src/main/frontend/cypress/e2e/views/status.cy.ts
  console/frontend/src/main/frontend/src/app/views/test-pipeline/test-pipeline.component.ts
Labels: FF! Console

#8590 Fix errorlog issues when configuration doesnt have errors
  console/frontend/src/main/frontend/src/app/views/status/server-warnings/server-warnings.component.html
Labels: FF! Console

#8614 Disable flow diagram 'New tab' button on firefox (temp fix)
  console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.html
  console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.ts
Labels: FF! Console

#8623 Simplify peeking into message
  aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/CisConversionServiceImpl.java
  aspose/src/main/java/org/frankframework/extensions/aspose/services/conv/impl/MediaTypeValidator.java
  aws/src/test/java/org/frankframework/senders/AmazonS3SenderTest.java
  commons/src/main/java/org/frankframework/util/StreamUtil.java
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/main/java/org/frankframework/stream/SerializableFileReference.java
  core/src/main/java/org/frankframework/util/MessageUtils.java
  core/src/main/java/org/frankframework/util/XmlUtils.java
  core/src/test/java/org/frankframework/http/cxf/SoapProviderTest.java
  core/src/test/java/org/frankframework/pipes/ReplacerPipeTest.java
  core/src/test/java/org/frankframework/stream/MessageTest.java
  core/src/test/java/org/frankframework/util/MessageUtilsTest.java
  core/src/test/java/org/frankframework/util/StreamCaptureUtilsTest.java
Labels: Backport, 9.0

#8625 Improve flow modal buttons (better error feedback)
  console/frontend/src/main/frontend/src/app/views/status/flow/flow-modal/flow-modal.component.ts
Labels: FF! Console

#8641 Fix 'time' in parameter pattern (#8632)
  core/src/main/java/org/frankframework/parameters/AbstractParameter.java
  core/src/test/java/org/frankframework/parameters/DateParameterTest.java
  core/src/test/java/org/frankframework/parameters/ParameterTest.java
Labels: Backport, 8.3

#8644 MessageStoreListener only supports BLOB, forbid other message field types
  core/src/main/java/org/frankframework/jdbc/JdbcListener.java
  core/src/main/java/org/frankframework/jdbc/MessageStoreListener.java
  core/src/main/java/org/frankframework/jdbc/MessageStoreSender.java
  core/src/main/java/org/frankframework/pipes/AbstractValidator.java
  core/src/main/java/org/frankframework/pipes/JsonValidator.java
  core/src/main/java/org/frankframework/pipes/XmlValidator.java
  core/src/main/java/org/frankframework/soap/SoapValidator.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
  core/src/test/resources/Migrator/ChangelogBlobTests.xml
  messaging/src/test/java/org/frankframework/jms/PushingJmsListenerTest.java
Labels: Technical Debt

#8649 Disable default-value Configuration warnings
  core/src/main/resources/AppConstants.properties
  core/src/test/java/org/frankframework/configuration/digester/ValidateAttributeRuleTest.java
Labels: Backport, 9.0

#8655 Fix MigratorTest for MariaDB
  core/src/test/resources/Migrator/sql_changes_mariadb.sql
Labels: Technical Debt, JDBC

#8665 Fixes for several more JDBC test related issues
  core/src/main/java/org/frankframework/jdbc/JdbcListener.java
  core/src/test/java/org/frankframework/jdbc/FixedQuerySenderTest.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
  core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java
  management-gateway/src/test/java/org/frankframework/management/gateway/HazelcastEndToEndTest.java
Labels: Technical Debt, JDBC

#8659 Allow returning extra fields from JDBCTableListener
  core/src/main/java/org/frankframework/jdbc/JdbcListener.java
  core/src/main/java/org/frankframework/jdbc/JdbcQueryListener.java
  core/src/main/java/org/frankframework/jdbc/JdbcTableListener.java
  core/src/main/java/org/frankframework/jdbc/MessageStoreListener.java
  core/src/test/java/org/frankframework/jdbc/JdbcQueryListenerTest.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
  core/src/test/java/org/frankframework/jdbc/MessageStoreListenerTest.java
  core/src/test/java/org/frankframework/receivers/ListenerTestBase.java
  core/src/test/java/org/frankframework/receivers/MessageStoreListenerTest.java
Labels: JDBC

#8591 Console backend controllers refactor
  console/backend/src/main/java/org/frankframework/console/controllers/AdapterStatistics.java
  console/backend/src/main/java/org/frankframework/console/controllers/Adapters.java
  console/backend/src/main/java/org/frankframework/console/controllers/BrowseJdbcTable.java
  console/backend/src/main/java/org/frankframework/console/controllers/BrowseQueue.java
  console/backend/src/main/java/org/frankframework/console/controllers/ClassInfo.java
  console/backend/src/main/java/org/frankframework/console/controllers/ClusterMembers.java
  console/backend/src/main/java/org/frankframework/console/controllers/Configurations.java
  console/backend/src/main/java/org/frankframework/console/controllers/ExecuteJdbcQuery.java
  console/backend/src/main/java/org/frankframework/console/controllers/IbisstoreSummary.java
  console/backend/src/main/java/org/frankframework/console/controllers/Init.java
  console/backend/src/main/java/org/frankframework/console/controllers/LiquibaseScript.java
  console/backend/src/main/java/org/frankframework/console/controllers/Logging.java
  console/backend/src/main/java/org/frankframework/console/controllers/Monitors.java
  console/backend/src/main/java/org/frankframework/console/controllers/Scheduler.java
  console/backend/src/main/java/org/frankframework/console/controllers/SendJmsMessage.java
  console/backend/src/main/java/org/frankframework/console/controllers/ServerDetails.java
  console/backend/src/main/java/org/frankframework/console/controllers/TransactionalStorage.java
  console/backend/src/main/java/org/frankframework/console/controllers/UpdateLoggingConfig.java
  console/backend/src/main/java/org/frankframework/console/controllers/Webservices.java
  console/backend/src/test/java/org/frankframework/console/configuration/SecurityChainConfigurerTest.java
  console/backend/src/test/java/org/frankframework/console/configuration/SecurityChainConfigurerWithoutAuthenticationTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/AdapterStatisticsTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/AdaptersTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ApiTestBaseTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ConfigurationsTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/InitTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/MonitorsTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ServerDetailsTest.java
  console/backend/src/test/resources/management/web/MonitorTest_testAddTrigger.json
  console/backend/src/test/resources/management/web/MonitorTest_testAddTrigger_output.json
  console/backend/src/test/resources/management/web/MonitorTest_updateTrigger.json
  console/backend/src/test/resources/management/web/MonitorTest_updateTrigger_output.json
  console/backend/src/test/resources/management/web/init-with-roles.json
Labels: FF! Console
