Repository frankframework/frankframework, pull requests merged in 2025-04, with the labels that each got.

#8677 Remove console dateFormat AppConstant property
  console/frontend/src/main/frontend/src/app/app.service.ts
  console/frontend/src/main/frontend/src/app/services/server-time.service.ts
  core/src/main/resources/AppConstants.properties
Labels: FF! Console

#8683 Minor Jdbc Optimisation
  core/src/main/java/org/frankframework/jdbc/JdbcListener.java
  core/src/main/java/org/frankframework/jdbc/XmlQuerySender.java
  core/src/main/java/org/frankframework/util/JdbcUtil.java
  core/src/test/java/org/frankframework/jdbc/JdbcTableListenerTest.java
Labels: Technical Debt, JDBC

#8675 Add new CI workflow for running database-tests
  .github/workflows/database-tests.yml
  core/src/test/java/org/frankframework/jdbc/datasource/TestBlobs.java
Labels: CI, JDBC

#8693 Change WebContent to webcontent to make sure the naming is consistent
  core/src/main/java/org/frankframework/lifecycle/WebContentServlet.java
Labels: Backport, 9.0

#8697 Conditionally supress log warning
  core/src/main/java/org/frankframework/http/HttpMessageEntity.java
Labels: Backport, 9.0

#8702 Allow multiple HttpSenders per adapter
  core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
  core/src/main/java/org/frankframework/statistics/FrankMeterType.java
  core/src/test/java/org/frankframework/metrics/TestLocalStatisticsRegistry.java
  core/src/test/resources/metrics/myAdapter.json
  core/src/test/resources/metrics/myAdapter2.json
Labels: Backport, 9.0

#8714 Fix NPE in ladybug to larva code
  ladybug/src/main/java/nl/nn/ibistesttool/larva/ConvertToLarvaAction.java
Labels: Backport, 7.9

#8715 Fix NPE in ApiListenerServlet
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
Labels: Backport, 7.9

#8716 Fix NPE in ApiListenerServlet
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
Labels: Backport, 9.0

#8719 Make sure to output text/html for the WebContentServlet overview page
  core/src/main/java/org/frankframework/lifecycle/WebContentServlet.java
Labels: Backport, 9.0

#8720 Make sure to output text/html for the WebContentServlet overview page
  core/src/main/java/nl/nn/adapterframework/lifecycle/WebContentServlet.java
Labels: Backport, 7.9

#8726 Update dependencies for CVE's
  pom.xml
Labels: Dependencies, 9.0

#8727 Update dependencies for CVE's
  pom.xml
Labels: Dependencies, 8.3

#8728 Fix PK name in test table (#8706)
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml
Labels: 9.0

#8730 Update json-smart
  pom.xml
Labels: Dependencies, 8.3

#8732 Fix PK name in test table
  core/src/test/resources/Jdbc/StoredProcedureQuerySender/DatabaseChangelog-StoredProcedures.xml
Labels: Backport, 8.3

#8740 Update ladybug CXF dependency version
  ladybug/common/pom.xml
Labels: Dependencies, 9.0

#8709 Skip slow and database tests in most Github runs
  .github/workflows/database-tests.yml
  .github/workflows/maven-build.yml
  console/frontend/pom.xml
  core/pom.xml
  core/src/test/java/org/frankframework/components/ComponentLoaderTest.java
  core/src/test/java/org/frankframework/testutil/TestAssertions.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemListenerTest.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemSenderTest.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/ftp/FtpFileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/ftp/FtpFileSystemListenerTest.java
  filesystem/src/test/java/org/frankframework/filesystem/ftp/FtpFileSystemSenderTest.java
  filesystem/src/test/java/org/frankframework/filesystem/ftp/FtpFileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/sftp/SftpFileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/sftp/SftpFileSystemListenerTest.java
  filesystem/src/test/java/org/frankframework/filesystem/sftp/SftpFileSystemSenderTest.java
  filesystem/src/test/java/org/frankframework/filesystem/sftp/SftpFileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba1FileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba1FileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba2FileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba2FileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba2FileSystemTestHelper.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba2ListenerTest.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba2PipeTest.java
  filesystem/src/test/java/org/frankframework/filesystem/smb/Samba2SenderTest.java
  ladybug/rerunner/pom.xml
  management-gateway/src/test/java/org/frankframework/management/gateway/HazelcastEndToEndTest.java
  pom.xml
  test/pom.xml
Labels: CI

#8751 Allow users to update websocket interval
  console/backend/src/main/java/org/frankframework/console/controllers/socket/EventHandler.java
  console/war/src/main/resources/application.properties
  core/src/main/resources/AppConstants.properties
Labels: Backport, 8.3

#8752 Allow users to update websocket interval
  console/backend/src/main/java/org/frankframework/console/controllers/socket/EventHandler.java
  console/war/src/main/resources/application.properties
  core/src/main/resources/AppConstants.properties
Labels: Backport, 9.0

#8749 Some Category reorgs of the AppConstants
  core/src/main/resources/AppConstants.properties
Labels: Documentation

#8753 Update transitive cxf dependencies
  console/war/pom.xml
  ladybug/pom.xml
  ladybug/rerunner/pom.xml
  pom.xml
Labels: Backport, 8.3

#8757 Add documentation and lowered access modifiers where possible
  FRANKDOC.md
  credentialProvider/src/main/java/org/frankframework/credentialprovider/AbstractMapCredentialFactory.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/AnsibleVaultCredentialFactory.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/FileSystemCredentialFactory.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/ICredentialFactory.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/PropertyFileCredentialFactory.java
  credentialProvider/src/main/java/org/frankframework/credentialprovider/WildFlyCredentialFactory.java
  kubernetes/src/main/java/org/frankframework/credentialprovider/KubernetesCredentialFactory.java
Labels: Documentation, Credential Provider, 9.1

#8776 Make health check expression configurable
  console/backend/src/main/java/org/frankframework/console/configuration/SecurityChainConfigurer.java
  core/src/main/resources/AppConstants.properties
  credentialProvider/src/main/java/org/frankframework/credentialprovider/delinea/DelineaCredentialFactory.java
Labels: Security

#8777 Use @code tags in javadoc and move yml code example on method to class level
  security/src/main/java/org/frankframework/lifecycle/servlets/ActiveDirectoryAuthenticator.java
  security/src/main/java/org/frankframework/lifecycle/servlets/InMemoryAuthenticator.java
  security/src/main/java/org/frankframework/lifecycle/servlets/JeeAuthenticator.java
  security/src/main/java/org/frankframework/lifecycle/servlets/NoOpAuthenticator.java
  security/src/main/java/org/frankframework/lifecycle/servlets/OAuth2Authenticator.java
  security/src/main/java/org/frankframework/lifecycle/servlets/YmlFileAuthenticator.java
Labels: Documentation

#8767 Fix infinite stacktrace that leads to stackoverflow
  core/src/main/java/org/frankframework/xml/SaxException.java
Labels: Backport, 9.0

#8768 Fix infinite stacktrace that leads to stackoverflow
  core/src/main/java/org/frankframework/xml/SaxException.java
Labels: Backport, 8.3

#8769 Fix infinite stacktrace that leads to stackoverflow
  core/src/main/java/nl/nn/adapterframework/xml/SaxException.java
Labels: Backport, 7.9

#8782 Ignore the ComponentLoaderTest when running tests within IntelliJ
  core/src/test/java/org/frankframework/components/ComponentLoaderTest.java
  core/src/test/java/org/frankframework/testutil/TestAssertions.java
Labels: Technical Debt

#8781 Improved caching of TransformerPools
  core/src/main/java/org/frankframework/documentbuilder/json/JsonUtils.java
  core/src/main/java/org/frankframework/pipes/JsonPipe.java
  core/src/main/java/org/frankframework/soap/SoapWrapper.java
  core/src/main/java/org/frankframework/util/TransformerPool.java
  core/src/main/java/org/frankframework/util/XmlUtils.java
  core/src/test/java/org/frankframework/pipes/JsonPipeTest.java
Labels: Technical Debt

#8710 First draft running Larva tests in the Integration Tests
  docker/db2-xa.yml
  docker/db2.yml
  docker/mariadb.yml
  docker/mssql.yml
  docker/mysql.yml
  docker/oracle-xa.yml
  docker/oracle.yml
  docker/postgres-xa.yml
  docker/postgres.yml
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/ScenarioRunner.java
  pom.xml
  test/pom.xml
  test/src/main/configurations/JDBC/ConfigurationStoredProcedureSender.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/test/java/org/frankframework/runner/HtmlTagStrippingWriter.java
  test/src/test/java/org/frankframework/runner/RunCypressE2eTest.java
  test/src/test/java/org/frankframework/runner/RunLarvaTests.java
  test/src/test/testtool/JdbcSenders/scenario06.properties
Labels: CI

#8770 Show console version info on ff version mismatch
  console/backend/src/main/java/org/frankframework/console/controllers/ConsoleDetails.java
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.html
  console/frontend/src/main/frontend/src/app/components/pages/information-modal/information-modal.component.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-footer/pages-footer.component.html
  console/frontend/src/main/frontend/src/app/components/pages/pages-footer/pages-footer.component.scss
  console/frontend/src/main/frontend/src/app/components/pages/pages-footer/pages-footer.component.spec.ts
  console/frontend/src/main/frontend/src/app/components/pages/pages-footer/pages-footer.component.ts
  console/frontend/src/main/frontend/src/app/services/server-info.service.ts
Labels: FF! Console

#8806 Make sure to pass the exception to the log and reformat the javadoc
  core/src/main/java/org/frankframework/pipes/IfPipe.java
Labels: Backport, Documentation, 9.1

#8804 Update SECURITY.md
  SECURITY.md
Labels: Dependencies, Documentation

#8819 Rename "queue" variables and strings in Larva to "action"
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
  larva/src/main/java/org/frankframework/larva/ScenarioRunner.java
  larva/src/main/java/org/frankframework/larva/actions/AbstractLarvaAction.java
  larva/src/main/java/org/frankframework/larva/actions/LarvaAction.java
  larva/src/main/java/org/frankframework/larva/actions/LarvaActionFactory.java
  larva/src/main/java/org/frankframework/larva/actions/LarvaActionUtils.java
  larva/src/main/java/org/frankframework/larva/actions/LarvaPushingListenerAction.java
  larva/src/main/java/org/frankframework/larva/actions/PullingListenerAction.java
Labels: Technical Debt

#8825 Allow JWT Token to omit "Bearer" when it is a non-standard header (#8818)
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListener.java
  core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java
  core/src/test/java/nl/nn/adapterframework/http/rest/ApiListenerServletTest.java
Labels: Backport, 7.9

#8824 Allow JWT Token to omit "Bearer" when it is a non-standard header (#8818)
  core/src/main/java/org/frankframework/http/rest/ApiListener.java
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
Labels: Backport, 8.3

#8823 Allow JWT Token to omit "Bearer" when it is a non-standard header (#8818)
  core/src/main/java/org/frankframework/http/rest/ApiListener.java
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
Labels: Backport, 9.0

#8821 Fix adapter pipes & receivers disappearing after certain adapter updates
  console/frontend/src/main/frontend/src/app/app.component.ts
Labels: FF! Console

#8834 The BusAction should be logged before the BusTopic to be consistent (#8830)
  console/backend/src/main/java/org/frankframework/console/util/RequestMessageBuilder.java
  console/backend/src/test/java/org/frankframework/console/controllers/AdaptersTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ConfigurationsTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ConnectionOverviewTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/EnvironmentVariablesTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/InlineMessageStoreOverviewTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/SecurityItemsTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ServerDetailsTest.java
Labels: Backport, 9.1

#8835 Change Console Log Levels
  akamai/src/main/java/org/frankframework/extensions/akamai/HashAlgorithm.java
  akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageRequest.java
  akamai/src/main/java/org/frankframework/extensions/akamai/NetStorageSender.java
  akamai/src/test/java/org/frankframework/extensions/akamai/NetStorageCmsSignerTest.java
  akamai/src/test/java/org/frankframework/extensions/akamai/NetStorageSenderTest.java
  console/backend/src/main/java/org/frankframework/console/util/RequestMessageBuilder.java
  console/backend/src/main/java/org/frankframework/console/util/RequestUtils.java
  console/backend/src/main/java/org/frankframework/console/util/ResponseUtils.java
  console/backend/src/test/java/org/frankframework/console/controllers/ConfigurationStatusTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ConfigurationsEndpointTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ConnectionOverviewTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/EnvironmentVariablesTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/InlineMessageStoreOverviewTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/SecurityItemsTest.java
  console/backend/src/test/java/org/frankframework/console/controllers/ServerStatisticsTest.java
  console/war/src/main/resources/application.properties
  core/src/main/resources/AppConstants.properties
  management-gateway/src/main/java/org/frankframework/management/gateway/events/AbstractGatewayEvent.java
  management-gateway/src/main/java/org/frankframework/management/gateway/events/ClusterMemberEvent.java
  security/src/main/java/org/frankframework/lifecycle/servlets/ServletConfiguration.java
  security/src/test/java/org/frankframework/lifecycle/servlets/DummyAuthenticator.java
  security/src/test/java/org/frankframework/lifecycle/servlets/DummyAuthenticatorTest.java
  security/src/test/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorTest.java
  security/src/test/java/org/frankframework/lifecycle/servlets/YmlFileAuthenticatorTest.java
Labels: Backport, 9.0

#8750 replace inheritDoc with inheritClassDoc for classes
  FRANKDOC.md
  core/src/main/java/org/frankframework/http/HttpSender.java
  core/src/main/java/org/frankframework/pipes/AsyncSenderWithListenerPipe.java
  core/src/main/java/org/frankframework/pipes/SenderPipe.java
  core/src/main/java/org/frankframework/scheduler/job/ActionJob.java
  core/src/main/java/org/frankframework/scheduler/job/CleanupDatabaseJob.java
  core/src/main/java/org/frankframework/scheduler/job/CleanupFileSystemJob.java
  core/src/main/java/org/frankframework/scheduler/job/ExecuteQueryJob.java
  core/src/main/java/org/frankframework/scheduler/job/SendMessageJob.java
  filesystem/src/main/java/org/frankframework/receivers/DirectoryListener.java
  filesystem/src/main/java/org/frankframework/receivers/FtpFileSystemListener.java
  filesystem/src/main/java/org/frankframework/receivers/Samba2Listener.java
  filesystem/src/main/java/org/frankframework/receivers/SambaListener.java
  filesystem/src/main/java/org/frankframework/receivers/SftpFileSystemListener.java
  messaging/src/main/java/org/frankframework/extensions/ibm/IMSSender.java
  messaging/src/main/java/org/frankframework/extensions/ibm/MQSender.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttListener.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttSender.java
  messaging/src/main/java/org/frankframework/jms/AbstractJmsListener.java
  messaging/src/main/java/org/frankframework/jms/AbstractJmsMessageBrowser.java
  messaging/src/main/java/org/frankframework/jms/JmsBrowser.java
  messaging/src/main/java/org/frankframework/jms/JmsListener.java
  messaging/src/main/java/org/frankframework/jms/JmsSender.java
  messaging/src/main/java/org/frankframework/jms/JmsTransactionalStorage.java
  messaging/src/main/java/org/frankframework/jms/PullingJmsListener.java
  messaging/src/main/java/org/frankframework/jms/PushingJmsListener.java
  nn-specials/src/main/java/org/frankframework/extensions/bis/BisJmsListener.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsListener.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsSender.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsTransactionalStorage.java
  nn-specials/src/main/java/org/frankframework/extensions/fxf/FxfListener.java
  sap/src/main/java/org/frankframework/extensions/sap/IdocSender.java
  sap/src/main/java/org/frankframework/extensions/sap/SapListener.java
  sap/src/main/java/org/frankframework/extensions/sap/SapSender.java
  sap/src/main/java/org/frankframework/extensions/sap/SapSystem.java
  tibco/src/main/java/org/frankframework/extensions/tibco/TibcoLogJmsListener.java
Labels: Documentation, Refactor

#8676 Only show existing columns in message storage views
  console/backend/src/main/java/org/frankframework/console/controllers/TransactionalStorage.java
  console/backend/src/test/java/org/frankframework/console/controllers/TransactionalStorageTest.java
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
  console/frontend/src/main/frontend/src/app/views/storage/storage-view/storage-view.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage-view/storage-view.component.scss
  console/frontend/src/main/frontend/src/app/views/storage/storage-view/storage-view.component.ts
  console/frontend/src/main/frontend/src/app/views/storage/storage.service.ts
  core/src/main/java/org/frankframework/core/IMessageBrowser.java
  core/src/main/java/org/frankframework/core/MessageBrowserField.java
  core/src/main/java/org/frankframework/jdbc/AbstractJdbcMessageBrowser.java
  core/src/main/java/org/frankframework/jdbc/JdbcTableMessageBrowser.java
  core/src/main/java/org/frankframework/management/bus/dto/StorageItemsDTO.java
  core/src/main/java/org/frankframework/management/bus/endpoints/BrowseMessageBrowsers.java
  core/src/test/java/org/frankframework/management/bus/endpoints/TestBrowseMessageBrowsers.java
  core/src/test/resources/Management/MessageBrowserFindAll.json
  core/src/test/resources/Management/MessageBrowserFindNone.json
  core/src/test/resources/Management/MessageBrowserFindOne.json
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemMessageBrowser.java
  management-gateway/src/main/java/org/frankframework/management/bus/BusMessageUtils.java
  messaging/src/main/java/org/frankframework/jms/AbstractJmsMessageBrowser.java
Labels: FF! Console

#8856 Ensure there is an upgrade path and improve deprecation warnings
  batch/src/main/java/org/frankframework/jdbc/Result2LobWriterBase.java
  nn-specials/src/main/java/org/frankframework/extensions/api/ApiStreamPipe.java
Labels: Backport, 9.1

#8847 Filtering on message storage with dynamic columns
  console/frontend/src/main/frontend/src/app/services/session.service.ts
  console/frontend/src/main/frontend/src/app/views/iaf-update/iaf-update.component.ts
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list.component.ts
Labels: FF! Console

#8861 Fix larva in ladybug reports
  console/frontend/pom.xml
  ladybug/debugger/src/main/java/org/frankframework/ladybug/IbisDebuggerAdvice.java
  larva/src/main/java/org/frankframework/larva/queues/QueueCreator.java
  larva/src/main/java/org/frankframework/larva/queues/QueueUtils.java
Labels: 9.1
