Repository frankframework/frankframework, pull requests merged in 2025-08, with the labels that each got.

#9406 Remove a few more unneeded invocations of PipeLineSession#unscheduleCloseOnSessionExit
  core/src/main/java/org/frankframework/compression/ZipWriter.java
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/main/java/org/frankframework/receivers/JavaListener.java
  core/src/main/java/org/frankframework/senders/FrankSender.java
  core/src/main/java/org/frankframework/senders/IbisLocalSender.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
  larva/src/main/java/org/frankframework/larva/SenderThread.java
Labels: Technical Debt

#9427 Improvements to the JavaDoc of class UUIDUtil
  commons/src/main/java/org/frankframework/util/UUIDUtil.java
Labels: Documentation

#9439 Fix no ladybug reports when using PostgreSQL
  docker/JBoss/src/configuration/standalone.xml
  docker/Tomcat/webapp/src/scripts/catalinaAdditional.properties
  docker/WildFly/src/configuration/standalone.xml
  ladybug/debugger/src/main/java/org/frankframework/ladybug/LadybugDebugger.java
  ladybug/debugger/src/main/java/org/frankframework/ladybug/LadybugPipe.java
  ladybug/pom.xml
  larva/src/main/java/org/frankframework/larva/SenderThread.java
  larva/src/main/java/org/frankframework/larva/actions/SenderAction.java
  test/src/main/configurations/UTIL/ConfigurationLadybug.xml
  test/src/main/resources/DeploymentSpecifics.properties
  test/src/test/java/org/frankframework/runner/RunLarvaTests.java
  test/src/test/testtool/LadybugIntegration/Diacritics.report.xml
  test/src/test/testtool/LadybugIntegration/Hello World.report.xml
  test/src/test/testtool/LadybugIntegration/Pipeline MainConfig_EchoPipe.report.xml
  test/src/test/testtool/LadybugIntegration/common.properties
  test/src/test/testtool/LadybugIntegration/scenario01.properties
  test/src/test/testtool/LadybugIntegration/scenario01/output.json
  test/src/test/testtool/LadybugIntegration/scenario02.properties
  test/src/test/testtool/LadybugIntegration/scenario02/in.txt
  test/src/test/testtool/LadybugIntegration/scenario02/out.xml
Labels: Backport, 9.2

#9440 Fix ObjectFactories
  core/src/main/java/org/frankframework/jdbc/datasource/ObjectFactory.java
  core/src/main/java/org/frankframework/jdbc/datasource/ResourceObjectLocator.java
  core/src/main/java/org/frankframework/mongodb/MongoClientFactory.java
  core/src/main/java/org/frankframework/mongodb/MongoClientFactoryFactory.java
  core/src/main/java/org/frankframework/mongodb/MongoDbSender.java
  core/src/main/resources/SpringApplicationContext.xml
  core/src/test/java/org/frankframework/mongodb/MongoDbSenderTest.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttClientFactory.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttClientFactoryFactory.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttFacade.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttListener.java
  messaging/src/main/java/org/frankframework/extensions/mqtt/MqttSender.java
  messaging/src/main/resources/springJms.xml
  messaging/src/test/java/org/frankframework/extensions/mqtt/MqttClientFactoryFactoryTest.java
  messaging/src/test/java/org/frankframework/extensions/mqtt/MqttSenderTest.java
Labels: Backport, 9.2

#9455 Fix Console JDBC Tables displaying message count
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
Labels: FF! Console, Backport, 9.0

#9456 Fix Console JDBC Tables displaying message count
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
Labels: FF! Console, Backport, 8.3

#9457 Fix Console JDBC Tables displaying message count
  console/frontend/src/main/frontend/src/app/views/jdbc/jdbc-browse-tables/jdbc-browse-tables.component.ts
Labels: FF! Console, Backport, 7.9

#9464 Split PkiUtil so it can be used in plugins
  commons/pom.xml
  commons/src/main/java/org/frankframework/encryption/CommonsPkiUtil.java
  commons/src/main/java/org/frankframework/encryption/KeystoreType.java
  commons/src/test/java/org/frankframework/encryption/CommonsPkiUtilTest.java
  commons/src/test/java/org/frankframework/encryption/KeystoreTypeTest.java
  core/src/main/java/org/frankframework/encryption/AuthSSLContextFactory.java
  core/src/main/java/org/frankframework/encryption/CorePkiUtil.java
  core/src/main/java/org/frankframework/http/authentication/SamlAssertionOauth.java
  core/src/main/java/org/frankframework/management/bus/endpoints/SecurityItems.java
  core/src/main/java/org/frankframework/pipes/SignaturePipe.java
  core/src/test/java/org/frankframework/encryption/AuthenticationContextFactoryTest.java
  core/src/test/java/org/frankframework/encryption/CorePkiUtilTest.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/org/frankframework/pipes/SignaturePipeTest.java
Labels: Refactor

#9506 Message store disable button when its not current action
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.ts
Labels: FF! Console

#9509 Message store disable button when its not current action
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
Labels: FF! Console, Backport, 9.0

#9508 Message store disable button when its not current action
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.html
  console/frontend/src/main/frontend/src/app/views/storage/storage-list/storage-list-dt/storage-list-dt.component.ts
Labels: FF! Console, Backport, 9.2

#9528 7.9: Update dependencies
  core/pom.xml
  pom.xml
Labels: Dependencies, 7.9

#9530 9.2: Update dependencies
  pom.xml
Labels: Dependencies, 9.2

#9535 Update dependencies
  pom.xml
Labels: Dependencies, 9.2

#9543 Fix incorrect JavaDoc tags
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisHttpSender.java
  core/src/main/java/org/frankframework/logging/IbisMaskingLayout.java
  core/src/main/java/org/frankframework/pipes/GetPrincipalPipe.java
  core/src/main/java/org/frankframework/pipes/XmlIf.java
  core/src/main/java/org/frankframework/util/flow/GraphvizJsFlowGenerator.java
  messaging/src/main/java/org/frankframework/jms/JmsBrowser.java
  messaging/src/main/java/org/frankframework/jms/JmsTransactionalStorage.java
  nn-specials/src/main/java/org/frankframework/extensions/esb/EsbJmsSender.java
Labels: Documentation

#9557 Wrap enum from external JAR in our own enum class to work around Frank!Doc limitation
  aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystem.java
  aws/src/main/java/org/frankframework/filesystem/AmazonS3FileSystemDelegator.java
  aws/src/main/java/org/frankframework/filesystem/S3StorageClass.java
  core/src/main/resources/xml/xsd/FrankConfig-compatibility.xsd
  core/src/main/resources/xml/xsd/FrankConfig.xsd
Labels: FF! Doc, Documentation
