Repository frankframework/frankframework, pull requests merged in 2025-01, with the labels that each got.

#8160 Prepare for next release cycle
  docker/.env
  pom.xml
Labels: 9.1

#8184 Bump Ladybug from 3.0-20241223.170709 to 3.0-20250107.001038
  ladybug/pom.xml
Labels: Backport, 9.0

#8194 Update app initialization to use AppConstants 'Global' instead of 'All'
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/custom-views/custom-views.component.ts
Labels: Bug, FF! Console

#8195 Update app initialization to use AppConstants 'Global' instead of 'All'
  console/frontend/src/main/frontend/src/app/app.component.ts
  console/frontend/src/main/frontend/src/app/components/custom-views/custom-views.component.ts
Labels: FF! Console, Backport

#8204 Only setup exchange graph connection once (#8188)
  .github/workflows/maven-build.yml
  filesystem/src/main/java/org/frankframework/filesystem/MsalClientAdapter.java
  filesystem/src/main/java/org/frankframework/filesystem/exchange/ExchangeFileSystem.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeConnectionCache.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemActorTest.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemListenerTest.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemSenderTest.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemTest.java
  filesystem/src/test/java/org/frankframework/filesystem/exchange/ExchangeFileSystemTestHelper.java
Labels: Backport, 9.0

#8213 Fix for XML2JSON mapping with wildcard-elements with nested elements (#8206)
  core/src/main/java/org/frankframework/align/XmlAligner.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/Json2Xml/WildcardElements/ExpectedOutput.json
  core/src/test/resources/Validation/Json2Xml/WildcardElements/Wildcard-Input.xml
  core/src/test/resources/Validation/Json2Xml/WildcardElements/Wildcard.xsd
  core/src/test/resources/Validation/Xsd1.1/Wildcard/in_OK.xml
Labels: Backport, 9.0

#8225 Enable monitoring by default
  console/backend/src/main/java/org/frankframework/console/controllers/Init.java
  core/src/main/resources/AppConstants.properties
Labels: Backport, 9.0

#8218 Allow configurations to be stopped from Console
  console/backend/src/main/java/org/frankframework/console/controllers/ConfigurationsEndpoint.java
  console/backend/src/test/java/org/frankframework/console/controllers/ConfigurationsEndpointTest.java
  console/frontend/src/main/frontend/src/app/pipes/configuration-filter.pipe.ts
  console/frontend/src/main/frontend/src/app/views/security-items/security-items.service.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.html
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
  console/frontend/src/main/frontend/src/assets/css/bootstrap-fix.css
  core/src/main/java/org/frankframework/unmanaged/DefaultIbisManager.java
Labels: FF! Console

#8248 Fix race condition on TransformerPool#getConfigMap (#8236)
  core/src/main/java/org/frankframework/util/TransformerPool.java
Labels: Backport, 9.0

#8267 Backport configuration warning to HttpSender
  core/src/main/java/org/frankframework/http/HttpSender.java
Labels: 9.0

#8276 Remove some overloads of the `configure()` method
  core/src/main/java/org/frankframework/core/IConfigurable.java
  core/src/main/java/org/frankframework/core/IListener.java
  core/src/main/java/org/frankframework/core/IPipe.java
  core/src/main/java/org/frankframework/core/ISender.java
Labels: Technical Debt

#8289 Reduce memory footprint when using iterating pipes and returned sessionkeys (#8528)
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
  core/src/test/java/org/frankframework/processors/InputOutputPipeProcessorTest.java
Labels: 8.3

#8288 Reduce memory footprint when using iterating pipes and returned sessionkeys (#8528)
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
  core/src/test/java/org/frankframework/processors/InputOutputPipeProcessorTest.java
Labels: 9.0

#8290 Reduce memory footprint when using iterating pipes and returned sessionkeys (#8528)
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
  core/src/test/java/org/frankframework/processors/InputOutputPipeProcessorTest.java
Labels: 8.0

#8280 Cleanups related to PipeLineSession#closeables
  cmis/src/main/java/org/frankframework/extensions/cmis/CmisSender.java
  core/src/main/java/org/frankframework/collection/AbstractCollectorPipe.java
  core/src/main/java/org/frankframework/core/Adapter.java
  core/src/main/java/org/frankframework/core/IPipe.java
  core/src/main/java/org/frankframework/core/PipeLineSession.java
  core/src/main/java/org/frankframework/http/HttpSender.java
  core/src/main/java/org/frankframework/http/rest/ApiListenerServlet.java
  core/src/main/java/org/frankframework/mongodb/MongoDbSender.java
  core/src/main/java/org/frankframework/monitoring/MonitorDestination.java
  core/src/main/java/org/frankframework/pipes/Base64Pipe.java
  core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
  core/src/main/java/org/frankframework/pipes/IteratingPipe.java
  core/src/main/java/org/frankframework/pipes/LogContextPipe.java
  core/src/main/java/org/frankframework/pipes/ReplacerPipe.java
  core/src/main/java/org/frankframework/processors/InputOutputPipeProcessor.java
  core/src/main/java/org/frankframework/receivers/JavaListener.java
  core/src/main/java/org/frankframework/senders/FrankSender.java
  core/src/main/java/org/frankframework/senders/IbisLocalSender.java
  core/src/main/java/org/frankframework/senders/ReconnectSenderWrapper.java
  core/src/main/java/org/frankframework/stream/Message.java
  core/src/main/java/org/frankframework/util/JdbcUtil.java
  core/src/test/java/org/frankframework/core/PipeLineSessionBaseTest.java
  core/src/test/java/org/frankframework/core/PipeLineSessionTest.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerServletTest.java
  core/src/test/java/org/frankframework/pipes/Base64PipeTest.java
  core/src/test/java/org/frankframework/pipes/PipeTestBase.java
  core/src/test/java/org/frankframework/senders/IbisLocalSenderTest.java
  core/src/test/java/org/frankframework/senders/ShadowSenderTest.java
  core/src/test/java/org/frankframework/stream/SerializableFileReferenceTest.java
  filesystem/src/main/java/org/frankframework/filesystem/FileSystemActor.java
  filesystem/src/main/java/org/frankframework/filesystem/MsalClientAdapter.java
  ladybug/debugger/src/main/java/org/frankframework/ladybug/IbisDebuggerAdvice.java
  ladybug/debugger/src/main/java/org/frankframework/ladybug/PipeLineSessionDebugger.java
  larva/src/main/java/org/frankframework/larva/LarvaTool.java
Labels: Technical Debt

#8309 Add Json2Xml fix with Multi-valued params and Message in session (#8292)
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/test/java/org/frankframework/align/TestJson2Xml.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Align/MultidimensionalArray/hierarchicalEmployee.xsd
  core/src/test/resources/Align/MultidimensionalArray/input.json
  core/src/test/resources/Align/MultidimensionalArray/output.xml
  core/src/test/resources/Align/MultidimensionalArray/schema.xsd
  core/src/test/resources/Validation/Parameters/out.xml
  core/src/test/resources/Validation/Parameters/simple.xsd
Labels: 8.3

#8317 Deprecate SchedulerSender
  core/src/main/java/org/frankframework/scheduler/SchedulerSender.java
Labels: 8.3

#8316 Deprecate SchedulerSender
  core/src/main/java/org/frankframework/scheduler/SchedulerSender.java
Labels: 8.0

#8318 Log potential errors when creating narayana database
  core/src/main/java/org/frankframework/jta/narayana/PoolingDataSourceJDBCAccess.java
Labels: 8.3

#8322 Fix validation for multivalued parameters / session-keys
  core/src/main/java/org/frankframework/align/Json2Xml.java
  core/src/main/java/org/frankframework/align/ToXml.java
  core/src/main/java/org/frankframework/align/Tree2Xml.java
  core/src/test/java/org/frankframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Validation/Parameters/out.xml
  core/src/test/resources/Validation/Parameters/simple.xsd
Labels: 8.0

#8314 Improve ApiListener options documentation and exception
  core/src/main/java/org/frankframework/http/rest/ApiListener.java
  core/src/test/java/org/frankframework/http/rest/ApiListenerTest.java
Labels: Backport, 9.0

#8291 Add test for Json2Xml with Multi-valued parameters
  core/src/test/java/nl/nn/adapterframework/align/TestJson2Xml.java
  core/src/test/java/nl/nn/adapterframework/pipes/Json2XmlValidatorTest.java
  core/src/test/resources/Align/MultidimensionalArray/hierarchicalEmployee.xsd
  core/src/test/resources/Align/MultidimensionalArray/input.json
  core/src/test/resources/Align/MultidimensionalArray/output.xml
  core/src/test/resources/Align/MultidimensionalArray/schema.xsd
  core/src/test/resources/Validation/Parameters/out.xml
  core/src/test/resources/Validation/Parameters/simple.xsd
Labels: 7.8

#8329 fix: update queryParamsHandling and replaceUrl
  console/frontend/src/main/frontend/src/app/components/monaco-editor/monaco-editor.component.ts
  console/frontend/src/main/frontend/src/app/components/tab-list/configuration-tab-list.component.ts
  console/frontend/src/main/frontend/src/app/views/configurations/configurations-show/configurations-show.component.ts
  console/frontend/src/main/frontend/src/app/views/status/status.component.ts
Labels: Backport, 9.0

#8326 Fix duplicate server warning response
  console/backend/src/main/java/org/frankframework/console/controllers/FrankApiService.java
  console/backend/src/main/java/org/frankframework/console/controllers/ServerStatistics.java
  console/backend/src/main/java/org/frankframework/console/controllers/socket/FrankApiWebSocketBase.java
  console/backend/src/test/java/org/frankframework/console/controllers/WebTestConfiguration.java
  console/frontend/src/main/frontend/src/app/app.component.ts
Labels: FF! Console

#8328 Fix duplicate server warning response
  console/backend/src/main/java/org/frankframework/console/controllers/FrankApiService.java
  console/backend/src/main/java/org/frankframework/console/controllers/ServerStatistics.java
  console/backend/src/main/java/org/frankframework/console/controllers/socket/FrankApiWebSocketBase.java
  console/backend/src/test/java/org/frankframework/console/controllers/WebTestConfiguration.java
  console/frontend/src/main/frontend/src/app/app.component.ts
Labels: FF! Console, Backport, 9.0
